# LSTM Pos-Tagger using PyTorch

In [3]:
# importing Comet first
# Used to log data about our experiment

from comet_ml import Experiment

In [4]:
import data
import torch, os
import torch.optim as optim
import torch.nn as nn
from tqdm import tqdm
from torch.nn import functional
from torch.nn import Module
from torch.utils.data import Dataset, DataLoader

device = torch.device('cpu')

##
# Loading the corpus into the following variables
#    train_dataloader           DataLoader for iterating over the training data
#    dev_dataloader             DataLoader for iterating over the development data
#    test_dataloader            DataLoader for iterating over the test data
#    vocabulary                 Vocabulary of words in the sentences in the data
#    tagset                     Vocabulary of POS tags in the data
#    pretrained_embeddings      Pretrained fasttext word embeddings 
##

train_dataloader,dev_dataloader,test_dataloader,vocabulary,tagset,pretrained_embeddings = data.load(
'corpus/de_gsd-ud-train.conllu',
'corpus/de_gsd-ud-dev.conllu',
'corpus/de_gsd-ud-test.conllu'
)

In [5]:
##
# Print information of Embeddings, Tagset and Vocab
##

print("\nPretrained Embeddings shape:")
print(pretrained_embeddings.shape)

print("\nTagset size:{}\n".format(len(tagset)))
print('Tags:\n{}'.format(tagset.lookup_tokens(range(0,len(tagset)))))

print("\nVocab size: {}".format(len(vocabulary)))

print("\nVocab sample:")
print(vocabulary.lookup_tokens(range(0,50)))




Pretrained Embeddings shape:
torch.Size([50506, 300])

Tagset size:18

Tags:
['NOUN', 'PUNCT', 'DET', 'ADP', 'PROPN', 'VERB', 'ADJ', 'ADV', 'PRON', 'AUX', 'CCONJ', 'NUM', '_', 'PART', 'SCONJ', 'X', 'SYM', 'INTJ']

Vocab size: 50506

Vocab sample:
['<unk>', '<pad>', '</s>', ',', 'der', 'die', 'in', 'und', 'dem', '-', 'von', 'zu', 'den', 'das', 'im', 'mit', 'ist', 'er', 'des', 'an', '"', ')', '(', 'ein', 'eine', 'auf', 'als', 'für', 'sich', 'wurde', 'auch', 'war', 'nach', 'bei', 'sie', 'es', 'nicht', 'aus', 'bis', 'sind', 'einer', 'werden', 'zum', 'durch', 'wird', 'ich', 'am', 'einen', 'einem', 'zur']


In [6]:
for minibatch in train_dataloader:

    print('Shape of the batch Tensor objects: {}'.format(minibatch.size()))
    print('\nFirst POS Tags:\n')
    print(' '.join(tagset.lookup_tokens(minibatch[0][1].flatten().tolist())))
    print('\nFirst Sentence:\n')
    print(' '.join(vocabulary.lookup_tokens(minibatch[0][0].flatten().tolist())))
    break

Shape of the batch Tensor objects: torch.Size([1, 2, 16])

First POS Tags:

ADV ADJ NOUN PUNCT ADJ NOUN DET NOUN PUNCT ADV VERB PRON PRON NOUN ADP PUNCT

First Sentence:

sehr gute beratung , schnelle behebung der probleme , so stelle ich mir kundenservice vor </s>


In [7]:
class LSTMPosTagger(nn.Module):
    def __init__(self,
        embeddings,
        hidden_dim,
        tagset_size):
        super(LSTMPosTagger, self).__init__()
        
        self.hidden_dim = hidden_dim

        self.word_embeddings = nn.Embedding.from_pretrained(embeddings)

        # The LSTM receives the word embedding vector a input and outputs
        # a vector of size int(hidden_dim). 
        self.lstm = nn.LSTM(self.word_embeddings.embedding_dim, self.hidden_dim)

        # A Linear layer that receives the output of the LSTM model with
        # size int(hidden_dim) and outputs a vector of size int(tagset_size) 
        self.hid_to_tag = nn.Linear(hidden_dim, tagset_size)

    def forward(self, sentence):
        '''
        Function to update the model parameters. Necessary for the model
        : param sentence : List of indices corresponding to the vocab in the pre trained embeddings model.
        : type List:'''
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm(embeds.view(len(sentence), 1, -1))
        tag_scores = self.hid_to_tag(lstm_out.view(len(sentence), -1))
        
        return tag_scores

In [8]:
def train_model_comet(model: Module, 
                train_data: DataLoader,
                num_epochs: int,
                optimizer_type,
                loss_function,
                learning_rate: float,
                experiment: Experiment) -> None:
    """
    Function to train a given PyTorch model with given Hyperparameters
    :param model: a pytorch model
    :param train_data: a dataloader for getting the training instances
    :param num_epochs: the number of epochs to train
    :param optimizer_type: the type of optimizer to use for training
    :param loss_function: the type of loss function to use
    :param learning_rate: the learning rate for the optimizer
    :return:
    """
    
    
    print(f'--------- Start Training ------------')

    # Important: bring model into training mode
    model.train()
    
    optimizer = optimizer_type(params=model.parameters(), lr=learning_rate)

    # Setting experiment to Train Mode.
    with experiment.train():
        step=0

        for epoch in tqdm(range(num_epochs), desc='Classifier Training\n'):
            # Cummulative loss per Epoch
            cum_loss = 0
            # Number of correct predictions
            correct = 0
            # Number of total tokens predicted
            total = 0
            
            print(f'---------- Started Epoch {epoch} -----------')

            for batch in tqdm(train_data):
                # get the inputs 
                input_attributes = batch[0][0].to(device)
                # get the corresponding labels
                gold_labels = batch[0][1].to(device)
                
                # compute model predictions with current model parameters
                model_output = model(input_attributes)
    
                # Compute Loss for current batch
                loss = loss_function(model_output, gold_labels)
                cum_loss += loss.item()
                  
                # Zero Gradient
                optimizer.zero_grad()
                loss.backward()
    
                # Update parameters
                optimizer.step()
            
                ##################################################
                # COMET
                # Compute train accuracy
                # Torch.max returns a namedtuple where of (value,indices)
                # where ```values``` is the maximum value of each rou of the
                # input tensor in the given dimension 
                _, predicted = torch.max(model_output.data, 1)

                batch_total = gold_labels.size(0)
                total += batch_total

                batch_correct = (predicted == gold_labels.data).sum()
                correct += batch_correct

                 # Log batch_accuracy to Comet.ml; step is a correction for epoch number
            step+=1
            experiment.log_metric("mean_epoch_accuracy", correct / total, step=step)
                ################################################
                
            mean_loss_per_epoch = cum_loss/len(train_data)
            experiment.log_metric('Mean_loss_per_epoch',mean_loss_per_epoch,step)
            print(mean_loss_per_epoch)

# Training the Models on Development Data 

Code used to define Hyperparameters, train the model and save the model.

**Run this only to train models**

In [ ]:
# Hyper Parameters
HIDDEN_SIZE = 300

NUM_EPOCHS = 10

LEARNING_RATE = 0.005


# Inputs
EMBEDDINGS = pretrained_embeddings

OPTIMIZER = optim.Adam

LOSS_FUNCTION = nn.functional.cross_entropy

EXPERIMENT = Experiment(project_name="LSTM-PosTagger - DevData")

# Logging the Hyper Parameters into Commet
HyperParameters = {'HiddenSize': HIDDEN_SIZE,
                   'NumEpochs': NUM_EPOCHS,
                   'LearningRate': LEARNING_RATE
                  }

EXPERIMENT.log_parameters(HyperParameters)


# Initializing the model
POS_TAGGER = LSTMPosTagger(pretrained_embeddings,HIDDEN_SIZE,len(tagset))

In [ ]:
# Using the Training Function

train_model_comet(POS_TAGGER,
            dev_dataloader,
            NUM_EPOCHS,
            OPTIMIZER,
            LOSS_FUNCTION,
            LEARNING_RATE,
            EXPERIMENT)

In [ ]:
# Saving the model. The path was changed multiple times for different models.
# wich the current settings it should save normally
torch.save(POS_TAGGER.state_dict(),'./models/LSTM_PosTagger_DEV - DevDataX.pt')

# Training the model on Development Data

Three different models were trained with different Learning Rates. 

| Hypterparameters | DevData 1 | DevData 2  | DevData 3 |
|:----------------:|---------|----------|---------|
| Learning Rate    | 0,01    | 0,001    | 0,015   |
| Hidden Size      | 300     | 300      | 300     |
| Number of Epochs | 20      | 20       | 20      |

## Evaluating Dev Models Accuracy on Test Data

Five different models were evaluated. Different Learning Rates and Hidden Sizes were used and the Mean Accuracy per Epoch and Mean Loss per Epoch were logged on Comet. The Hyperparameters are shown right before the 

Data for the models trained on the Dev Data can be found on the following link

[Comet - Dev Data](https://www.comet.ml/lflage/lstm-postagger-devdata/view/new/panels)

In [9]:
def eval_model(Data, Model):
    '''function created to return the accuracy of the models predictions on any given data
    : param Data: Iterable containing the sentences to be predicted
    : type: Dataloader
    : Model: a PyTorch Model'''
    
    Model.eval()

    with torch.no_grad():  
        correct=0
        total=0
           
        test_predictions = None
        test_targets = None
        
        for batch in Data:
            input_attributes = batch[0][0].to(device)
            # get the corresponding labels
            gold_labels = batch[0][1].to(device)
            model_output = Model(input_attributes)
            _, predicted = torch.max(model_output.data, 1)
            
            
            batch_total = gold_labels.size(0)
            total += batch_total
    
            batch_correct = (predicted == gold_labels.data).sum()
            correct += batch_correct
            
    model_accurracy = correct/total        
    print('model accuracy: {:.4f}'.format(model_accurracy))



### Model 1

| Hyperparameters | DevData 1 | 
|:----------------:|---------|
| Learning Rate    | 0,01    |
| Hidden Size      | 300     |
| Number of Epochs | 20      |

<img src='./images/Mean Accuracy per Epoch - DevData 1.svg' width="1000" height="800">

<img src='./images/Mean Loss per Epoch - DevData1.svg' width="1000" height="800">

In [13]:
# Loading the model
path = './models/LSTM_PosTagger_DEV - DevData1.pt'
lstm = LSTMPosTagger(pretrained_embeddings,300,len(tagset))
lstm.load_state_dict(torch.load(path))
lstm.eval()

if os.path.exists(path):
    eval_model(test_dataloader,lstm)
    # Obtained accuracy of: 0.8701

model accuracy: 0.8701


### Model 2

| Hyperparameters  |DevData 2 | 
|:----------------:|----------|
| Learning Rate    | 0,001    | 
| Hidden Size      | 300      | 
| Number of Epochs | 20       | 


<img src='./images/Mean Accuracy per Epoch - DevData2.svg' width="1000" height="800">

<img src='./images/Mean Loss per Epoch - DevData2.svg' width="1000" height="800">

In [14]:
# Loading the model
path = './models/LSTM_PosTagger_DEV - DevData2.pt'
lstm = LSTMPosTagger(pretrained_embeddings,300,len(tagset))
lstm.load_state_dict(torch.load(path))
lstm.eval()

if os.path.exists(path):
    eval_model(test_dataloader,lstm)
    # Obtained accuracy of: 0.8940

model accuracy: 0.8940


### Model 3

| Hyperparameters || DevData 3 |
|:----------------:||---------|
| Learning Rate    || 0,015   |
| Hidden Size      || 300     |
| Number of Epochs || 20      |

<img src='./images/Mean Accuracy per Epoch - DevData3.svg' width="1000" height="800">

<img src='./images/Mean Loss per Epoch - DevData3.svg' width="1000" height="800">

In [16]:
# Loading the model
path = './models/LSTM_PosTagger_DEV - DevData3.pt'
lstm = LSTMPosTagger(pretrained_embeddings,300,len(tagset))
lstm.load_state_dict(torch.load(path))
lstm.eval()

if os.path.exists(path):
    eval_model(test_dataloader,lstm)
    # Obtained accuracy of: 0.8802

model accuracy: 0.8802


## Different Hidden Sizes

Two other models were trained using different Hidden Sizes. The first one using hidden size 150 and the second using Hidden Size 600.

### Model 4 

  
| Hyperparameters  || DevData 4 |
|:----------------:||-----------|
| Learning Rate    ||   0,01    |
| Hidden Size      ||   150     |
| Number of Epochs ||   20      |

<img src='./images/Mean Accuracy per Epoch - DevData4.svg' width="1000" height="800">

<img src='./images/Mean Loss per Epoch - DevData4.svg' width="1000" height="800">

In [17]:
# Loading the model

path = './models/LSTM_PosTagger_DEV - DevData4.pt'
lstm = LSTMPosTagger(pretrained_embeddings,150,len(tagset))
lstm.load_state_dict(torch.load(path))
lstm.eval()

if os.path.exists(path):
    eval_model(test_dataloader,lstm)
    # Obtained accuracy of: 0.8898

model accuracy: 0.8898


### Model 5 

  
| Hyperparameters  || DevData 5 |
|:----------------:||-----------|
| Learning Rate    ||   0,01    |
| Hidden Size      ||   600     |
| Number of Epochs ||   20      |

<img src='./images/Mean Accuracy per Epoch - DevData5.svg' width="1000" height="800">

<img src='./images/Mean Loss per Epoch - DevData5.svg' width="1000" height="800">

In [18]:
# Loading the model
path = './models/LSTM_PosTagger_DEV - DevData5.pt'
lstm = LSTMPosTagger(pretrained_embeddings,600,len(tagset))
lstm.load_state_dict(torch.load(path))
lstm.eval()

if os.path.exists(path):
    eval_model(test_dataloader,lstm)
    # Obtained accuracy of: 0.8772

model accuracy: 0.8772


### Conclusion on HyperParameters

Model 1 gave us a baseline for accuracy performance (0.8701) on the test data and from this performance we can decide which Hyperparameters to use to train our model.  

Models 2 and 3 allowed us to compare the influence of the **Learning Rate** on the models performance. We found an accuracy of 0.8940 for model 2, and 0.8802 for model 3. Although both achieved a higher accuracy than the baseline model, Model2 performance was slightly better on both the test and training data (can be seen on Comet). For this reason a **Learning Rate** of 0.001 was chosen to train the final model.

When comparing models 4 and 5 accuracy on test data, we see the model has a better accuracy (0.8898) with **Hidden Size** 150, achieved on Model 4. Model 5 had a slightly better accuracy (0.8772) than the baseline model, although not as high as Model 4.

The final model was trained using 

# Computing accuracy on a given sentence

The accuracy can only be computed on sentences for which we know the correct POS-Tags. Therefore we check the accuracy of the Development model on the first sentence provided by the development Dataloarder

In [19]:
def compute_accuracy(y_true, y_pred):
    '''
    Function Defined to compute accuracy
    :param y_true: List of the correct values to be checked
    :type y_true: List
    :param y_pred: List of the predicted values
    :type y_pred: List of predicted values
    :return accuracy: Float number between 1 and 0 that represents the accuracy
    '''
    correct_predictions = 0
    # iterate over each label and check
    for true, predicted in zip(y_true, y_pred):
        if true == predicted:
            correct_predictions += 1
    # compute the accuracy
    accuracy = correct_predictions/len(y_true)
    return accuracy


In [22]:
# Loading a model and setting it to evaluation mode

model = LSTMPosTagger(pretrained_embeddings,300,len(tagset))
model.load_state_dict(torch.load('./models/LSTM_PosTagger_DEV - DevData1.pt'))
model.eval()

LSTMPosTagger(
  (word_embeddings): Embedding(50506, 300)
  (lstm): LSTM(300, 300)
  (hid_to_tag): Linear(in_features=300, out_features=18, bias=True)
)

In [23]:
# Access the first sentence of the Dataloader and checks the models accuracy

for batch in dev_dataloader:
    input_attributes = batch[0][0].to(device)
    gold_labels = batch[0][1].to(device)
    
    model_output = model(input_attributes)
    
    _, predicted = torch.max(model_output.data, 1)
    
    print('Tagging Accuracy: {}'.format(compute_accuracy(gold_labels, predicted)))
    
    break

Tagging Accuracy: 1.0


# Train model on training data
 
The model will be trained using the hyperparameters that resulted on the best accuracy for the model trained on the development data. This means we used the Hyperparameters for Model 2

In [46]:
HIDDEN_SIZE = 150

NUM_EPOCHS = 20

LEARNING_RATE = 0.001

# Inputs
EMBEDDINGS = pretrained_embeddings

OPTIMIZER = optim.Adam

LOSS_FUNCTION = nn.functional.cross_entropy

EXPERIMENT = Experiment(project_name="LSTM-PosTagger - Training Data")

COMET INFO: ---------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     url                   : https://www.comet.ml/lflage/lstm-postagger-devdata/94f9becec1864152901864681b5db7e3
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     train_Mean_loss_per_epoch [20] : (0.08815085770042011, 0.6820052868193563)
COMET INFO:     train_mean_epoch_accuracy [20] : 0.9595257
COMET INFO:   Parameters:
COMET INFO:     HiddenSize   : 600
COMET INFO:     LearningRate : 0.01
COMET INFO:     NumEpochs    : 20
COMET INFO:   Uploads:
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (123 KB)
COMET INFO:     installed packages       : 1
COMET INFO:     os packages              : 1
COMET INFO: ---------------------------
COMET INFO: Experiment is liv

In [47]:
# Logging the Hyper Parameters into Commet
HyperParameters = {'HiddenSize': HIDDEN_SIZE,
                   'NumEpochs': NUM_EPOCHS,
                   'LearningRate': LEARNING_RATE
                  }

EXPERIMENT.log_parameters(HyperParameters)

# Initializing the model
POS_TAGGER = LSTMPosTagger(pretrained_embeddings,HIDDEN_SIZE,len(tagset))

In [ ]:
# Using the train function
train_model_comet(POS_TAGGER,
            train_dataloader,
            NUM_EPOCHS,
            OPTIMIZER,
            LOSS_FUNCTION,
            LEARNING_RATE,
            EXPERIMENT)

torch.save(POS_TAGGER.state_dict(),'./LSTM_PosTagger_Train - TrainData3.pt')



Classifier Training
:   0%|          | 0/20 [00:00<?, ?it/s]


  0%|          | 0/13814 [00:00<?, ?it/s]


  0%|          | 1/13814 [00:00<37:48,  6.09it/s]

--------- Start Training ------------
---------- Started Epoch 0 -----------





  0%|          | 2/13814 [00:00<34:42,  6.63it/s]


  0%|          | 4/13814 [00:00<35:12,  6.54it/s]


  0%|          | 5/13814 [00:00<32:22,  7.11it/s]


  0%|          | 6/13814 [00:00<32:20,  7.12it/s]


  0%|          | 7/13814 [00:01<34:09,  6.74it/s]


  0%|          | 8/13814 [00:01<37:41,  6.11it/s]


  0%|          | 9/13814 [00:01<33:27,  6.88it/s]


  0%|          | 11/13814 [00:01<33:17,  6.91it/s]


  0%|          | 12/13814 [00:01<37:30,  6.13it/s]


  0%|          | 14/13814 [00:02<35:33,  6.47it/s]


  0%|          | 15/13814 [00:02<45:41,  5.03it/s]


  0%|          | 16/13814 [00:02<40:47,  5.64it/s]


  0%|          | 18/13814 [00:02<40:17,  5.71it/s]


  0%|          | 20/13814 [00:03<33:03,  6.95it/s]


  0%|          | 21/13814 [00:03<31:05,  7.39it/s]


  0%|          | 22/13814 [00:03<31:13,  7.36it/s]


  0%|          | 24/13814 [00:03<27:26,  8.38it/s]


  0%|          | 25/13814 [00:03<29:51,  7.70it/s]


  0%|          | 26/13814 [00:03<30:19,  7.58it/s]

  4%|▍         | 605/13814 [00:48<21:47, 10.10it/s]


  4%|▍         | 607/13814 [00:49<19:12, 11.46it/s]


  4%|▍         | 609/13814 [00:49<21:57, 10.02it/s]


  4%|▍         | 611/13814 [00:49<20:29, 10.74it/s]


  4%|▍         | 613/13814 [00:49<21:00, 10.47it/s]


  4%|▍         | 615/13814 [00:49<22:36,  9.73it/s]


  4%|▍         | 617/13814 [00:50<21:53, 10.04it/s]


  4%|▍         | 619/13814 [00:50<22:41,  9.69it/s]


  4%|▍         | 621/13814 [00:50<21:14, 10.35it/s]


  5%|▍         | 623/13814 [00:50<21:32, 10.21it/s]


  5%|▍         | 626/13814 [00:50<19:35, 11.22it/s]


  5%|▍         | 628/13814 [00:51<17:03, 12.88it/s]


  5%|▍         | 630/13814 [00:51<16:02, 13.69it/s]


  5%|▍         | 633/13814 [00:51<14:19, 15.33it/s]


  5%|▍         | 636/13814 [00:51<12:56, 16.98it/s]


  5%|▍         | 638/13814 [00:51<17:10, 12.79it/s]


  5%|▍         | 640/13814 [00:51<15:39, 14.02it/s]


  5%|▍         | 642/13814 [00:51<16:20, 13.43it/s]


  5%|▍         | 644/13814 [

  8%|▊         | 1167/13814 [01:38<24:17,  8.68it/s]


  8%|▊         | 1169/13814 [01:39<23:15,  9.06it/s]


  8%|▊         | 1170/13814 [01:39<27:26,  7.68it/s]


  8%|▊         | 1171/13814 [01:39<31:16,  6.74it/s]


  8%|▊         | 1172/13814 [01:39<30:50,  6.83it/s]


  8%|▊         | 1173/13814 [01:39<30:45,  6.85it/s]


  8%|▊         | 1174/13814 [01:39<30:40,  6.87it/s]


  9%|▊         | 1175/13814 [01:40<30:15,  6.96it/s]


  9%|▊         | 1178/13814 [01:40<23:35,  8.93it/s]


  9%|▊         | 1180/13814 [01:40<20:39, 10.19it/s]


  9%|▊         | 1182/13814 [01:40<21:13,  9.92it/s]


  9%|▊         | 1184/13814 [01:40<18:39, 11.28it/s]


  9%|▊         | 1186/13814 [01:40<22:24,  9.39it/s]


  9%|▊         | 1189/13814 [01:41<19:58, 10.53it/s]


  9%|▊         | 1193/13814 [01:41<16:01, 13.12it/s]


  9%|▊         | 1195/13814 [01:41<16:09, 13.02it/s]


  9%|▊         | 1197/13814 [01:41<21:22,  9.84it/s]


  9%|▊         | 1199/13814 [01:41<21:36,  9.73it/s]


  9%|▊    

 12%|█▏        | 1691/13814 [02:30<24:28,  8.26it/s]


 12%|█▏        | 1693/13814 [02:30<26:04,  7.75it/s]


 12%|█▏        | 1694/13814 [02:30<28:50,  7.01it/s]


 12%|█▏        | 1697/13814 [02:30<25:57,  7.78it/s]


 12%|█▏        | 1698/13814 [02:30<30:10,  6.69it/s]


 12%|█▏        | 1699/13814 [02:31<34:27,  5.86it/s]


 12%|█▏        | 1700/13814 [02:31<31:49,  6.34it/s]


 12%|█▏        | 1702/13814 [02:31<26:03,  7.75it/s]


 12%|█▏        | 1704/13814 [02:31<22:32,  8.95it/s]


 12%|█▏        | 1706/13814 [02:31<25:44,  7.84it/s]


 12%|█▏        | 1708/13814 [02:32<23:26,  8.61it/s]


 12%|█▏        | 1710/13814 [02:32<20:34,  9.80it/s]


 12%|█▏        | 1712/13814 [02:32<21:23,  9.43it/s]


 12%|█▏        | 1714/13814 [02:32<29:11,  6.91it/s]


 12%|█▏        | 1715/13814 [02:33<32:05,  6.28it/s]


 12%|█▏        | 1716/13814 [02:33<30:22,  6.64it/s]


 12%|█▏        | 1717/13814 [02:33<29:37,  6.81it/s]


 12%|█▏        | 1719/13814 [02:33<23:47,  8.47it/s]


 12%|█▏   

 16%|█▌        | 2149/13814 [03:24<32:02,  6.07it/s]


 16%|█▌        | 2150/13814 [03:25<33:30,  5.80it/s]


 16%|█▌        | 2151/13814 [03:25<34:09,  5.69it/s]


 16%|█▌        | 2153/13814 [03:25<27:52,  6.97it/s]


 16%|█▌        | 2154/13814 [03:25<31:54,  6.09it/s]


 16%|█▌        | 2156/13814 [03:25<26:37,  7.30it/s]


 16%|█▌        | 2158/13814 [03:25<22:36,  8.59it/s]


 16%|█▌        | 2160/13814 [03:26<26:08,  7.43it/s]


 16%|█▌        | 2161/13814 [03:26<28:55,  6.71it/s]


 16%|█▌        | 2162/13814 [03:26<28:20,  6.85it/s]


 16%|█▌        | 2163/13814 [03:26<26:29,  7.33it/s]


 16%|█▌        | 2164/13814 [03:26<30:38,  6.34it/s]


 16%|█▌        | 2165/13814 [03:26<29:27,  6.59it/s]


 16%|█▌        | 2168/13814 [03:27<22:40,  8.56it/s]


 16%|█▌        | 2170/13814 [03:27<21:39,  8.96it/s]


 16%|█▌        | 2172/13814 [03:27<20:37,  9.41it/s]


 16%|█▌        | 2174/13814 [03:27<21:43,  8.93it/s]


 16%|█▌        | 2176/13814 [03:27<21:18,  9.10it/s]


 16%|█▌   

 19%|█▉        | 2620/13814 [04:18<20:42,  9.01it/s]


 19%|█▉        | 2622/13814 [04:18<20:15,  9.20it/s]


 19%|█▉        | 2624/13814 [04:18<18:59,  9.82it/s]


 19%|█▉        | 2626/13814 [04:19<23:13,  8.03it/s]


 19%|█▉        | 2627/13814 [04:19<24:28,  7.62it/s]


 19%|█▉        | 2628/13814 [04:19<26:16,  7.10it/s]


 19%|█▉        | 2629/13814 [04:19<26:04,  7.15it/s]


 19%|█▉        | 2630/13814 [04:19<27:51,  6.69it/s]


 19%|█▉        | 2631/13814 [04:19<32:19,  5.77it/s]


 19%|█▉        | 2633/13814 [04:20<26:42,  6.98it/s]


 19%|█▉        | 2635/13814 [04:20<22:07,  8.42it/s]


 19%|█▉        | 2637/13814 [04:20<19:02,  9.78it/s]


 19%|█▉        | 2639/13814 [04:20<16:49, 11.07it/s]


 19%|█▉        | 2641/13814 [04:20<19:30,  9.55it/s]


 19%|█▉        | 2643/13814 [04:20<18:09, 10.26it/s]


 19%|█▉        | 2645/13814 [04:21<18:36, 10.00it/s]


 19%|█▉        | 2647/13814 [04:21<19:28,  9.56it/s]


 19%|█▉        | 2650/13814 [04:21<16:45, 11.10it/s]


 19%|█▉   

 22%|██▏       | 3099/13814 [05:11<24:47,  7.21it/s]


 22%|██▏       | 3101/13814 [05:12<24:21,  7.33it/s]


 22%|██▏       | 3103/13814 [05:12<22:53,  7.80it/s]


 22%|██▏       | 3105/13814 [05:12<19:11,  9.30it/s]


 23%|██▎       | 3110/13814 [05:12<14:45, 12.09it/s]


 23%|██▎       | 3113/13814 [05:12<17:02, 10.46it/s]


 23%|██▎       | 3115/13814 [05:13<21:05,  8.46it/s]


 23%|██▎       | 3117/13814 [05:13<18:33,  9.61it/s]


 23%|██▎       | 3119/13814 [05:13<19:43,  9.04it/s]


 23%|██▎       | 3121/13814 [05:14<24:49,  7.18it/s]


 23%|██▎       | 3122/13814 [05:14<24:05,  7.40it/s]


 23%|██▎       | 3123/13814 [05:14<29:46,  5.98it/s]


 23%|██▎       | 3124/13814 [05:14<28:30,  6.25it/s]


 23%|██▎       | 3125/13814 [05:14<29:37,  6.01it/s]


 23%|██▎       | 3127/13814 [05:15<25:39,  6.94it/s]


 23%|██▎       | 3128/13814 [05:15<26:15,  6.78it/s]


 23%|██▎       | 3131/13814 [05:15<20:17,  8.78it/s]


 23%|██▎       | 3133/13814 [05:15<16:55, 10.52it/s]


 23%|██▎  

 26%|██▌       | 3530/13814 [06:05<25:30,  6.72it/s]


 26%|██▌       | 3531/13814 [06:05<25:01,  6.85it/s]


 26%|██▌       | 3532/13814 [06:05<25:07,  6.82it/s]


 26%|██▌       | 3533/13814 [06:05<25:44,  6.66it/s]


 26%|██▌       | 3535/13814 [06:05<20:58,  8.17it/s]


 26%|██▌       | 3536/13814 [06:06<20:07,  8.51it/s]


 26%|██▌       | 3537/13814 [06:06<25:43,  6.66it/s]


 26%|██▌       | 3539/13814 [06:06<21:16,  8.05it/s]


 26%|██▌       | 3541/13814 [06:06<19:48,  8.64it/s]


 26%|██▌       | 3544/13814 [06:06<15:56, 10.74it/s]


 26%|██▌       | 3546/13814 [06:06<15:29, 11.05it/s]


 26%|██▌       | 3548/13814 [06:07<15:43, 10.88it/s]


 26%|██▌       | 3550/13814 [06:07<15:47, 10.83it/s]


 26%|██▌       | 3552/13814 [06:07<15:06, 11.32it/s]


 26%|██▌       | 3554/13814 [06:07<14:05, 12.13it/s]


 26%|██▌       | 3557/13814 [06:07<12:05, 14.13it/s]


 26%|██▌       | 3559/13814 [06:07<13:37, 12.54it/s]


 26%|██▌       | 3561/13814 [06:08<16:26, 10.39it/s]


 26%|██▌  

 29%|██▊       | 3942/13814 [06:57<29:58,  5.49it/s]


 29%|██▊       | 3943/13814 [06:57<35:45,  4.60it/s]


 29%|██▊       | 3944/13814 [06:58<46:35,  3.53it/s]


 29%|██▊       | 3945/13814 [06:58<55:28,  2.97it/s]


 29%|██▊       | 3946/13814 [06:58<47:45,  3.44it/s]


 29%|██▊       | 3947/13814 [06:59<38:26,  4.28it/s]


 29%|██▊       | 3949/13814 [06:59<29:47,  5.52it/s]


 29%|██▊       | 3951/13814 [06:59<24:30,  6.71it/s]


 29%|██▊       | 3953/13814 [06:59<21:14,  7.74it/s]


 29%|██▊       | 3955/13814 [06:59<19:22,  8.48it/s]


 29%|██▊       | 3957/13814 [06:59<19:30,  8.42it/s]


 29%|██▊       | 3959/13814 [07:00<17:16,  9.51it/s]


 29%|██▊       | 3961/13814 [07:00<18:32,  8.86it/s]


 29%|██▊       | 3964/13814 [07:00<17:22,  9.45it/s]


 29%|██▊       | 3966/13814 [07:00<19:12,  8.54it/s]


 29%|██▊       | 3967/13814 [07:01<24:11,  6.78it/s]


 29%|██▊       | 3968/13814 [07:01<25:54,  6.34it/s]


 29%|██▊       | 3969/13814 [07:01<23:13,  7.07it/s]


 29%|██▊  

 32%|███▏      | 4419/13814 [07:53<14:07, 11.09it/s]


 32%|███▏      | 4421/13814 [07:53<13:46, 11.37it/s]


 32%|███▏      | 4423/13814 [07:53<12:43, 12.31it/s]


 32%|███▏      | 4425/13814 [07:53<17:15,  9.07it/s]


 32%|███▏      | 4427/13814 [07:53<17:15,  9.06it/s]


 32%|███▏      | 4429/13814 [07:54<17:07,  9.13it/s]


 32%|███▏      | 4431/13814 [07:54<23:06,  6.77it/s]


 32%|███▏      | 4432/13814 [07:54<23:16,  6.72it/s]


 32%|███▏      | 4433/13814 [07:54<21:19,  7.33it/s]


 32%|███▏      | 4435/13814 [07:54<17:35,  8.88it/s]


 32%|███▏      | 4437/13814 [07:55<22:12,  7.04it/s]


 32%|███▏      | 4438/13814 [07:55<21:13,  7.36it/s]


 32%|███▏      | 4440/13814 [07:55<18:46,  8.32it/s]


 32%|███▏      | 4442/13814 [07:55<15:40,  9.97it/s]


 32%|███▏      | 4444/13814 [07:56<17:27,  8.94it/s]


 32%|███▏      | 4446/13814 [07:56<20:45,  7.52it/s]


 32%|███▏      | 4447/13814 [07:56<19:40,  7.94it/s]


 32%|███▏      | 4448/13814 [07:56<28:47,  5.42it/s]


 32%|███▏ 

 35%|███▌      | 4859/13814 [08:45<20:15,  7.37it/s]


 35%|███▌      | 4863/13814 [08:45<15:35,  9.57it/s]


 35%|███▌      | 4866/13814 [08:45<12:31, 11.91it/s]


 35%|███▌      | 4868/13814 [08:45<11:28, 12.99it/s]


 35%|███▌      | 4870/13814 [08:45<10:19, 14.43it/s]


 35%|███▌      | 4872/13814 [08:45<13:40, 10.90it/s]


 35%|███▌      | 4874/13814 [08:46<13:51, 10.75it/s]


 35%|███▌      | 4876/13814 [08:46<13:07, 11.35it/s]


 35%|███▌      | 4878/13814 [08:46<12:18, 12.09it/s]


 35%|███▌      | 4880/13814 [08:46<12:41, 11.74it/s]


 35%|███▌      | 4882/13814 [08:46<16:30,  9.02it/s]


 35%|███▌      | 4884/13814 [08:47<14:37, 10.18it/s]


 35%|███▌      | 4886/13814 [08:47<14:13, 10.47it/s]


 35%|███▌      | 4888/13814 [08:47<14:50, 10.02it/s]


 35%|███▌      | 4891/13814 [08:47<12:54, 11.52it/s]


 35%|███▌      | 4893/13814 [08:47<15:04,  9.87it/s]


 35%|███▌      | 4895/13814 [08:47<13:31, 10.99it/s]


 35%|███▌      | 4897/13814 [08:48<12:22, 12.01it/s]


 35%|███▌ 

 38%|███▊      | 5304/13814 [09:38<31:41,  4.47it/s]


 38%|███▊      | 5305/13814 [09:38<29:28,  4.81it/s]


 38%|███▊      | 5307/13814 [09:39<24:53,  5.70it/s]


 38%|███▊      | 5308/13814 [09:39<37:42,  3.76it/s]


 38%|███▊      | 5309/13814 [09:39<30:41,  4.62it/s]


 38%|███▊      | 5310/13814 [09:39<25:48,  5.49it/s]


 38%|███▊      | 5311/13814 [09:39<23:38,  5.99it/s]


 38%|███▊      | 5312/13814 [09:40<21:19,  6.64it/s]


 38%|███▊      | 5313/13814 [09:40<24:15,  5.84it/s]


 38%|███▊      | 5315/13814 [09:40<22:03,  6.42it/s]


 38%|███▊      | 5317/13814 [09:40<18:25,  7.68it/s]


 39%|███▊      | 5319/13814 [09:40<15:20,  9.23it/s]


 39%|███▊      | 5321/13814 [09:41<15:04,  9.39it/s]


 39%|███▊      | 5324/13814 [09:41<13:45, 10.28it/s]


 39%|███▊      | 5326/13814 [09:41<13:23, 10.57it/s]


 39%|███▊      | 5328/13814 [09:41<13:37, 10.38it/s]


 39%|███▊      | 5330/13814 [09:41<13:14, 10.68it/s]


 39%|███▊      | 5332/13814 [09:42<16:53,  8.37it/s]


 39%|███▊ 

 41%|████▏     | 5719/13814 [10:30<14:03,  9.60it/s]


 41%|████▏     | 5721/13814 [10:30<11:56, 11.30it/s]


 41%|████▏     | 5723/13814 [10:30<11:36, 11.61it/s]


 41%|████▏     | 5725/13814 [10:31<10:56, 12.32it/s]


 41%|████▏     | 5727/13814 [10:31<10:32, 12.78it/s]


 41%|████▏     | 5730/13814 [10:31<09:02, 14.91it/s]


 41%|████▏     | 5732/13814 [10:31<09:10, 14.69it/s]


 42%|████▏     | 5734/13814 [10:31<10:09, 13.26it/s]


 42%|████▏     | 5736/13814 [10:32<14:18,  9.41it/s]


 42%|████▏     | 5738/13814 [10:32<18:03,  7.45it/s]


 42%|████▏     | 5740/13814 [10:32<18:35,  7.24it/s]


 42%|████▏     | 5741/13814 [10:32<21:36,  6.23it/s]


 42%|████▏     | 5742/13814 [10:33<22:21,  6.02it/s]


 42%|████▏     | 5744/13814 [10:33<18:59,  7.08it/s]


 42%|████▏     | 5746/13814 [10:33<16:11,  8.30it/s]


 42%|████▏     | 5748/13814 [10:33<14:37,  9.19it/s]


 42%|████▏     | 5750/13814 [10:33<13:42,  9.80it/s]


 42%|████▏     | 5752/13814 [10:33<13:20, 10.08it/s]


 42%|████▏

 44%|████▍     | 6128/13814 [11:21<28:15,  4.53it/s]


 44%|████▍     | 6129/13814 [11:21<27:14,  4.70it/s]


 44%|████▍     | 6131/13814 [11:22<23:29,  5.45it/s]


 44%|████▍     | 6132/13814 [11:22<25:30,  5.02it/s]


 44%|████▍     | 6134/13814 [11:22<20:26,  6.26it/s]


 44%|████▍     | 6135/13814 [11:22<22:26,  5.70it/s]


 44%|████▍     | 6136/13814 [11:22<21:41,  5.90it/s]


 44%|████▍     | 6137/13814 [11:23<22:49,  5.61it/s]


 44%|████▍     | 6138/13814 [11:23<24:30,  5.22it/s]


 44%|████▍     | 6139/13814 [11:23<21:32,  5.94it/s]


 44%|████▍     | 6140/13814 [11:23<21:23,  5.98it/s]


 44%|████▍     | 6141/13814 [11:23<20:25,  6.26it/s]


 44%|████▍     | 6142/13814 [11:23<22:48,  5.60it/s]


 44%|████▍     | 6143/13814 [11:24<20:59,  6.09it/s]


 44%|████▍     | 6144/13814 [11:24<20:35,  6.21it/s]


 44%|████▍     | 6145/13814 [11:24<23:08,  5.52it/s]


 44%|████▍     | 6146/13814 [11:24<24:58,  5.12it/s]


 44%|████▍     | 6147/13814 [11:24<24:53,  5.13it/s]


 45%|████▍

 47%|████▋     | 6551/13814 [12:13<12:10,  9.94it/s]


 47%|████▋     | 6553/13814 [12:13<12:24,  9.75it/s]


 47%|████▋     | 6555/13814 [12:13<10:31, 11.49it/s]


 47%|████▋     | 6558/13814 [12:13<09:12, 13.14it/s]


 47%|████▋     | 6560/13814 [12:14<09:48, 12.33it/s]


 48%|████▊     | 6562/13814 [12:14<10:16, 11.76it/s]


 48%|████▊     | 6564/13814 [12:14<16:50,  7.17it/s]


 48%|████▊     | 6566/13814 [12:15<18:14,  6.62it/s]


 48%|████▊     | 6568/13814 [12:15<15:03,  8.02it/s]


 48%|████▊     | 6570/13814 [12:15<16:17,  7.41it/s]


 48%|████▊     | 6571/13814 [12:15<15:51,  7.61it/s]


 48%|████▊     | 6573/13814 [12:15<13:03,  9.24it/s]


 48%|████▊     | 6575/13814 [12:16<12:24,  9.72it/s]


 48%|████▊     | 6577/13814 [12:16<12:03, 10.00it/s]


 48%|████▊     | 6579/13814 [12:16<11:01, 10.94it/s]


 48%|████▊     | 6581/13814 [12:16<12:38,  9.54it/s]


 48%|████▊     | 6583/13814 [12:16<11:50, 10.18it/s]


 48%|████▊     | 6585/13814 [12:17<15:59,  7.54it/s]


 48%|████▊

 51%|█████     | 7021/13814 [13:07<08:57, 12.65it/s]


 51%|█████     | 7023/13814 [13:07<08:00, 14.15it/s]


 51%|█████     | 7025/13814 [13:07<08:43, 12.97it/s]


 51%|█████     | 7027/13814 [13:08<09:01, 12.54it/s]


 51%|█████     | 7029/13814 [13:08<10:28, 10.79it/s]


 51%|█████     | 7031/13814 [13:08<09:09, 12.35it/s]


 51%|█████     | 7033/13814 [13:08<15:16,  7.40it/s]


 51%|█████     | 7035/13814 [13:09<15:03,  7.50it/s]


 51%|█████     | 7037/13814 [13:09<16:29,  6.85it/s]


 51%|█████     | 7040/13814 [13:09<12:51,  8.78it/s]


 51%|█████     | 7042/13814 [13:09<11:49,  9.55it/s]


 51%|█████     | 7044/13814 [13:10<12:36,  8.94it/s]


 51%|█████     | 7046/13814 [13:10<12:05,  9.33it/s]


 51%|█████     | 7048/13814 [13:10<10:18, 10.93it/s]


 51%|█████     | 7050/13814 [13:10<09:52, 11.42it/s]


 51%|█████     | 7052/13814 [13:10<09:32, 11.81it/s]


 51%|█████     | 7054/13814 [13:11<12:03,  9.34it/s]


 51%|█████     | 7057/13814 [13:11<10:54, 10.33it/s]


 51%|█████

 54%|█████▍    | 7512/13814 [14:02<15:14,  6.89it/s]


 54%|█████▍    | 7513/13814 [14:02<16:28,  6.38it/s]


 54%|█████▍    | 7515/13814 [14:02<14:00,  7.50it/s]


 54%|█████▍    | 7517/13814 [14:02<11:32,  9.09it/s]


 54%|█████▍    | 7519/13814 [14:02<10:04, 10.42it/s]


 54%|█████▍    | 7521/13814 [14:03<10:27, 10.03it/s]


 54%|█████▍    | 7523/13814 [14:03<12:43,  8.24it/s]


 54%|█████▍    | 7524/13814 [14:03<14:41,  7.14it/s]


 54%|█████▍    | 7525/13814 [14:03<17:11,  6.10it/s]


 54%|█████▍    | 7526/13814 [14:04<16:16,  6.44it/s]


 54%|█████▍    | 7527/13814 [14:04<17:34,  5.96it/s]


 54%|█████▍    | 7528/13814 [14:04<19:18,  5.43it/s]


 55%|█████▍    | 7529/13814 [14:04<17:09,  6.11it/s]


 55%|█████▍    | 7530/13814 [14:04<17:45,  5.90it/s]


 55%|█████▍    | 7531/13814 [14:04<16:11,  6.47it/s]


 55%|█████▍    | 7534/13814 [14:05<13:21,  7.83it/s]


 55%|█████▍    | 7536/13814 [14:05<11:27,  9.13it/s]


 55%|█████▍    | 7538/13814 [14:05<09:53, 10.58it/s]


 55%|█████

 58%|█████▊    | 7966/13814 [14:56<13:49,  7.05it/s]


 58%|█████▊    | 7967/13814 [14:56<13:34,  7.18it/s]


 58%|█████▊    | 7970/13814 [14:56<11:10,  8.72it/s]


 58%|█████▊    | 7972/13814 [14:56<09:29, 10.26it/s]


 58%|█████▊    | 7975/13814 [14:56<08:25, 11.54it/s]


 58%|█████▊    | 7977/13814 [14:57<08:20, 11.66it/s]


 58%|█████▊    | 7979/13814 [14:57<07:31, 12.93it/s]


 58%|█████▊    | 7981/13814 [14:57<09:47,  9.92it/s]


 58%|█████▊    | 7983/13814 [14:57<11:01,  8.82it/s]


 58%|█████▊    | 7985/13814 [14:57<10:05,  9.62it/s]


 58%|█████▊    | 7987/13814 [14:58<08:52, 10.95it/s]


 58%|█████▊    | 7989/13814 [14:58<09:39, 10.06it/s]


 58%|█████▊    | 7991/13814 [14:58<10:23,  9.33it/s]


 58%|█████▊    | 7993/13814 [14:58<10:00,  9.69it/s]


 58%|█████▊    | 7995/13814 [14:58<08:38, 11.21it/s]


 58%|█████▊    | 7997/13814 [14:59<10:29,  9.24it/s]


 58%|█████▊    | 7999/13814 [14:59<14:20,  6.76it/s]


 58%|█████▊    | 8000/13814 [14:59<13:42,  7.07it/s]


 58%|█████

 61%|██████    | 8437/13814 [15:50<08:45, 10.24it/s]


 61%|██████    | 8439/13814 [15:51<08:08, 11.01it/s]


 61%|██████    | 8441/13814 [15:51<08:44, 10.24it/s]


 61%|██████    | 8443/13814 [15:51<11:53,  7.53it/s]


 61%|██████    | 8445/13814 [15:51<09:50,  9.09it/s]


 61%|██████    | 8447/13814 [15:52<10:30,  8.51it/s]


 61%|██████    | 8449/13814 [15:52<14:51,  6.02it/s]


 61%|██████    | 8450/13814 [15:52<14:16,  6.26it/s]


 61%|██████    | 8452/13814 [15:53<14:12,  6.29it/s]


 61%|██████    | 8454/13814 [15:53<11:55,  7.49it/s]


 61%|██████    | 8457/13814 [15:53<10:13,  8.73it/s]


 61%|██████    | 8459/13814 [15:53<12:58,  6.88it/s]


 61%|██████    | 8460/13814 [15:54<12:28,  7.16it/s]


 61%|██████    | 8461/13814 [15:54<11:36,  7.69it/s]


 61%|██████▏   | 8462/13814 [15:54<10:49,  8.24it/s]


 61%|██████▏   | 8464/13814 [15:54<09:56,  8.97it/s]


 61%|██████▏   | 8465/13814 [15:54<14:16,  6.24it/s]


 61%|██████▏   | 8466/13814 [15:54<14:46,  6.03it/s]


 61%|█████

 64%|██████▍   | 8865/13814 [16:41<07:48, 10.57it/s]


 64%|██████▍   | 8867/13814 [16:42<07:51, 10.49it/s]


 64%|██████▍   | 8869/13814 [16:42<07:36, 10.84it/s]


 64%|██████▍   | 8871/13814 [16:42<07:20, 11.22it/s]


 64%|██████▍   | 8873/13814 [16:42<08:26,  9.76it/s]


 64%|██████▍   | 8875/13814 [16:42<07:11, 11.44it/s]


 64%|██████▍   | 8877/13814 [16:42<06:48, 12.08it/s]


 64%|██████▍   | 8879/13814 [16:43<06:13, 13.20it/s]


 64%|██████▍   | 8881/13814 [16:43<07:20, 11.19it/s]


 64%|██████▍   | 8883/13814 [16:43<08:08, 10.10it/s]


 64%|██████▍   | 8885/13814 [16:43<08:34,  9.57it/s]


 64%|██████▍   | 8887/13814 [16:43<08:44,  9.39it/s]


 64%|██████▍   | 8889/13814 [16:44<07:46, 10.57it/s]


 64%|██████▍   | 8891/13814 [16:44<06:40, 12.30it/s]


 64%|██████▍   | 8893/13814 [16:44<08:48,  9.31it/s]


 64%|██████▍   | 8895/13814 [16:44<08:00, 10.24it/s]


 64%|██████▍   | 8897/13814 [16:45<11:48,  6.94it/s]


 64%|██████▍   | 8898/13814 [16:45<11:18,  7.25it/s]


 64%|█████

 67%|██████▋   | 9308/13814 [17:37<14:53,  5.04it/s]


 67%|██████▋   | 9309/13814 [17:37<14:08,  5.31it/s]


 67%|██████▋   | 9310/13814 [17:37<20:46,  3.61it/s]


 67%|██████▋   | 9312/13814 [17:38<18:29,  4.06it/s]


 67%|██████▋   | 9313/13814 [17:38<16:01,  4.68it/s]


 67%|██████▋   | 9315/13814 [17:38<12:30,  5.99it/s]


 67%|██████▋   | 9316/13814 [17:38<11:44,  6.38it/s]


 67%|██████▋   | 9317/13814 [17:38<13:32,  5.54it/s]


 67%|██████▋   | 9318/13814 [17:38<12:41,  5.90it/s]


 67%|██████▋   | 9320/13814 [17:38<10:04,  7.43it/s]


 67%|██████▋   | 9322/13814 [17:39<09:26,  7.93it/s]


 67%|██████▋   | 9324/13814 [17:39<09:39,  7.75it/s]


 68%|██████▊   | 9325/13814 [17:39<11:25,  6.55it/s]


 68%|██████▊   | 9326/13814 [17:39<10:33,  7.09it/s]


 68%|██████▊   | 9328/13814 [17:40<10:16,  7.27it/s]


 68%|██████▊   | 9329/13814 [17:40<11:51,  6.30it/s]


 68%|██████▊   | 9330/13814 [17:40<13:33,  5.51it/s]


 68%|██████▊   | 9332/13814 [17:40<11:30,  6.49it/s]


 68%|█████

 71%|███████   | 9757/13814 [18:29<08:40,  7.79it/s]


 71%|███████   | 9758/13814 [18:29<08:35,  7.87it/s]


 71%|███████   | 9760/13814 [18:30<07:03,  9.57it/s]


 71%|███████   | 9762/13814 [18:30<06:09, 10.98it/s]


 71%|███████   | 9764/13814 [18:30<05:33, 12.13it/s]


 71%|███████   | 9766/13814 [18:30<06:53,  9.78it/s]


 71%|███████   | 9769/13814 [18:30<07:29,  9.01it/s]


 71%|███████   | 9771/13814 [18:31<06:58,  9.66it/s]


 71%|███████   | 9773/13814 [18:31<08:07,  8.28it/s]


 71%|███████   | 9775/13814 [18:31<07:23,  9.11it/s]


 71%|███████   | 9777/13814 [18:31<07:26,  9.05it/s]


 71%|███████   | 9779/13814 [18:32<07:43,  8.70it/s]


 71%|███████   | 9780/13814 [18:32<07:26,  9.03it/s]


 71%|███████   | 9781/13814 [18:32<07:40,  8.76it/s]


 71%|███████   | 9783/13814 [18:32<09:18,  7.21it/s]


 71%|███████   | 9784/13814 [18:32<09:30,  7.07it/s]


 71%|███████   | 9785/13814 [18:33<11:26,  5.87it/s]


 71%|███████   | 9786/13814 [18:33<10:04,  6.67it/s]


 71%|█████

 74%|███████▍  | 10196/13814 [19:21<09:06,  6.62it/s]


 74%|███████▍  | 10198/13814 [19:21<07:41,  7.83it/s]


 74%|███████▍  | 10200/13814 [19:21<06:29,  9.27it/s]


 74%|███████▍  | 10202/13814 [19:21<05:32, 10.86it/s]


 74%|███████▍  | 10204/13814 [19:21<05:42, 10.53it/s]


 74%|███████▍  | 10206/13814 [19:21<05:28, 10.97it/s]


 74%|███████▍  | 10208/13814 [19:22<04:47, 12.54it/s]


 74%|███████▍  | 10211/13814 [19:22<04:07, 14.54it/s]


 74%|███████▍  | 10213/13814 [19:22<05:46, 10.40it/s]


 74%|███████▍  | 10215/13814 [19:22<06:13,  9.63it/s]


 74%|███████▍  | 10217/13814 [19:22<05:33, 10.80it/s]


 74%|███████▍  | 10219/13814 [19:23<05:15, 11.38it/s]


 74%|███████▍  | 10222/13814 [19:23<04:56, 12.10it/s]


 74%|███████▍  | 10224/13814 [19:23<04:46, 12.53it/s]


 74%|███████▍  | 10226/13814 [19:23<05:20, 11.19it/s]


 74%|███████▍  | 10228/13814 [19:24<08:01,  7.45it/s]


 74%|███████▍  | 10230/13814 [19:24<06:59,  8.55it/s]


 74%|███████▍  | 10232/13814 [19:24<05:57, 10.01

 77%|███████▋  | 10632/13814 [20:15<05:38,  9.41it/s]


 77%|███████▋  | 10634/13814 [20:15<05:14, 10.10it/s]


 77%|███████▋  | 10636/13814 [20:16<04:41, 11.28it/s]


 77%|███████▋  | 10638/13814 [20:16<04:51, 10.91it/s]


 77%|███████▋  | 10640/13814 [20:16<07:24,  7.15it/s]


 77%|███████▋  | 10641/13814 [20:16<07:04,  7.48it/s]


 77%|███████▋  | 10644/13814 [20:17<05:59,  8.83it/s]


 77%|███████▋  | 10646/13814 [20:17<07:27,  7.08it/s]


 77%|███████▋  | 10648/13814 [20:17<06:52,  7.67it/s]


 77%|███████▋  | 10649/13814 [20:17<06:30,  8.10it/s]


 77%|███████▋  | 10650/13814 [20:18<10:44,  4.91it/s]


 77%|███████▋  | 10651/13814 [20:18<10:40,  4.94it/s]


 77%|███████▋  | 10653/13814 [20:18<09:20,  5.64it/s]


 77%|███████▋  | 10654/13814 [20:18<10:07,  5.20it/s]


 77%|███████▋  | 10655/13814 [20:18<09:14,  5.70it/s]


 77%|███████▋  | 10656/13814 [20:19<11:10,  4.71it/s]


 77%|███████▋  | 10659/13814 [20:19<09:06,  5.77it/s]


 77%|███████▋  | 10661/13814 [20:19<08:32,  6.16

 80%|████████  | 11092/13814 [21:10<06:11,  7.34it/s]


 80%|████████  | 11093/13814 [21:10<06:43,  6.74it/s]


 80%|████████  | 11094/13814 [21:10<06:42,  6.76it/s]


 80%|████████  | 11095/13814 [21:10<06:44,  6.72it/s]


 80%|████████  | 11097/13814 [21:11<05:50,  7.74it/s]


 80%|████████  | 11098/13814 [21:11<05:50,  7.74it/s]


 80%|████████  | 11100/13814 [21:11<05:00,  9.03it/s]


 80%|████████  | 11102/13814 [21:11<04:26, 10.18it/s]


 80%|████████  | 11104/13814 [21:11<03:53, 11.61it/s]


 80%|████████  | 11106/13814 [21:11<04:13, 10.67it/s]


 80%|████████  | 11108/13814 [21:11<03:49, 11.79it/s]


 80%|████████  | 11110/13814 [21:12<04:02, 11.17it/s]


 80%|████████  | 11112/13814 [21:12<03:37, 12.44it/s]


 80%|████████  | 11115/13814 [21:12<03:36, 12.49it/s]


 80%|████████  | 11117/13814 [21:12<03:50, 11.68it/s]


 80%|████████  | 11120/13814 [21:12<03:15, 13.77it/s]


 81%|████████  | 11122/13814 [21:13<03:45, 11.96it/s]


 81%|████████  | 11124/13814 [21:13<06:12,  7.23

 84%|████████▎ | 11568/13814 [22:01<05:31,  6.78it/s]


 84%|████████▎ | 11569/13814 [22:01<05:19,  7.03it/s]


 84%|████████▍ | 11570/13814 [22:01<06:00,  6.22it/s]


 84%|████████▍ | 11571/13814 [22:01<06:15,  5.97it/s]


 84%|████████▍ | 11573/13814 [22:01<05:07,  7.28it/s]


 84%|████████▍ | 11575/13814 [22:02<04:41,  7.96it/s]


 84%|████████▍ | 11576/13814 [22:02<05:05,  7.32it/s]


 84%|████████▍ | 11577/13814 [22:02<07:41,  4.85it/s]


 84%|████████▍ | 11578/13814 [22:02<08:40,  4.29it/s]


 84%|████████▍ | 11579/13814 [22:03<08:06,  4.60it/s]


 84%|████████▍ | 11581/13814 [22:03<07:06,  5.23it/s]


 84%|████████▍ | 11582/13814 [22:03<06:25,  5.79it/s]


 84%|████████▍ | 11584/13814 [22:03<05:03,  7.35it/s]


 84%|████████▍ | 11586/13814 [22:04<06:19,  5.87it/s]


 84%|████████▍ | 11587/13814 [22:04<06:47,  5.46it/s]


 84%|████████▍ | 11590/13814 [22:04<05:19,  6.96it/s]


 84%|████████▍ | 11592/13814 [22:04<04:34,  8.11it/s]


 84%|████████▍ | 11594/13814 [22:04<03:55,  9.44

 87%|████████▋ | 11993/13814 [22:56<06:33,  4.62it/s]


 87%|████████▋ | 11994/13814 [22:57<06:15,  4.85it/s]


 87%|████████▋ | 11995/13814 [22:57<05:31,  5.49it/s]


 87%|████████▋ | 11996/13814 [22:57<04:47,  6.33it/s]


 87%|████████▋ | 11997/13814 [22:57<05:29,  5.51it/s]


 87%|████████▋ | 11999/13814 [22:57<04:29,  6.73it/s]


 87%|████████▋ | 12000/13814 [22:57<04:14,  7.14it/s]


 87%|████████▋ | 12002/13814 [22:58<04:07,  7.32it/s]


 87%|████████▋ | 12003/13814 [22:58<04:28,  6.75it/s]


 87%|████████▋ | 12005/13814 [22:58<03:44,  8.06it/s]


 87%|████████▋ | 12007/13814 [22:58<04:42,  6.41it/s]


 87%|████████▋ | 12008/13814 [22:59<05:27,  5.51it/s]


 87%|████████▋ | 12009/13814 [22:59<05:25,  5.54it/s]


 87%|████████▋ | 12010/13814 [22:59<05:01,  5.97it/s]


 87%|████████▋ | 12012/13814 [22:59<04:01,  7.47it/s]


 87%|████████▋ | 12014/13814 [23:00<05:04,  5.90it/s]


 87%|████████▋ | 12015/13814 [23:00<08:56,  3.35it/s]


 87%|████████▋ | 12017/13814 [23:00<06:58,  4.30

 90%|████████▉ | 12421/13814 [23:49<03:19,  6.98it/s]


 90%|████████▉ | 12424/13814 [23:49<02:39,  8.71it/s]


 90%|████████▉ | 12426/13814 [23:50<02:20,  9.88it/s]


 90%|████████▉ | 12428/13814 [23:50<02:46,  8.31it/s]


 90%|████████▉ | 12430/13814 [23:50<02:37,  8.78it/s]


 90%|████████▉ | 12432/13814 [23:50<02:26,  9.41it/s]


 90%|█████████ | 12434/13814 [23:50<02:29,  9.26it/s]


 90%|█████████ | 12436/13814 [23:51<02:13, 10.33it/s]


 90%|█████████ | 12438/13814 [23:51<02:34,  8.92it/s]


 90%|█████████ | 12440/13814 [23:51<02:24,  9.53it/s]


 90%|█████████ | 12443/13814 [23:51<01:55, 11.83it/s]


 90%|█████████ | 12445/13814 [23:51<01:53, 12.11it/s]


 90%|█████████ | 12447/13814 [23:52<02:22,  9.60it/s]


 90%|█████████ | 12449/13814 [23:52<03:10,  7.18it/s]


 90%|█████████ | 12450/13814 [23:52<03:24,  6.66it/s]


 90%|█████████ | 12451/13814 [23:53<05:34,  4.07it/s]


 90%|█████████ | 12452/13814 [23:53<04:39,  4.87it/s]


 90%|█████████ | 12453/13814 [23:53<04:27,  5.09

 93%|█████████▎| 12871/13814 [24:43<03:22,  4.67it/s]


 93%|█████████▎| 12872/13814 [24:43<03:15,  4.82it/s]


 93%|█████████▎| 12874/13814 [24:44<03:13,  4.85it/s]


 93%|█████████▎| 12876/13814 [24:44<03:25,  4.57it/s]


 93%|█████████▎| 12877/13814 [24:45<03:01,  5.16it/s]


 93%|█████████▎| 12878/13814 [24:45<03:00,  5.19it/s]


 93%|█████████▎| 12880/13814 [24:45<02:22,  6.57it/s]


 93%|█████████▎| 12882/13814 [24:45<02:03,  7.57it/s]


 93%|█████████▎| 12883/13814 [24:45<02:00,  7.71it/s]


 93%|█████████▎| 12884/13814 [24:45<02:21,  6.57it/s]


 93%|█████████▎| 12887/13814 [24:46<01:57,  7.92it/s]


 93%|█████████▎| 12889/13814 [24:46<02:47,  5.51it/s]


 93%|█████████▎| 12892/13814 [24:46<02:16,  6.76it/s]


 93%|█████████▎| 12894/13814 [24:47<02:09,  7.13it/s]


 93%|█████████▎| 12896/13814 [24:47<01:51,  8.20it/s]


 93%|█████████▎| 12898/13814 [24:47<01:49,  8.34it/s]


 93%|█████████▎| 12900/13814 [24:47<01:53,  8.04it/s]


 93%|█████████▎| 12901/13814 [24:48<02:38,  5.78

 97%|█████████▋| 13372/13814 [25:34<01:05,  6.70it/s]


 97%|█████████▋| 13374/13814 [25:34<01:03,  6.95it/s]


 97%|█████████▋| 13376/13814 [25:34<00:51,  8.52it/s]


 97%|█████████▋| 13378/13814 [25:35<00:45,  9.65it/s]


 97%|█████████▋| 13380/13814 [25:35<00:42, 10.20it/s]


 97%|█████████▋| 13382/13814 [25:35<00:41, 10.53it/s]


 97%|█████████▋| 13384/13814 [25:35<00:43,  9.97it/s]


 97%|█████████▋| 13386/13814 [25:35<00:38, 11.02it/s]


 97%|█████████▋| 13388/13814 [25:36<00:41, 10.20it/s]


 97%|█████████▋| 13390/13814 [25:36<01:03,  6.67it/s]


 97%|█████████▋| 13391/13814 [25:36<00:58,  7.26it/s]


 97%|█████████▋| 13393/13814 [25:36<00:50,  8.27it/s]


 97%|█████████▋| 13395/13814 [25:37<00:45,  9.17it/s]


 97%|█████████▋| 13397/13814 [25:37<00:38, 10.78it/s]


 97%|█████████▋| 13399/13814 [25:37<00:34, 12.15it/s]


 97%|█████████▋| 13401/13814 [25:37<00:47,  8.69it/s]


 97%|█████████▋| 13403/13814 [25:37<00:55,  7.47it/s]


 97%|█████████▋| 13406/13814 [25:38<00:45,  9.06

100%|█████████▉| 13767/13814 [26:24<00:05,  8.20it/s]


100%|█████████▉| 13769/13814 [26:24<00:05,  8.29it/s]


100%|█████████▉| 13771/13814 [26:24<00:04,  9.57it/s]


100%|█████████▉| 13773/13814 [26:25<00:04,  8.60it/s]


100%|█████████▉| 13775/13814 [26:25<00:04,  9.52it/s]


100%|█████████▉| 13777/13814 [26:25<00:03, 10.52it/s]


100%|█████████▉| 13779/13814 [26:25<00:03,  9.76it/s]


100%|█████████▉| 13781/13814 [26:26<00:03,  9.64it/s]


100%|█████████▉| 13783/13814 [26:26<00:03,  9.42it/s]


100%|█████████▉| 13784/13814 [26:26<00:07,  4.10it/s]


100%|█████████▉| 13785/13814 [26:27<00:07,  4.05it/s]


100%|█████████▉| 13786/13814 [26:27<00:07,  3.93it/s]


100%|█████████▉| 13787/13814 [26:27<00:06,  4.39it/s]


100%|█████████▉| 13790/13814 [26:27<00:04,  5.46it/s]


100%|█████████▉| 13792/13814 [26:27<00:03,  6.86it/s]


100%|█████████▉| 13796/13814 [26:27<00:02,  8.82it/s]


100%|█████████▉| 13798/13814 [26:28<00:02,  7.30it/s]


100%|█████████▉| 13800/13814 [26:28<00:01,  7.19

0.2878868185124366
---------- Started Epoch 1 -----------





  0%|          | 1/13814 [00:00<48:46,  4.72it/s]


  0%|          | 2/13814 [00:00<42:09,  5.46it/s]


  0%|          | 4/13814 [00:00<33:27,  6.88it/s]


  0%|          | 6/13814 [00:00<36:11,  6.36it/s]


  0%|          | 7/13814 [00:01<41:13,  5.58it/s]


  0%|          | 8/13814 [00:01<40:21,  5.70it/s]


  0%|          | 9/13814 [00:01<43:53,  5.24it/s]


  0%|          | 10/13814 [00:01<53:01,  4.34it/s]


  0%|          | 11/13814 [00:01<48:12,  4.77it/s]


  0%|          | 12/13814 [00:02<42:18,  5.44it/s]


  0%|          | 14/13814 [00:02<35:32,  6.47it/s]


  0%|          | 15/13814 [00:02<34:44,  6.62it/s]


  0%|          | 16/13814 [00:02<43:01,  5.34it/s]


  0%|          | 17/13814 [00:02<39:05,  5.88it/s]


  0%|          | 18/13814 [00:02<38:17,  6.01it/s]


  0%|          | 19/13814 [00:03<47:36,  4.83it/s]


  0%|          | 21/13814 [00:03<38:32,  5.96it/s]


  0%|          | 22/13814 [00:03<34:48,  6.60it/s]


  0%|          | 24/13814 [00:03<29:41,  7.74it/s]

  4%|▍         | 615/13814 [00:51<16:10, 13.60it/s]


  4%|▍         | 617/13814 [00:51<16:15, 13.52it/s]


  4%|▍         | 619/13814 [00:52<15:11, 14.47it/s]


  5%|▍         | 622/13814 [00:52<13:00, 16.90it/s]


  5%|▍         | 624/13814 [00:52<17:52, 12.30it/s]


  5%|▍         | 626/13814 [00:52<16:55, 12.99it/s]


  5%|▍         | 628/13814 [00:52<16:40, 13.18it/s]


  5%|▍         | 631/13814 [00:52<14:23, 15.27it/s]


  5%|▍         | 633/13814 [00:53<17:11, 12.78it/s]


  5%|▍         | 635/13814 [00:53<15:21, 14.30it/s]


  5%|▍         | 638/13814 [00:53<13:27, 16.32it/s]


  5%|▍         | 641/13814 [00:53<12:45, 17.21it/s]


  5%|▍         | 643/13814 [00:53<14:59, 14.65it/s]


  5%|▍         | 645/13814 [00:53<13:57, 15.72it/s]


  5%|▍         | 647/13814 [00:53<15:03, 14.58it/s]


  5%|▍         | 649/13814 [00:54<19:08, 11.46it/s]


  5%|▍         | 651/13814 [00:54<17:00, 12.89it/s]


  5%|▍         | 654/13814 [00:54<15:28, 14.18it/s]


  5%|▍         | 656/13814 [

  8%|▊         | 1170/13814 [01:41<15:28, 13.61it/s]


  8%|▊         | 1172/13814 [01:41<15:10, 13.88it/s]


  8%|▊         | 1174/13814 [01:41<17:54, 11.77it/s]


  9%|▊         | 1176/13814 [01:42<17:53, 11.77it/s]


  9%|▊         | 1178/13814 [01:42<16:48, 12.53it/s]


  9%|▊         | 1180/13814 [01:42<16:25, 12.82it/s]


  9%|▊         | 1183/13814 [01:42<13:54, 15.13it/s]


  9%|▊         | 1186/13814 [01:42<12:54, 16.31it/s]


  9%|▊         | 1188/13814 [01:42<13:34, 15.51it/s]


  9%|▊         | 1191/13814 [01:42<11:51, 17.74it/s]


  9%|▊         | 1193/13814 [01:43<17:24, 12.08it/s]


  9%|▊         | 1195/13814 [01:43<15:58, 13.16it/s]


  9%|▊         | 1197/13814 [01:43<14:24, 14.59it/s]


  9%|▊         | 1199/13814 [01:43<14:21, 14.64it/s]


  9%|▊         | 1201/13814 [01:43<16:12, 12.97it/s]


  9%|▊         | 1203/13814 [01:43<18:06, 11.61it/s]


  9%|▊         | 1205/13814 [01:44<16:35, 12.67it/s]


  9%|▊         | 1207/13814 [01:44<23:18,  9.02it/s]


  9%|▉    

 12%|█▏        | 1658/13814 [02:31<36:42,  5.52it/s]


 12%|█▏        | 1660/13814 [02:31<30:23,  6.67it/s]


 12%|█▏        | 1662/13814 [02:31<26:37,  7.61it/s]


 12%|█▏        | 1663/13814 [02:31<25:00,  8.10it/s]


 12%|█▏        | 1665/13814 [02:31<21:04,  9.61it/s]


 12%|█▏        | 1667/13814 [02:31<19:06, 10.60it/s]


 12%|█▏        | 1669/13814 [02:32<16:41, 12.13it/s]


 12%|█▏        | 1671/13814 [02:32<17:11, 11.77it/s]


 12%|█▏        | 1674/13814 [02:32<15:26, 13.11it/s]


 12%|█▏        | 1676/13814 [02:32<16:16, 12.44it/s]


 12%|█▏        | 1678/13814 [02:32<21:10,  9.55it/s]


 12%|█▏        | 1680/13814 [02:33<20:21,  9.93it/s]


 12%|█▏        | 1682/13814 [02:33<21:04,  9.59it/s]


 12%|█▏        | 1684/13814 [02:33<22:37,  8.94it/s]


 12%|█▏        | 1685/13814 [02:33<22:45,  8.88it/s]


 12%|█▏        | 1687/13814 [02:33<20:38,  9.79it/s]


 12%|█▏        | 1689/13814 [02:34<18:35, 10.87it/s]


 12%|█▏        | 1691/13814 [02:34<18:20, 11.02it/s]


 12%|█▏   

 15%|█▌        | 2123/13814 [03:24<25:52,  7.53it/s]


 15%|█▌        | 2124/13814 [03:24<25:51,  7.53it/s]


 15%|█▌        | 2125/13814 [03:24<28:56,  6.73it/s]


 15%|█▌        | 2127/13814 [03:24<24:33,  7.93it/s]


 15%|█▌        | 2128/13814 [03:24<28:26,  6.85it/s]


 15%|█▌        | 2129/13814 [03:25<29:49,  6.53it/s]


 15%|█▌        | 2130/13814 [03:25<30:16,  6.43it/s]


 15%|█▌        | 2131/13814 [03:25<44:13,  4.40it/s]


 15%|█▌        | 2132/13814 [03:25<38:08,  5.10it/s]


 15%|█▌        | 2133/13814 [03:25<33:16,  5.85it/s]


 15%|█▌        | 2135/13814 [03:26<26:52,  7.24it/s]


 15%|█▌        | 2136/13814 [03:26<27:47,  7.00it/s]


 15%|█▌        | 2137/13814 [03:26<31:12,  6.24it/s]


 15%|█▌        | 2138/13814 [03:26<29:23,  6.62it/s]


 15%|█▌        | 2139/13814 [03:26<27:38,  7.04it/s]


 15%|█▌        | 2141/13814 [03:26<25:11,  7.72it/s]


 16%|█▌        | 2142/13814 [03:26<23:38,  8.23it/s]


 16%|█▌        | 2144/13814 [03:27<21:03,  9.24it/s]


 16%|█▌   

 19%|█▊        | 2556/13814 [04:15<22:24,  8.37it/s]


 19%|█▊        | 2558/13814 [04:15<31:35,  5.94it/s]


 19%|█▊        | 2559/13814 [04:15<28:20,  6.62it/s]


 19%|█▊        | 2560/13814 [04:15<27:27,  6.83it/s]


 19%|█▊        | 2562/13814 [04:16<26:05,  7.19it/s]


 19%|█▊        | 2563/13814 [04:16<27:52,  6.73it/s]


 19%|█▊        | 2565/13814 [04:16<23:16,  8.06it/s]


 19%|█▊        | 2566/13814 [04:16<27:55,  6.71it/s]


 19%|█▊        | 2567/13814 [04:16<26:29,  7.08it/s]


 19%|█▊        | 2569/13814 [04:16<22:21,  8.38it/s]


 19%|█▊        | 2571/13814 [04:17<19:19,  9.70it/s]


 19%|█▊        | 2573/13814 [04:17<27:01,  6.93it/s]


 19%|█▊        | 2575/13814 [04:17<23:18,  8.04it/s]


 19%|█▊        | 2577/13814 [04:18<25:59,  7.21it/s]


 19%|█▊        | 2579/13814 [04:18<21:44,  8.61it/s]


 19%|█▊        | 2582/13814 [04:18<20:40,  9.05it/s]


 19%|█▊        | 2584/13814 [04:18<18:38, 10.04it/s]


 19%|█▊        | 2586/13814 [04:18<16:05, 11.63it/s]


 19%|█▊   

 22%|██▏       | 3019/13814 [05:10<41:29,  4.34it/s]


 22%|██▏       | 3020/13814 [05:11<41:03,  4.38it/s]


 22%|██▏       | 3021/13814 [05:11<39:27,  4.56it/s]


 22%|██▏       | 3022/13814 [05:11<38:39,  4.65it/s]


 22%|██▏       | 3023/13814 [05:11<41:22,  4.35it/s]


 22%|██▏       | 3025/13814 [05:11<32:18,  5.56it/s]


 22%|██▏       | 3026/13814 [05:12<43:56,  4.09it/s]


 22%|██▏       | 3027/13814 [05:12<41:07,  4.37it/s]


 22%|██▏       | 3028/13814 [05:12<47:46,  3.76it/s]


 22%|██▏       | 3029/13814 [05:12<41:32,  4.33it/s]


 22%|██▏       | 3031/13814 [05:13<32:35,  5.51it/s]


 22%|██▏       | 3032/13814 [05:13<29:06,  6.18it/s]


 22%|██▏       | 3033/13814 [05:13<26:44,  6.72it/s]


 22%|██▏       | 3036/13814 [05:13<20:46,  8.65it/s]


 22%|██▏       | 3039/13814 [05:13<17:28, 10.28it/s]


 22%|██▏       | 3041/13814 [05:13<16:35, 10.82it/s]


 22%|██▏       | 3043/13814 [05:14<18:30,  9.70it/s]


 22%|██▏       | 3045/13814 [05:14<23:09,  7.75it/s]


 22%|██▏  

 25%|██▌       | 3471/13814 [06:06<23:40,  7.28it/s]


 25%|██▌       | 3473/13814 [06:06<20:04,  8.58it/s]


 25%|██▌       | 3475/13814 [06:06<17:19,  9.94it/s]


 25%|██▌       | 3477/13814 [06:06<18:43,  9.20it/s]


 25%|██▌       | 3479/13814 [06:07<26:56,  6.39it/s]


 25%|██▌       | 3480/13814 [06:07<28:13,  6.10it/s]


 25%|██▌       | 3481/13814 [06:07<30:37,  5.62it/s]


 25%|██▌       | 3482/13814 [06:08<31:56,  5.39it/s]


 25%|██▌       | 3483/13814 [06:08<37:01,  4.65it/s]


 25%|██▌       | 3484/13814 [06:08<32:36,  5.28it/s]


 25%|██▌       | 3485/13814 [06:08<39:30,  4.36it/s]


 25%|██▌       | 3486/13814 [06:08<35:42,  4.82it/s]


 25%|██▌       | 3487/13814 [06:09<37:47,  4.56it/s]


 25%|██▌       | 3488/13814 [06:09<37:31,  4.59it/s]


 25%|██▌       | 3489/13814 [06:09<34:04,  5.05it/s]


 25%|██▌       | 3490/13814 [06:09<29:51,  5.76it/s]


 25%|██▌       | 3491/13814 [06:09<27:26,  6.27it/s]


 25%|██▌       | 3493/13814 [06:09<22:25,  7.67it/s]


 25%|██▌  

 28%|██▊       | 3887/13814 [06:58<20:31,  8.06it/s]


 28%|██▊       | 3889/13814 [06:58<21:10,  7.81it/s]


 28%|██▊       | 3890/13814 [06:58<34:35,  4.78it/s]


 28%|██▊       | 3891/13814 [06:59<46:37,  3.55it/s]


 28%|██▊       | 3892/13814 [06:59<45:26,  3.64it/s]


 28%|██▊       | 3893/13814 [06:59<49:20,  3.35it/s]


 28%|██▊       | 3895/13814 [07:00<39:34,  4.18it/s]


 28%|██▊       | 3896/13814 [07:00<40:22,  4.09it/s]


 28%|██▊       | 3899/13814 [07:00<29:55,  5.52it/s]


 28%|██▊       | 3902/13814 [07:00<22:47,  7.25it/s]


 28%|██▊       | 3904/13814 [07:00<19:13,  8.59it/s]


 28%|██▊       | 3906/13814 [07:01<24:58,  6.61it/s]


 28%|██▊       | 3908/13814 [07:01<22:41,  7.27it/s]


 28%|██▊       | 3910/13814 [07:01<20:16,  8.14it/s]


 28%|██▊       | 3912/13814 [07:02<27:43,  5.95it/s]


 28%|██▊       | 3913/13814 [07:02<25:21,  6.51it/s]


 28%|██▊       | 3914/13814 [07:02<28:23,  5.81it/s]


 28%|██▊       | 3915/13814 [07:02<34:12,  4.82it/s]


 28%|██▊  

 31%|███       | 4280/13814 [07:53<31:02,  5.12it/s]


 31%|███       | 4282/13814 [07:53<24:44,  6.42it/s]


 31%|███       | 4284/13814 [07:54<23:03,  6.89it/s]


 31%|███       | 4286/13814 [07:54<19:36,  8.10it/s]


 31%|███       | 4288/13814 [07:54<20:32,  7.73it/s]


 31%|███       | 4290/13814 [07:54<18:37,  8.53it/s]


 31%|███       | 4291/13814 [07:54<20:12,  7.85it/s]


 31%|███       | 4293/13814 [07:54<18:12,  8.72it/s]


 31%|███       | 4294/13814 [07:55<17:37,  9.01it/s]


 31%|███       | 4296/13814 [07:55<14:53, 10.66it/s]


 31%|███       | 4298/13814 [07:55<20:39,  7.68it/s]


 31%|███       | 4301/13814 [07:55<16:03,  9.87it/s]


 31%|███       | 4304/13814 [07:55<14:04, 11.27it/s]


 31%|███       | 4306/13814 [07:56<16:09,  9.80it/s]


 31%|███       | 4308/13814 [07:56<14:54, 10.63it/s]


 31%|███       | 4311/13814 [07:56<12:41, 12.47it/s]


 31%|███       | 4313/13814 [07:56<12:17, 12.89it/s]


 31%|███       | 4315/13814 [07:56<12:24, 12.77it/s]


 31%|███▏ 

 34%|███▍      | 4738/13814 [08:47<14:31, 10.41it/s]


 34%|███▍      | 4740/13814 [08:47<12:45, 11.85it/s]


 34%|███▍      | 4742/13814 [08:48<11:37, 13.00it/s]


 34%|███▍      | 4744/13814 [08:48<11:19, 13.34it/s]


 34%|███▍      | 4746/13814 [08:48<11:03, 13.67it/s]


 34%|███▍      | 4748/13814 [08:48<17:55,  8.43it/s]


 34%|███▍      | 4750/13814 [08:48<18:12,  8.29it/s]


 34%|███▍      | 4752/13814 [08:49<21:56,  6.88it/s]


 34%|███▍      | 4753/13814 [08:49<24:39,  6.13it/s]


 34%|███▍      | 4755/13814 [08:49<19:42,  7.66it/s]


 34%|███▍      | 4757/13814 [08:49<17:37,  8.57it/s]


 34%|███▍      | 4759/13814 [08:50<17:52,  8.44it/s]


 34%|███▍      | 4761/13814 [08:50<27:17,  5.53it/s]


 34%|███▍      | 4763/13814 [08:50<22:26,  6.72it/s]


 34%|███▍      | 4765/13814 [08:51<18:07,  8.32it/s]


 35%|███▍      | 4767/13814 [08:51<18:02,  8.36it/s]


 35%|███▍      | 4769/13814 [08:51<17:06,  8.81it/s]


 35%|███▍      | 4771/13814 [08:51<16:35,  9.09it/s]


 35%|███▍ 

 38%|███▊      | 5190/13814 [09:42<14:57,  9.60it/s]


 38%|███▊      | 5192/13814 [09:42<12:50, 11.19it/s]


 38%|███▊      | 5194/13814 [09:43<11:47, 12.18it/s]


 38%|███▊      | 5196/13814 [09:43<13:26, 10.69it/s]


 38%|███▊      | 5198/13814 [09:43<17:17,  8.30it/s]


 38%|███▊      | 5199/13814 [09:43<27:14,  5.27it/s]


 38%|███▊      | 5201/13814 [09:44<22:35,  6.36it/s]


 38%|███▊      | 5202/13814 [09:44<21:02,  6.82it/s]


 38%|███▊      | 5204/13814 [09:44<18:34,  7.73it/s]


 38%|███▊      | 5206/13814 [09:44<15:31,  9.24it/s]


 38%|███▊      | 5208/13814 [09:44<14:42,  9.75it/s]


 38%|███▊      | 5210/13814 [09:44<15:14,  9.41it/s]


 38%|███▊      | 5212/13814 [09:45<20:39,  6.94it/s]


 38%|███▊      | 5214/13814 [09:45<17:14,  8.32it/s]


 38%|███▊      | 5216/13814 [09:46<22:14,  6.44it/s]


 38%|███▊      | 5217/13814 [09:46<26:45,  5.36it/s]


 38%|███▊      | 5218/13814 [09:46<31:54,  4.49it/s]


 38%|███▊      | 5219/13814 [09:47<42:23,  3.38it/s]


 38%|███▊ 

 41%|████      | 5643/13814 [10:37<12:04, 11.28it/s]


 41%|████      | 5645/13814 [10:37<11:35, 11.75it/s]


 41%|████      | 5647/13814 [10:37<13:46,  9.88it/s]


 41%|████      | 5650/13814 [10:37<11:43, 11.61it/s]


 41%|████      | 5653/13814 [10:38<13:52,  9.80it/s]


 41%|████      | 5655/13814 [10:38<14:04,  9.66it/s]


 41%|████      | 5659/13814 [10:38<11:16, 12.06it/s]


 41%|████      | 5661/13814 [10:38<10:52, 12.50it/s]


 41%|████      | 5663/13814 [10:38<16:15,  8.36it/s]


 41%|████      | 5665/13814 [10:39<17:24,  7.80it/s]


 41%|████      | 5667/13814 [10:39<15:27,  8.78it/s]


 41%|████      | 5669/13814 [10:39<17:25,  7.79it/s]


 41%|████      | 5670/13814 [10:39<21:38,  6.27it/s]


 41%|████      | 5671/13814 [10:40<21:56,  6.18it/s]


 41%|████      | 5672/13814 [10:40<24:28,  5.54it/s]


 41%|████      | 5674/13814 [10:40<19:23,  6.99it/s]


 41%|████      | 5676/13814 [10:40<15:55,  8.51it/s]


 41%|████      | 5678/13814 [10:40<14:23,  9.42it/s]


 41%|████ 

 44%|████▍     | 6095/13814 [11:31<21:28,  5.99it/s]


 44%|████▍     | 6096/13814 [11:31<19:37,  6.55it/s]


 44%|████▍     | 6098/13814 [11:31<16:22,  7.85it/s]


 44%|████▍     | 6100/13814 [11:32<14:19,  8.98it/s]


 44%|████▍     | 6102/13814 [11:32<12:30, 10.27it/s]


 44%|████▍     | 6105/13814 [11:32<10:25, 12.33it/s]


 44%|████▍     | 6109/13814 [11:32<08:47, 14.61it/s]


 44%|████▍     | 6111/13814 [11:32<10:39, 12.05it/s]


 44%|████▍     | 6113/13814 [11:32<09:53, 12.97it/s]


 44%|████▍     | 6115/13814 [11:33<12:18, 10.42it/s]


 44%|████▍     | 6117/13814 [11:33<16:13,  7.90it/s]


 44%|████▍     | 6120/13814 [11:33<13:55,  9.21it/s]


 44%|████▍     | 6122/13814 [11:34<21:29,  5.96it/s]


 44%|████▍     | 6124/13814 [11:34<23:22,  5.48it/s]


 44%|████▍     | 6125/13814 [11:35<25:43,  4.98it/s]


 44%|████▍     | 6126/13814 [11:35<24:24,  5.25it/s]


 44%|████▍     | 6127/13814 [11:35<22:10,  5.78it/s]


 44%|████▍     | 6128/13814 [11:35<24:01,  5.33it/s]


 44%|████▍

 48%|████▊     | 6569/13814 [12:25<08:01, 15.06it/s]


 48%|████▊     | 6571/13814 [12:26<10:32, 11.45it/s]


 48%|████▊     | 6573/13814 [12:26<12:56,  9.33it/s]


 48%|████▊     | 6575/13814 [12:27<18:13,  6.62it/s]


 48%|████▊     | 6576/13814 [12:27<29:59,  4.02it/s]


 48%|████▊     | 6577/13814 [12:27<29:09,  4.14it/s]


 48%|████▊     | 6578/13814 [12:27<25:53,  4.66it/s]


 48%|████▊     | 6579/13814 [12:27<22:02,  5.47it/s]


 48%|████▊     | 6581/13814 [12:28<18:05,  6.66it/s]


 48%|████▊     | 6582/13814 [12:28<16:35,  7.26it/s]


 48%|████▊     | 6583/13814 [12:28<19:20,  6.23it/s]


 48%|████▊     | 6584/13814 [12:28<22:06,  5.45it/s]


 48%|████▊     | 6586/13814 [12:28<18:47,  6.41it/s]


 48%|████▊     | 6587/13814 [12:29<24:08,  4.99it/s]


 48%|████▊     | 6588/13814 [12:29<26:02,  4.62it/s]


 48%|████▊     | 6589/13814 [12:29<22:00,  5.47it/s]


 48%|████▊     | 6590/13814 [12:29<21:49,  5.52it/s]


 48%|████▊     | 6591/13814 [12:29<25:03,  4.80it/s]


 48%|████▊

 51%|█████     | 7038/13814 [13:21<16:01,  7.05it/s]


 51%|█████     | 7040/13814 [13:21<14:14,  7.92it/s]


 51%|█████     | 7042/13814 [13:22<12:02,  9.37it/s]


 51%|█████     | 7044/13814 [13:22<10:51, 10.39it/s]


 51%|█████     | 7047/13814 [13:22<09:27, 11.92it/s]


 51%|█████     | 7049/13814 [13:22<12:14,  9.21it/s]


 51%|█████     | 7051/13814 [13:22<11:04, 10.18it/s]


 51%|█████     | 7053/13814 [13:23<14:18,  7.87it/s]


 51%|█████     | 7055/13814 [13:23<12:18,  9.15it/s]


 51%|█████     | 7057/13814 [13:23<10:20, 10.89it/s]


 51%|█████     | 7064/13814 [13:23<07:56, 14.17it/s]


 51%|█████     | 7067/13814 [13:24<10:30, 10.69it/s]


 51%|█████     | 7069/13814 [13:24<16:16,  6.91it/s]


 51%|█████     | 7071/13814 [13:24<14:56,  7.52it/s]


 51%|█████     | 7073/13814 [13:25<13:57,  8.05it/s]


 51%|█████     | 7075/13814 [13:25<14:40,  7.66it/s]


 51%|█████     | 7077/13814 [13:25<13:44,  8.17it/s]


 51%|█████     | 7079/13814 [13:25<13:54,  8.07it/s]


 51%|█████

 54%|█████▍    | 7472/13814 [14:18<19:18,  5.47it/s]


 54%|█████▍    | 7474/13814 [14:18<16:06,  6.56it/s]


 54%|█████▍    | 7476/13814 [14:18<15:00,  7.03it/s]


 54%|█████▍    | 7477/13814 [14:18<17:36,  6.00it/s]


 54%|█████▍    | 7478/13814 [14:18<18:14,  5.79it/s]


 54%|█████▍    | 7479/13814 [14:19<20:34,  5.13it/s]


 54%|█████▍    | 7480/13814 [14:19<20:46,  5.08it/s]


 54%|█████▍    | 7481/13814 [14:19<20:07,  5.25it/s]


 54%|█████▍    | 7482/13814 [14:19<17:45,  5.94it/s]


 54%|█████▍    | 7483/13814 [14:19<18:03,  5.84it/s]


 54%|█████▍    | 7484/13814 [14:19<16:40,  6.33it/s]


 54%|█████▍    | 7485/13814 [14:19<15:20,  6.87it/s]


 54%|█████▍    | 7487/13814 [14:20<12:19,  8.56it/s]


 54%|█████▍    | 7489/13814 [14:20<12:03,  8.74it/s]


 54%|█████▍    | 7491/13814 [14:20<12:18,  8.56it/s]


 54%|█████▍    | 7492/13814 [14:20<13:51,  7.60it/s]


 54%|█████▍    | 7496/13814 [14:20<10:35,  9.94it/s]


 54%|█████▍    | 7498/13814 [14:21<10:22, 10.15it/s]


 54%|█████

 57%|█████▋    | 7924/13814 [15:10<13:08,  7.47it/s]


 57%|█████▋    | 7926/13814 [15:10<11:15,  8.71it/s]


 57%|█████▋    | 7928/13814 [15:10<11:00,  8.91it/s]


 57%|█████▋    | 7931/13814 [15:11<11:07,  8.82it/s]


 57%|█████▋    | 7933/13814 [15:11<09:24, 10.42it/s]


 57%|█████▋    | 7936/13814 [15:11<07:44, 12.67it/s]


 57%|█████▋    | 7942/13814 [15:11<06:00, 16.31it/s]


 58%|█████▊    | 7946/13814 [15:11<05:12, 18.81it/s]


 58%|█████▊    | 7949/13814 [15:12<05:58, 16.35it/s]


 58%|█████▊    | 7952/13814 [15:12<06:03, 16.13it/s]


 58%|█████▊    | 7955/13814 [15:12<06:16, 15.58it/s]


 58%|█████▊    | 7957/13814 [15:12<08:33, 11.40it/s]


 58%|█████▊    | 7959/13814 [15:13<13:07,  7.44it/s]


 58%|█████▊    | 7961/13814 [15:13<13:03,  7.47it/s]


 58%|█████▊    | 7963/13814 [15:13<12:37,  7.72it/s]


 58%|█████▊    | 7965/13814 [15:13<10:51,  8.97it/s]


 58%|█████▊    | 7967/13814 [15:14<13:56,  6.99it/s]


 58%|█████▊    | 7968/13814 [15:14<13:44,  7.09it/s]


 58%|█████

 61%|██████    | 8430/13814 [16:06<09:31,  9.42it/s]


 61%|██████    | 8432/13814 [16:06<10:11,  8.81it/s]


 61%|██████    | 8434/13814 [16:06<10:06,  8.87it/s]


 61%|██████    | 8436/13814 [16:07<08:46, 10.22it/s]


 61%|██████    | 8438/13814 [16:07<09:28,  9.45it/s]


 61%|██████    | 8440/13814 [16:07<09:11,  9.74it/s]


 61%|██████    | 8442/13814 [16:08<15:37,  5.73it/s]


 61%|██████    | 8443/13814 [16:08<17:38,  5.08it/s]


 61%|██████    | 8444/13814 [16:08<15:25,  5.80it/s]


 61%|██████    | 8445/13814 [16:08<13:39,  6.56it/s]


 61%|██████    | 8448/13814 [16:08<10:47,  8.29it/s]


 61%|██████    | 8450/13814 [16:08<09:32,  9.38it/s]


 61%|██████    | 8452/13814 [16:09<09:55,  9.01it/s]


 61%|██████    | 8454/13814 [16:09<08:24, 10.62it/s]


 61%|██████    | 8457/13814 [16:09<07:59, 11.18it/s]


 61%|██████    | 8459/13814 [16:09<07:55, 11.26it/s]


 61%|██████    | 8461/13814 [16:09<09:06,  9.80it/s]


 61%|██████▏   | 8463/13814 [16:10<09:19,  9.57it/s]


 61%|█████

 64%|██████▍   | 8849/13814 [16:59<11:54,  6.95it/s]


 64%|██████▍   | 8850/13814 [16:59<11:37,  7.12it/s]


 64%|██████▍   | 8852/13814 [16:59<10:03,  8.22it/s]


 64%|██████▍   | 8854/13814 [16:59<09:13,  8.96it/s]


 64%|██████▍   | 8856/13814 [16:59<11:40,  7.07it/s]


 64%|██████▍   | 8857/13814 [17:00<12:59,  6.36it/s]


 64%|██████▍   | 8859/13814 [17:00<11:13,  7.36it/s]


 64%|██████▍   | 8860/13814 [17:00<11:48,  7.00it/s]


 64%|██████▍   | 8861/13814 [17:00<12:26,  6.64it/s]


 64%|██████▍   | 8862/13814 [17:00<11:45,  7.02it/s]


 64%|██████▍   | 8863/13814 [17:00<13:14,  6.24it/s]


 64%|██████▍   | 8864/13814 [17:01<16:07,  5.12it/s]


 64%|██████▍   | 8866/13814 [17:01<13:19,  6.19it/s]


 64%|██████▍   | 8867/13814 [17:01<12:57,  6.37it/s]


 64%|██████▍   | 8868/13814 [17:01<11:38,  7.09it/s]


 64%|██████▍   | 8869/13814 [17:01<10:47,  7.64it/s]


 64%|██████▍   | 8870/13814 [17:02<15:59,  5.15it/s]


 64%|██████▍   | 8871/13814 [17:02<15:44,  5.24it/s]


 64%|█████

 67%|██████▋   | 9280/13814 [17:51<17:53,  4.22it/s]


 67%|██████▋   | 9282/13814 [17:51<13:47,  5.48it/s]


 67%|██████▋   | 9283/13814 [17:51<13:39,  5.53it/s]


 67%|██████▋   | 9285/13814 [17:52<10:42,  7.04it/s]


 67%|██████▋   | 9287/13814 [17:52<10:27,  7.21it/s]


 67%|██████▋   | 9289/13814 [17:52<09:34,  7.88it/s]


 67%|██████▋   | 9291/13814 [17:52<10:38,  7.09it/s]


 67%|██████▋   | 9293/13814 [17:53<09:38,  7.81it/s]


 67%|██████▋   | 9294/13814 [17:53<12:11,  6.18it/s]


 67%|██████▋   | 9295/13814 [17:53<13:18,  5.66it/s]


 67%|██████▋   | 9297/13814 [17:53<10:56,  6.88it/s]


 67%|██████▋   | 9298/13814 [17:53<12:12,  6.17it/s]


 67%|██████▋   | 9299/13814 [17:54<13:10,  5.71it/s]


 67%|██████▋   | 9301/13814 [17:54<11:35,  6.48it/s]


 67%|██████▋   | 9303/13814 [17:54<10:46,  6.98it/s]


 67%|██████▋   | 9305/13814 [17:54<09:20,  8.05it/s]


 67%|██████▋   | 9307/13814 [17:54<10:18,  7.29it/s]


 67%|██████▋   | 9308/13814 [17:55<10:16,  7.31it/s]


 67%|█████

 70%|███████   | 9700/13814 [18:44<13:55,  4.92it/s]


 70%|███████   | 9701/13814 [18:44<13:35,  5.04it/s]


 70%|███████   | 9702/13814 [18:44<14:50,  4.62it/s]


 70%|███████   | 9703/13814 [18:45<17:29,  3.92it/s]


 70%|███████   | 9705/13814 [18:45<14:27,  4.74it/s]


 70%|███████   | 9706/13814 [18:45<15:41,  4.36it/s]


 70%|███████   | 9708/13814 [18:45<13:03,  5.24it/s]


 70%|███████   | 9709/13814 [18:45<12:18,  5.56it/s]


 70%|███████   | 9711/13814 [18:46<10:57,  6.24it/s]


 70%|███████   | 9712/13814 [18:46<11:44,  5.82it/s]


 70%|███████   | 9714/13814 [18:46<09:28,  7.21it/s]


 70%|███████   | 9716/13814 [18:46<07:50,  8.71it/s]


 70%|███████   | 9718/13814 [18:46<07:16,  9.39it/s]


 70%|███████   | 9720/13814 [18:46<07:16,  9.39it/s]


 70%|███████   | 9723/13814 [18:47<06:49, 10.00it/s]


 70%|███████   | 9725/13814 [18:47<09:14,  7.38it/s]


 70%|███████   | 9726/13814 [18:47<08:59,  7.58it/s]


 70%|███████   | 9727/13814 [18:47<08:52,  7.67it/s]


 70%|█████

 74%|███████▎  | 10179/13814 [19:38<09:00,  6.73it/s]


 74%|███████▎  | 10180/13814 [19:38<10:07,  5.98it/s]


 74%|███████▎  | 10181/13814 [19:39<19:51,  3.05it/s]


 74%|███████▎  | 10182/13814 [19:39<16:23,  3.69it/s]


 74%|███████▎  | 10184/13814 [19:39<12:34,  4.81it/s]


 74%|███████▎  | 10185/13814 [19:40<10:47,  5.60it/s]


 74%|███████▎  | 10187/13814 [19:40<09:58,  6.06it/s]


 74%|███████▍  | 10188/13814 [19:40<09:45,  6.19it/s]


 74%|███████▍  | 10189/13814 [19:40<10:16,  5.88it/s]


 74%|███████▍  | 10191/13814 [19:40<08:12,  7.36it/s]


 74%|███████▍  | 10193/13814 [19:41<08:25,  7.16it/s]


 74%|███████▍  | 10194/13814 [19:41<08:32,  7.06it/s]


 74%|███████▍  | 10195/13814 [19:41<07:56,  7.60it/s]


 74%|███████▍  | 10196/13814 [19:41<07:21,  8.19it/s]


 74%|███████▍  | 10198/13814 [19:41<06:21,  9.48it/s]


 74%|███████▍  | 10200/13814 [19:41<05:29, 10.96it/s]


 74%|███████▍  | 10202/13814 [19:41<05:42, 10.54it/s]


 74%|███████▍  | 10204/13814 [19:42<06:42,  8.97

 77%|███████▋  | 10602/13814 [20:34<07:54,  6.77it/s]


 77%|███████▋  | 10603/13814 [20:34<08:08,  6.58it/s]


 77%|███████▋  | 10604/13814 [20:34<09:18,  5.75it/s]


 77%|███████▋  | 10605/13814 [20:34<08:37,  6.21it/s]


 77%|███████▋  | 10606/13814 [20:34<08:23,  6.37it/s]


 77%|███████▋  | 10607/13814 [20:34<08:16,  6.46it/s]


 77%|███████▋  | 10608/13814 [20:34<07:24,  7.21it/s]


 77%|███████▋  | 10609/13814 [20:35<08:14,  6.48it/s]


 77%|███████▋  | 10610/13814 [20:35<11:12,  4.76it/s]


 77%|███████▋  | 10611/13814 [20:35<11:05,  4.82it/s]


 77%|███████▋  | 10613/13814 [20:35<09:33,  5.58it/s]


 77%|███████▋  | 10614/13814 [20:36<09:10,  5.81it/s]


 77%|███████▋  | 10615/13814 [20:36<08:26,  6.32it/s]


 77%|███████▋  | 10616/13814 [20:36<07:59,  6.67it/s]


 77%|███████▋  | 10619/13814 [20:36<06:41,  7.95it/s]


 77%|███████▋  | 10620/13814 [20:36<07:11,  7.40it/s]


 77%|███████▋  | 10621/13814 [20:36<08:33,  6.21it/s]


 77%|███████▋  | 10622/13814 [20:37<12:28,  4.26

 80%|███████▉  | 11022/13814 [21:24<06:25,  7.23it/s]


 80%|███████▉  | 11024/13814 [21:24<05:40,  8.19it/s]


 80%|███████▉  | 11026/13814 [21:24<04:59,  9.32it/s]


 80%|███████▉  | 11029/13814 [21:24<04:12, 11.03it/s]


 80%|███████▉  | 11031/13814 [21:24<03:38, 12.72it/s]


 80%|███████▉  | 11033/13814 [21:25<04:55,  9.42it/s]


 80%|███████▉  | 11036/13814 [21:25<03:56, 11.77it/s]


 80%|███████▉  | 11039/13814 [21:25<03:52, 11.95it/s]


 80%|███████▉  | 11041/13814 [21:25<03:56, 11.71it/s]


 80%|███████▉  | 11043/13814 [21:26<05:10,  8.92it/s]


 80%|███████▉  | 11045/13814 [21:26<05:08,  8.97it/s]


 80%|███████▉  | 11047/13814 [21:26<04:19, 10.66it/s]


 80%|███████▉  | 11049/13814 [21:26<03:49, 12.07it/s]


 80%|███████▉  | 11051/13814 [21:26<05:03,  9.11it/s]


 80%|████████  | 11053/13814 [21:27<05:00,  9.20it/s]


 80%|████████  | 11056/13814 [21:27<04:28, 10.28it/s]


 80%|████████  | 11058/13814 [21:27<04:31, 10.16it/s]


 80%|████████  | 11060/13814 [21:28<06:41,  6.86

 83%|████████▎ | 11442/13814 [22:15<05:20,  7.39it/s]


 83%|████████▎ | 11444/13814 [22:15<04:38,  8.52it/s]


 83%|████████▎ | 11446/13814 [22:16<04:10,  9.46it/s]


 83%|████████▎ | 11449/13814 [22:16<03:19, 11.84it/s]


 83%|████████▎ | 11451/13814 [22:16<04:22,  9.00it/s]


 83%|████████▎ | 11453/13814 [22:16<04:47,  8.20it/s]


 83%|████████▎ | 11455/13814 [22:17<04:47,  8.21it/s]


 83%|████████▎ | 11457/13814 [22:17<04:06,  9.57it/s]


 83%|████████▎ | 11459/13814 [22:17<03:56,  9.97it/s]


 83%|████████▎ | 11461/13814 [22:17<04:42,  8.33it/s]


 83%|████████▎ | 11462/13814 [22:17<05:37,  6.96it/s]


 83%|████████▎ | 11463/13814 [22:18<05:45,  6.81it/s]


 83%|████████▎ | 11465/13814 [22:18<04:53,  8.01it/s]


 83%|████████▎ | 11467/13814 [22:18<05:10,  7.57it/s]


 83%|████████▎ | 11468/13814 [22:18<05:52,  6.66it/s]


 83%|████████▎ | 11469/13814 [22:18<06:22,  6.13it/s]


 83%|████████▎ | 11470/13814 [22:19<06:26,  6.06it/s]


 83%|████████▎ | 11471/13814 [22:19<05:54,  6.60

 86%|████████▌ | 11828/13814 [23:07<04:21,  7.60it/s]


 86%|████████▌ | 11830/13814 [23:07<03:48,  8.67it/s]


 86%|████████▌ | 11832/13814 [23:07<03:22,  9.78it/s]


 86%|████████▌ | 11834/13814 [23:08<03:41,  8.95it/s]


 86%|████████▌ | 11836/13814 [23:08<03:44,  8.82it/s]


 86%|████████▌ | 11837/13814 [23:08<03:45,  8.78it/s]


 86%|████████▌ | 11838/13814 [23:08<03:52,  8.51it/s]


 86%|████████▌ | 11840/13814 [23:08<03:29,  9.44it/s]


 86%|████████▌ | 11842/13814 [23:08<03:03, 10.72it/s]


 86%|████████▌ | 11844/13814 [23:09<03:18,  9.90it/s]


 86%|████████▌ | 11846/13814 [23:09<04:14,  7.73it/s]


 86%|████████▌ | 11847/13814 [23:09<06:14,  5.25it/s]


 86%|████████▌ | 11849/13814 [23:09<04:52,  6.73it/s]


 86%|████████▌ | 11851/13814 [23:10<04:09,  7.87it/s]


 86%|████████▌ | 11853/13814 [23:10<04:52,  6.69it/s]


 86%|████████▌ | 11854/13814 [23:10<05:05,  6.42it/s]


 86%|████████▌ | 11855/13814 [23:10<05:27,  5.98it/s]


 86%|████████▌ | 11856/13814 [23:11<05:37,  5.80

 89%|████████▊ | 12243/13814 [24:02<06:14,  4.20it/s]


 89%|████████▊ | 12246/13814 [24:02<04:48,  5.43it/s]


 89%|████████▊ | 12247/13814 [24:02<04:17,  6.09it/s]


 89%|████████▊ | 12248/13814 [24:02<04:21,  5.98it/s]


 89%|████████▊ | 12251/13814 [24:02<03:32,  7.35it/s]


 89%|████████▊ | 12253/13814 [24:03<03:51,  6.73it/s]


 89%|████████▊ | 12254/13814 [24:03<03:31,  7.38it/s]


 89%|████████▊ | 12255/13814 [24:03<03:23,  7.64it/s]


 89%|████████▊ | 12257/13814 [24:03<03:07,  8.30it/s]


 89%|████████▊ | 12259/13814 [24:03<02:41,  9.61it/s]


 89%|████████▉ | 12261/13814 [24:04<02:52,  9.01it/s]


 89%|████████▉ | 12263/13814 [24:04<02:35, 10.00it/s]


 89%|████████▉ | 12265/13814 [24:04<02:17, 11.30it/s]


 89%|████████▉ | 12268/13814 [24:04<01:52, 13.71it/s]


 89%|████████▉ | 12271/13814 [24:04<01:43, 14.91it/s]


 89%|████████▉ | 12274/13814 [24:04<01:31, 16.78it/s]


 89%|████████▉ | 12278/13814 [24:04<01:17, 19.72it/s]


 89%|████████▉ | 12281/13814 [24:05<02:02, 12.51

 92%|█████████▏| 12674/13814 [24:52<02:15,  8.43it/s]


 92%|█████████▏| 12676/13814 [24:53<03:12,  5.90it/s]


 92%|█████████▏| 12677/13814 [24:53<02:54,  6.51it/s]


 92%|█████████▏| 12678/13814 [24:53<02:47,  6.76it/s]


 92%|█████████▏| 12680/13814 [24:54<02:41,  7.02it/s]


 92%|█████████▏| 12681/13814 [24:54<02:33,  7.39it/s]


 92%|█████████▏| 12683/13814 [24:54<02:15,  8.32it/s]


 92%|█████████▏| 12685/13814 [24:54<02:07,  8.86it/s]


 92%|█████████▏| 12687/13814 [24:54<01:54,  9.82it/s]


 92%|█████████▏| 12690/13814 [24:54<01:35, 11.80it/s]


 92%|█████████▏| 12692/13814 [24:55<01:57,  9.56it/s]


 92%|█████████▏| 12694/13814 [24:55<01:50, 10.16it/s]


 92%|█████████▏| 12696/13814 [24:55<01:52,  9.98it/s]


 92%|█████████▏| 12698/13814 [24:55<01:47, 10.41it/s]


 92%|█████████▏| 12700/13814 [24:56<02:38,  7.04it/s]


 92%|█████████▏| 12701/13814 [24:56<02:30,  7.41it/s]


 92%|█████████▏| 12702/13814 [24:56<02:34,  7.22it/s]


 92%|█████████▏| 12705/13814 [24:56<01:59,  9.26

 95%|█████████▌| 13133/13814 [25:46<01:51,  6.09it/s]


 95%|█████████▌| 13134/13814 [25:46<01:55,  5.87it/s]


 95%|█████████▌| 13136/13814 [25:46<01:39,  6.83it/s]


 95%|█████████▌| 13138/13814 [25:47<01:26,  7.84it/s]


 95%|█████████▌| 13140/13814 [25:47<01:43,  6.52it/s]


 95%|█████████▌| 13142/13814 [25:47<01:31,  7.38it/s]


 95%|█████████▌| 13145/13814 [25:47<01:12,  9.21it/s]


 95%|█████████▌| 13147/13814 [25:47<01:02, 10.61it/s]


 95%|█████████▌| 13149/13814 [25:48<00:54, 12.26it/s]


 95%|█████████▌| 13151/13814 [25:48<01:02, 10.60it/s]


 95%|█████████▌| 13153/13814 [25:48<00:55, 11.99it/s]


 95%|█████████▌| 13155/13814 [25:48<00:50, 13.12it/s]


 95%|█████████▌| 13157/13814 [25:48<00:46, 14.11it/s]


 95%|█████████▌| 13159/13814 [25:48<00:46, 14.20it/s]


 95%|█████████▌| 13161/13814 [25:49<01:04, 10.19it/s]


 95%|█████████▌| 13163/13814 [25:49<00:58, 11.19it/s]


 95%|█████████▌| 13165/13814 [25:49<00:56, 11.54it/s]


 95%|█████████▌| 13167/13814 [25:50<01:41,  6.40

 98%|█████████▊| 13582/13814 [26:38<00:36,  6.30it/s]


 98%|█████████▊| 13584/13814 [26:38<00:30,  7.66it/s]


 98%|█████████▊| 13586/13814 [26:39<00:37,  6.06it/s]


 98%|█████████▊| 13588/13814 [26:39<00:29,  7.55it/s]


 98%|█████████▊| 13590/13814 [26:39<00:30,  7.24it/s]


 98%|█████████▊| 13591/13814 [26:39<00:28,  7.77it/s]


 98%|█████████▊| 13592/13814 [26:39<00:26,  8.24it/s]


 98%|█████████▊| 13595/13814 [26:39<00:21, 10.04it/s]


 98%|█████████▊| 13598/13814 [26:39<00:17, 12.42it/s]


 98%|█████████▊| 13600/13814 [26:40<00:25,  8.53it/s]


 98%|█████████▊| 13602/13814 [26:40<00:23,  9.21it/s]


 98%|█████████▊| 13604/13814 [26:40<00:23,  9.04it/s]


 99%|█████████▊| 13608/13814 [26:40<00:19, 10.70it/s]


 99%|█████████▊| 13610/13814 [26:41<00:17, 11.93it/s]


 99%|█████████▊| 13612/13814 [26:41<00:20,  9.67it/s]


 99%|█████████▊| 13614/13814 [26:41<00:21,  9.36it/s]


 99%|█████████▊| 13616/13814 [26:41<00:18, 10.83it/s]


 99%|█████████▊| 13620/13814 [26:41<00:15, 12.51

0.1689120709794673
---------- Started Epoch 2 -----------





  0%|          | 3/13814 [00:00<20:42, 11.12it/s]


  0%|          | 4/13814 [00:00<27:57,  8.23it/s]


  0%|          | 5/13814 [00:00<28:06,  8.19it/s]


  0%|          | 6/13814 [00:00<26:44,  8.60it/s]


  0%|          | 8/13814 [00:00<25:01,  9.19it/s]


  0%|          | 10/13814 [00:00<21:09, 10.87it/s]


  0%|          | 12/13814 [00:01<19:52, 11.57it/s]


  0%|          | 15/13814 [00:01<16:36, 13.84it/s]


  0%|          | 17/13814 [00:01<17:36, 13.06it/s]


  0%|          | 19/13814 [00:01<15:48, 14.54it/s]


  0%|          | 22/13814 [00:01<14:45, 15.58it/s]


  0%|          | 28/13814 [00:01<11:45, 19.55it/s]


  0%|          | 31/13814 [00:02<13:38, 16.83it/s]


  0%|          | 34/13814 [00:02<21:48, 10.53it/s]


  0%|          | 36/13814 [00:02<22:25, 10.24it/s]


  0%|          | 38/13814 [00:03<29:24,  7.81it/s]


  0%|          | 40/13814 [00:03<25:33,  8.98it/s]


  0%|          | 42/13814 [00:03<23:12,  9.89it/s]


  0%|          | 44/13814 [00:03<21:36, 10.62it/

  4%|▍         | 614/13814 [00:49<16:58, 12.95it/s]


  4%|▍         | 617/13814 [00:49<15:23, 14.30it/s]


  4%|▍         | 619/13814 [00:49<18:42, 11.75it/s]


  5%|▍         | 623/13814 [00:49<15:07, 14.54it/s]


  5%|▍         | 626/13814 [00:50<16:01, 13.71it/s]


  5%|▍         | 628/13814 [00:50<15:16, 14.38it/s]


  5%|▍         | 630/13814 [00:50<14:07, 15.56it/s]


  5%|▍         | 632/13814 [00:50<18:34, 11.83it/s]


  5%|▍         | 634/13814 [00:50<18:49, 11.67it/s]


  5%|▍         | 636/13814 [00:51<20:18, 10.81it/s]


  5%|▍         | 640/13814 [00:51<15:54, 13.80it/s]


  5%|▍         | 643/13814 [00:51<14:21, 15.29it/s]


  5%|▍         | 646/13814 [00:51<13:07, 16.73it/s]


  5%|▍         | 649/13814 [00:51<17:51, 12.29it/s]


  5%|▍         | 651/13814 [00:52<16:48, 13.05it/s]


  5%|▍         | 653/13814 [00:52<16:51, 13.01it/s]


  5%|▍         | 655/13814 [00:52<17:49, 12.31it/s]


  5%|▍         | 657/13814 [00:52<16:22, 13.39it/s]


  5%|▍         | 659/13814 [

  9%|▉         | 1217/13814 [01:42<23:23,  8.97it/s]


  9%|▉         | 1219/13814 [01:42<20:06, 10.44it/s]


  9%|▉         | 1221/13814 [01:42<23:24,  8.97it/s]


  9%|▉         | 1223/13814 [01:43<27:03,  7.75it/s]


  9%|▉         | 1224/13814 [01:43<30:26,  6.89it/s]


  9%|▉         | 1226/13814 [01:43<25:29,  8.23it/s]


  9%|▉         | 1228/13814 [01:43<22:55,  9.15it/s]


  9%|▉         | 1231/13814 [01:43<18:47, 11.16it/s]


  9%|▉         | 1233/13814 [01:43<16:30, 12.71it/s]


  9%|▉         | 1235/13814 [01:44<21:34,  9.72it/s]


  9%|▉         | 1237/13814 [01:44<20:35, 10.18it/s]


  9%|▉         | 1241/13814 [01:44<16:53, 12.40it/s]


  9%|▉         | 1243/13814 [01:44<17:54, 11.70it/s]


  9%|▉         | 1245/13814 [01:44<18:45, 11.17it/s]


  9%|▉         | 1249/13814 [01:44<14:58, 13.99it/s]


  9%|▉         | 1251/13814 [01:45<17:22, 12.05it/s]


  9%|▉         | 1254/13814 [01:45<15:14, 13.74it/s]


  9%|▉         | 1259/13814 [01:45<12:23, 16.89it/s]


  9%|▉    

 12%|█▏        | 1725/13814 [02:32<29:34,  6.81it/s]


 12%|█▏        | 1726/13814 [02:32<32:37,  6.18it/s]


 13%|█▎        | 1727/13814 [02:32<32:37,  6.17it/s]


 13%|█▎        | 1729/13814 [02:32<28:12,  7.14it/s]


 13%|█▎        | 1730/13814 [02:32<26:31,  7.59it/s]


 13%|█▎        | 1731/13814 [02:32<26:11,  7.69it/s]


 13%|█▎        | 1733/13814 [02:32<21:36,  9.32it/s]


 13%|█▎        | 1736/13814 [02:33<17:31, 11.49it/s]


 13%|█▎        | 1738/13814 [02:33<16:31, 12.18it/s]


 13%|█▎        | 1740/13814 [02:33<17:35, 11.44it/s]


 13%|█▎        | 1742/13814 [02:33<17:52, 11.25it/s]


 13%|█▎        | 1744/13814 [02:33<18:23, 10.94it/s]


 13%|█▎        | 1746/13814 [02:33<18:13, 11.03it/s]


 13%|█▎        | 1748/13814 [02:34<18:38, 10.79it/s]


 13%|█▎        | 1750/13814 [02:34<18:50, 10.67it/s]


 13%|█▎        | 1752/13814 [02:34<18:14, 11.02it/s]


 13%|█▎        | 1755/13814 [02:34<14:48, 13.57it/s]


 13%|█▎        | 1757/13814 [02:34<14:57, 13.43it/s]


 13%|█▎   

 16%|█▌        | 2164/13814 [03:23<24:07,  8.05it/s]


 16%|█▌        | 2165/13814 [03:23<33:19,  5.83it/s]


 16%|█▌        | 2168/13814 [03:23<26:51,  7.23it/s]


 16%|█▌        | 2169/13814 [03:24<30:00,  6.47it/s]


 16%|█▌        | 2171/13814 [03:24<26:47,  7.24it/s]


 16%|█▌        | 2172/13814 [03:24<38:20,  5.06it/s]


 16%|█▌        | 2173/13814 [03:24<35:00,  5.54it/s]


 16%|█▌        | 2176/13814 [03:24<26:34,  7.30it/s]


 16%|█▌        | 2179/13814 [03:24<20:40,  9.38it/s]


 16%|█▌        | 2182/13814 [03:25<17:06, 11.33it/s]


 16%|█▌        | 2184/13814 [03:25<18:32, 10.46it/s]


 16%|█▌        | 2186/13814 [03:25<17:56, 10.81it/s]


 16%|█▌        | 2188/13814 [03:25<16:40, 11.62it/s]


 16%|█▌        | 2190/13814 [03:25<21:55,  8.84it/s]


 16%|█▌        | 2192/13814 [03:26<19:37,  9.87it/s]


 16%|█▌        | 2194/13814 [03:26<30:50,  6.28it/s]


 16%|█▌        | 2195/13814 [03:26<33:14,  5.83it/s]


 16%|█▌        | 2196/13814 [03:27<32:03,  6.04it/s]


 16%|█▌   

 19%|█▉        | 2596/13814 [04:18<32:03,  5.83it/s]


 19%|█▉        | 2597/13814 [04:19<1:04:04,  2.92it/s]


 19%|█▉        | 2598/13814 [04:19<56:49,  3.29it/s]  


 19%|█▉        | 2599/13814 [04:20<1:13:42,  2.54it/s]


 19%|█▉        | 2600/13814 [04:20<1:02:53,  2.97it/s]


 19%|█▉        | 2601/13814 [04:20<54:04,  3.46it/s]  


 19%|█▉        | 2602/13814 [04:21<52:21,  3.57it/s]


 19%|█▉        | 2603/13814 [04:21<44:05,  4.24it/s]


 19%|█▉        | 2605/13814 [04:21<34:27,  5.42it/s]


 19%|█▉        | 2606/13814 [04:21<30:27,  6.13it/s]


 19%|█▉        | 2608/13814 [04:21<26:35,  7.02it/s]


 19%|█▉        | 2609/13814 [04:21<25:57,  7.20it/s]


 19%|█▉        | 2610/13814 [04:21<25:26,  7.34it/s]


 19%|█▉        | 2611/13814 [04:22<25:04,  7.45it/s]


 19%|█▉        | 2612/13814 [04:22<32:01,  5.83it/s]


 19%|█▉        | 2613/13814 [04:22<30:05,  6.20it/s]


 19%|█▉        | 2614/13814 [04:22<28:29,  6.55it/s]


 19%|█▉        | 2616/13814 [04:22<23:20,  8.00it/s]




 22%|██▏       | 3019/13814 [05:13<42:36,  4.22it/s]


 22%|██▏       | 3021/13814 [05:13<35:31,  5.06it/s]


 22%|██▏       | 3023/13814 [05:13<30:47,  5.84it/s]


 22%|██▏       | 3025/13814 [05:13<26:24,  6.81it/s]


 22%|██▏       | 3027/13814 [05:13<23:17,  7.72it/s]


 22%|██▏       | 3028/13814 [05:14<36:40,  4.90it/s]


 22%|██▏       | 3030/13814 [05:14<29:11,  6.16it/s]


 22%|██▏       | 3031/13814 [05:14<32:31,  5.53it/s]


 22%|██▏       | 3032/13814 [05:14<29:40,  6.06it/s]


 22%|██▏       | 3033/13814 [05:15<30:58,  5.80it/s]


 22%|██▏       | 3034/13814 [05:15<27:09,  6.62it/s]


 22%|██▏       | 3038/13814 [05:15<20:58,  8.56it/s]


 22%|██▏       | 3040/13814 [05:15<20:59,  8.55it/s]


 22%|██▏       | 3044/13814 [05:15<17:37, 10.18it/s]


 22%|██▏       | 3046/13814 [05:15<18:07,  9.90it/s]


 22%|██▏       | 3049/13814 [05:16<14:45, 12.15it/s]


 22%|██▏       | 3052/13814 [05:16<13:43, 13.07it/s]


 22%|██▏       | 3054/13814 [05:16<15:21, 11.68it/s]


 22%|██▏  

 25%|██▍       | 3431/13814 [06:06<37:31,  4.61it/s]


 25%|██▍       | 3433/13814 [06:06<30:10,  5.73it/s]


 25%|██▍       | 3434/13814 [06:06<26:21,  6.56it/s]


 25%|██▍       | 3435/13814 [06:06<24:34,  7.04it/s]


 25%|██▍       | 3437/13814 [06:06<20:42,  8.35it/s]


 25%|██▍       | 3439/13814 [06:06<17:14, 10.03it/s]


 25%|██▍       | 3441/13814 [06:07<19:18,  8.95it/s]


 25%|██▍       | 3444/13814 [06:07<17:18,  9.98it/s]


 25%|██▍       | 3446/13814 [06:07<15:22, 11.24it/s]


 25%|██▍       | 3448/13814 [06:07<13:21, 12.93it/s]


 25%|██▍       | 3451/13814 [06:07<11:14, 15.37it/s]


 25%|██▍       | 3453/13814 [06:07<12:28, 13.83it/s]


 25%|██▌       | 3455/13814 [06:07<12:47, 13.49it/s]


 25%|██▌       | 3457/13814 [06:08<17:09, 10.06it/s]


 25%|██▌       | 3459/13814 [06:08<16:48, 10.26it/s]


 25%|██▌       | 3461/13814 [06:08<21:30,  8.02it/s]


 25%|██▌       | 3463/13814 [06:09<26:39,  6.47it/s]


 25%|██▌       | 3464/13814 [06:09<38:23,  4.49it/s]


 25%|██▌  

 28%|██▊       | 3882/13814 [06:59<22:38,  7.31it/s]


 28%|██▊       | 3884/13814 [06:59<20:58,  7.89it/s]


 28%|██▊       | 3885/13814 [06:59<20:33,  8.05it/s]


 28%|██▊       | 3886/13814 [07:00<26:41,  6.20it/s]


 28%|██▊       | 3887/13814 [07:00<34:46,  4.76it/s]


 28%|██▊       | 3888/13814 [07:00<33:39,  4.92it/s]


 28%|██▊       | 3889/13814 [07:00<28:50,  5.74it/s]


 28%|██▊       | 3890/13814 [07:01<34:19,  4.82it/s]


 28%|██▊       | 3891/13814 [07:01<35:01,  4.72it/s]


 28%|██▊       | 3893/13814 [07:01<38:08,  4.33it/s]


 28%|██▊       | 3894/13814 [07:01<34:04,  4.85it/s]


 28%|██▊       | 3895/13814 [07:02<29:59,  5.51it/s]


 28%|██▊       | 3896/13814 [07:02<26:51,  6.15it/s]


 28%|██▊       | 3898/13814 [07:02<21:56,  7.53it/s]


 28%|██▊       | 3901/13814 [07:02<17:28,  9.45it/s]


 28%|██▊       | 3904/13814 [07:02<14:13, 11.60it/s]


 28%|██▊       | 3906/13814 [07:02<16:07, 10.24it/s]


 28%|██▊       | 3908/13814 [07:03<17:40,  9.34it/s]


 28%|██▊  

 31%|███▏      | 4326/13814 [07:53<16:37,  9.51it/s]


 31%|███▏      | 4328/13814 [07:53<20:30,  7.71it/s]


 31%|███▏      | 4330/13814 [07:53<26:05,  6.06it/s]


 31%|███▏      | 4331/13814 [07:54<25:08,  6.29it/s]


 31%|███▏      | 4332/13814 [07:54<26:41,  5.92it/s]


 31%|███▏      | 4333/13814 [07:54<25:22,  6.23it/s]


 31%|███▏      | 4334/13814 [07:54<23:51,  6.62it/s]


 31%|███▏      | 4336/13814 [07:54<23:16,  6.79it/s]


 31%|███▏      | 4337/13814 [07:55<24:58,  6.32it/s]


 31%|███▏      | 4338/13814 [07:55<30:39,  5.15it/s]


 31%|███▏      | 4339/13814 [07:55<31:20,  5.04it/s]


 31%|███▏      | 4340/13814 [07:55<28:51,  5.47it/s]


 31%|███▏      | 4341/13814 [07:55<33:16,  4.74it/s]


 31%|███▏      | 4342/13814 [07:56<31:15,  5.05it/s]


 31%|███▏      | 4343/13814 [07:56<29:59,  5.26it/s]


 31%|███▏      | 4345/13814 [07:56<23:39,  6.67it/s]


 31%|███▏      | 4346/13814 [07:56<28:46,  5.48it/s]


 31%|███▏      | 4349/13814 [07:57<28:21,  5.56it/s]


 31%|███▏ 

 35%|███▍      | 4786/13814 [08:46<11:56, 12.59it/s]


 35%|███▍      | 4789/13814 [08:46<12:33, 11.97it/s]


 35%|███▍      | 4791/13814 [08:47<13:33, 11.09it/s]


 35%|███▍      | 4793/13814 [08:47<19:05,  7.87it/s]


 35%|███▍      | 4794/13814 [08:47<24:27,  6.15it/s]


 35%|███▍      | 4795/13814 [08:47<24:22,  6.17it/s]


 35%|███▍      | 4797/13814 [08:48<20:28,  7.34it/s]


 35%|███▍      | 4799/13814 [08:48<21:15,  7.07it/s]


 35%|███▍      | 4801/13814 [08:48<17:24,  8.63it/s]


 35%|███▍      | 4803/13814 [08:48<20:21,  7.38it/s]


 35%|███▍      | 4805/13814 [08:49<18:35,  8.07it/s]


 35%|███▍      | 4806/13814 [08:49<17:44,  8.46it/s]


 35%|███▍      | 4808/13814 [08:49<15:07,  9.92it/s]


 35%|███▍      | 4810/13814 [08:49<18:54,  7.94it/s]


 35%|███▍      | 4811/13814 [08:49<23:37,  6.35it/s]


 35%|███▍      | 4812/13814 [08:50<23:00,  6.52it/s]


 35%|███▍      | 4814/13814 [08:50<22:46,  6.59it/s]


 35%|███▍      | 4816/13814 [08:50<18:20,  8.18it/s]


 35%|███▍ 

 38%|███▊      | 5257/13814 [09:40<17:53,  7.97it/s]


 38%|███▊      | 5259/13814 [09:40<18:00,  7.91it/s]


 38%|███▊      | 5261/13814 [09:40<16:15,  8.77it/s]


 38%|███▊      | 5263/13814 [09:40<15:03,  9.46it/s]


 38%|███▊      | 5265/13814 [09:40<14:15,  9.99it/s]


 38%|███▊      | 5267/13814 [09:41<15:12,  9.37it/s]


 38%|███▊      | 5269/13814 [09:41<15:13,  9.35it/s]


 38%|███▊      | 5271/13814 [09:41<13:21, 10.66it/s]


 38%|███▊      | 5273/13814 [09:41<11:34, 12.30it/s]


 38%|███▊      | 5275/13814 [09:41<13:17, 10.71it/s]


 38%|███▊      | 5277/13814 [09:42<14:31,  9.80it/s]


 38%|███▊      | 5279/13814 [09:42<19:13,  7.40it/s]


 38%|███▊      | 5280/13814 [09:42<25:49,  5.51it/s]


 38%|███▊      | 5282/13814 [09:42<20:25,  6.96it/s]


 38%|███▊      | 5284/13814 [09:43<21:52,  6.50it/s]


 38%|███▊      | 5288/13814 [09:43<17:01,  8.35it/s]


 38%|███▊      | 5290/13814 [09:43<14:23,  9.87it/s]


 38%|███▊      | 5292/13814 [09:43<15:23,  9.23it/s]


 38%|███▊ 

 41%|████      | 5692/13814 [10:35<13:43,  9.87it/s]


 41%|████      | 5694/13814 [10:35<12:01, 11.25it/s]


 41%|████      | 5696/13814 [10:35<11:53, 11.38it/s]


 41%|████      | 5698/13814 [10:36<12:20, 10.96it/s]


 41%|████▏     | 5700/13814 [10:36<11:58, 11.30it/s]


 41%|████▏     | 5702/13814 [10:36<15:15,  8.86it/s]


 41%|████▏     | 5704/13814 [10:36<17:39,  7.65it/s]


 41%|████▏     | 5705/13814 [10:36<16:40,  8.11it/s]


 41%|████▏     | 5706/13814 [10:37<16:36,  8.14it/s]


 41%|████▏     | 5708/13814 [10:37<13:45,  9.83it/s]


 41%|████▏     | 5710/13814 [10:37<12:42, 10.62it/s]


 41%|████▏     | 5712/13814 [10:37<10:55, 12.35it/s]


 41%|████▏     | 5714/13814 [10:37<11:33, 11.68it/s]


 41%|████▏     | 5716/13814 [10:37<12:45, 10.58it/s]


 41%|████▏     | 5718/13814 [10:38<11:31, 11.70it/s]


 41%|████▏     | 5720/13814 [10:38<10:57, 12.30it/s]


 41%|████▏     | 5722/13814 [10:38<11:10, 12.06it/s]


 41%|████▏     | 5724/13814 [10:38<09:56, 13.55it/s]


 41%|████▏

 45%|████▍     | 6153/13814 [11:27<14:12,  8.99it/s]


 45%|████▍     | 6156/13814 [11:27<11:42, 10.91it/s]


 45%|████▍     | 6160/13814 [11:27<09:53, 12.90it/s]


 45%|████▍     | 6162/13814 [11:28<09:58, 12.79it/s]


 45%|████▍     | 6164/13814 [11:28<12:10, 10.48it/s]


 45%|████▍     | 6166/13814 [11:28<10:42, 11.91it/s]


 45%|████▍     | 6168/13814 [11:28<10:47, 11.80it/s]


 45%|████▍     | 6170/13814 [11:28<09:29, 13.42it/s]


 45%|████▍     | 6174/13814 [11:28<07:43, 16.49it/s]


 45%|████▍     | 6178/13814 [11:29<06:47, 18.75it/s]


 45%|████▍     | 6181/13814 [11:29<06:14, 20.38it/s]


 45%|████▍     | 6184/13814 [11:29<06:11, 20.54it/s]


 45%|████▍     | 6187/13814 [11:29<05:43, 22.21it/s]


 45%|████▍     | 6190/13814 [11:29<06:16, 20.26it/s]


 45%|████▍     | 6193/13814 [11:29<05:43, 22.16it/s]


 45%|████▍     | 6196/13814 [11:30<08:22, 15.15it/s]


 45%|████▍     | 6198/13814 [11:30<11:24, 11.13it/s]


 45%|████▍     | 6201/13814 [11:30<09:34, 13.25it/s]


 45%|████▍

 48%|████▊     | 6618/13814 [12:19<13:09,  9.12it/s]


 48%|████▊     | 6620/13814 [12:19<11:14, 10.66it/s]


 48%|████▊     | 6622/13814 [12:20<12:25,  9.65it/s]


 48%|████▊     | 6624/13814 [12:20<11:38, 10.30it/s]


 48%|████▊     | 6626/13814 [12:20<15:43,  7.62it/s]


 48%|████▊     | 6627/13814 [12:20<18:30,  6.47it/s]


 48%|████▊     | 6628/13814 [12:21<21:44,  5.51it/s]


 48%|████▊     | 6629/13814 [12:21<22:38,  5.29it/s]


 48%|████▊     | 6631/13814 [12:21<19:09,  6.25it/s]


 48%|████▊     | 6632/13814 [12:21<18:12,  6.57it/s]


 48%|████▊     | 6634/13814 [12:21<15:20,  7.80it/s]


 48%|████▊     | 6636/13814 [12:21<12:50,  9.32it/s]


 48%|████▊     | 6638/13814 [12:22<11:58,  9.98it/s]


 48%|████▊     | 6640/13814 [12:22<11:30, 10.39it/s]


 48%|████▊     | 6642/13814 [12:22<10:47, 11.07it/s]


 48%|████▊     | 6644/13814 [12:22<10:48, 11.06it/s]


 48%|████▊     | 6646/13814 [12:22<13:11,  9.06it/s]


 48%|████▊     | 6648/13814 [12:23<11:54, 10.03it/s]


 48%|████▊

 51%|█████▏    | 7087/13814 [13:14<17:05,  6.56it/s]


 51%|█████▏    | 7088/13814 [13:14<17:02,  6.58it/s]


 51%|█████▏    | 7090/13814 [13:14<15:24,  7.27it/s]


 51%|█████▏    | 7093/13814 [13:14<12:56,  8.65it/s]


 51%|█████▏    | 7095/13814 [13:14<10:56, 10.23it/s]


 51%|█████▏    | 7097/13814 [13:15<14:29,  7.72it/s]


 51%|█████▏    | 7099/13814 [13:15<15:14,  7.34it/s]


 51%|█████▏    | 7100/13814 [13:15<20:06,  5.56it/s]


 51%|█████▏    | 7101/13814 [13:16<19:31,  5.73it/s]


 51%|█████▏    | 7102/13814 [13:16<17:13,  6.49it/s]


 51%|█████▏    | 7103/13814 [13:16<20:03,  5.57it/s]


 51%|█████▏    | 7105/13814 [13:16<16:55,  6.60it/s]


 51%|█████▏    | 7106/13814 [13:16<18:23,  6.08it/s]


 51%|█████▏    | 7107/13814 [13:16<19:22,  5.77it/s]


 51%|█████▏    | 7108/13814 [13:17<16:59,  6.58it/s]


 51%|█████▏    | 7109/13814 [13:17<15:59,  6.99it/s]


 51%|█████▏    | 7110/13814 [13:17<16:42,  6.69it/s]


 51%|█████▏    | 7111/13814 [13:17<29:01,  3.85it/s]


 51%|█████

 54%|█████▍    | 7517/13814 [14:08<13:58,  7.51it/s]


 54%|█████▍    | 7518/13814 [14:09<13:45,  7.62it/s]


 54%|█████▍    | 7520/13814 [14:09<13:03,  8.04it/s]


 54%|█████▍    | 7521/13814 [14:09<14:19,  7.32it/s]


 54%|█████▍    | 7523/13814 [14:09<12:15,  8.55it/s]


 54%|█████▍    | 7526/13814 [14:09<10:23, 10.08it/s]


 55%|█████▍    | 7529/13814 [14:09<08:24, 12.45it/s]


 55%|█████▍    | 7532/13814 [14:10<07:25, 14.09it/s]


 55%|█████▍    | 7535/13814 [14:10<06:26, 16.27it/s]


 55%|█████▍    | 7538/13814 [14:10<05:40, 18.43it/s]


 55%|█████▍    | 7541/13814 [14:10<06:38, 15.75it/s]


 55%|█████▍    | 7543/13814 [14:10<06:41, 15.63it/s]


 55%|█████▍    | 7545/13814 [14:10<07:15, 14.38it/s]


 55%|█████▍    | 7547/13814 [14:11<08:53, 11.75it/s]


 55%|█████▍    | 7549/13814 [14:11<09:11, 11.37it/s]


 55%|█████▍    | 7551/13814 [14:11<09:20, 11.17it/s]


 55%|█████▍    | 7553/13814 [14:11<13:01,  8.02it/s]


 55%|█████▍    | 7555/13814 [14:12<12:35,  8.29it/s]


 55%|█████

 58%|█████▊    | 7945/13814 [15:01<12:25,  7.87it/s]


 58%|█████▊    | 7946/13814 [15:01<14:18,  6.84it/s]


 58%|█████▊    | 7947/13814 [15:01<19:42,  4.96it/s]


 58%|█████▊    | 7948/13814 [15:02<17:21,  5.63it/s]


 58%|█████▊    | 7949/13814 [15:02<20:52,  4.68it/s]


 58%|█████▊    | 7950/13814 [15:02<22:47,  4.29it/s]


 58%|█████▊    | 7952/13814 [15:02<18:17,  5.34it/s]


 58%|█████▊    | 7955/13814 [15:02<14:08,  6.90it/s]


 58%|█████▊    | 7957/13814 [15:03<13:11,  7.40it/s]


 58%|█████▊    | 7959/13814 [15:03<11:55,  8.18it/s]


 58%|█████▊    | 7961/13814 [15:03<10:20,  9.44it/s]


 58%|█████▊    | 7963/13814 [15:03<10:50,  9.00it/s]


 58%|█████▊    | 7965/13814 [15:04<14:21,  6.79it/s]


 58%|█████▊    | 7966/13814 [15:04<13:38,  7.15it/s]


 58%|█████▊    | 7967/13814 [15:04<14:51,  6.56it/s]


 58%|█████▊    | 7968/13814 [15:04<15:27,  6.30it/s]


 58%|█████▊    | 7970/13814 [15:04<14:10,  6.87it/s]


 58%|█████▊    | 7971/13814 [15:05<17:10,  5.67it/s]


 58%|█████

 61%|██████    | 8384/13814 [15:56<07:45, 11.67it/s]


 61%|██████    | 8386/13814 [15:56<10:23,  8.71it/s]


 61%|██████    | 8388/13814 [15:56<09:22,  9.65it/s]


 61%|██████    | 8390/13814 [15:56<08:28, 10.67it/s]


 61%|██████    | 8392/13814 [15:57<10:05,  8.96it/s]


 61%|██████    | 8394/13814 [15:57<08:59, 10.05it/s]


 61%|██████    | 8397/13814 [15:57<08:04, 11.18it/s]


 61%|██████    | 8399/13814 [15:57<09:27,  9.55it/s]


 61%|██████    | 8402/13814 [15:57<07:38, 11.81it/s]


 61%|██████    | 8404/13814 [15:58<07:17, 12.36it/s]


 61%|██████    | 8406/13814 [15:58<08:27, 10.66it/s]


 61%|██████    | 8409/13814 [15:58<06:55, 13.01it/s]


 61%|██████    | 8411/13814 [15:58<07:14, 12.44it/s]


 61%|██████    | 8414/13814 [15:58<07:35, 11.86it/s]


 61%|██████    | 8416/13814 [15:59<08:17, 10.84it/s]


 61%|██████    | 8418/13814 [15:59<10:22,  8.67it/s]


 61%|██████    | 8420/13814 [15:59<10:45,  8.36it/s]


 61%|██████    | 8422/13814 [15:59<09:14,  9.72it/s]


 61%|█████

 64%|██████▍   | 8851/13814 [16:47<10:30,  7.87it/s]


 64%|██████▍   | 8852/13814 [16:47<12:36,  6.56it/s]


 64%|██████▍   | 8854/13814 [16:48<11:54,  6.94it/s]


 64%|██████▍   | 8855/13814 [16:48<14:22,  5.75it/s]


 64%|██████▍   | 8856/13814 [16:48<15:04,  5.48it/s]


 64%|██████▍   | 8858/13814 [16:48<11:58,  6.90it/s]


 64%|██████▍   | 8859/13814 [16:48<12:20,  6.69it/s]


 64%|██████▍   | 8863/13814 [16:49<09:33,  8.63it/s]


 64%|██████▍   | 8867/13814 [16:49<07:39, 10.78it/s]


 64%|██████▍   | 8869/13814 [16:49<07:30, 10.99it/s]


 64%|██████▍   | 8871/13814 [16:49<10:54,  7.55it/s]


 64%|██████▍   | 8873/13814 [16:50<13:12,  6.24it/s]


 64%|██████▍   | 8875/13814 [16:50<11:15,  7.31it/s]


 64%|██████▍   | 8877/13814 [16:50<10:13,  8.05it/s]


 64%|██████▍   | 8879/13814 [16:50<09:34,  8.58it/s]


 64%|██████▍   | 8881/13814 [16:51<09:35,  8.57it/s]


 64%|██████▍   | 8883/13814 [16:51<09:15,  8.88it/s]


 64%|██████▍   | 8885/13814 [16:51<08:24,  9.77it/s]


 64%|█████

 67%|██████▋   | 9281/13814 [17:41<13:15,  5.70it/s]


 67%|██████▋   | 9283/13814 [17:41<12:19,  6.13it/s]


 67%|██████▋   | 9285/13814 [17:42<10:00,  7.54it/s]


 67%|██████▋   | 9286/13814 [17:42<12:25,  6.07it/s]


 67%|██████▋   | 9287/13814 [17:42<13:02,  5.79it/s]


 67%|██████▋   | 9288/13814 [17:42<12:52,  5.86it/s]


 67%|██████▋   | 9290/13814 [17:42<10:35,  7.12it/s]


 67%|██████▋   | 9291/13814 [17:42<11:06,  6.78it/s]


 67%|██████▋   | 9292/13814 [17:43<11:48,  6.38it/s]


 67%|██████▋   | 9293/13814 [17:43<11:43,  6.43it/s]


 67%|██████▋   | 9294/13814 [17:43<15:48,  4.76it/s]


 67%|██████▋   | 9295/13814 [17:43<16:00,  4.71it/s]


 67%|██████▋   | 9297/13814 [17:43<12:30,  6.02it/s]


 67%|██████▋   | 9299/13814 [17:44<11:23,  6.60it/s]


 67%|██████▋   | 9302/13814 [17:44<09:03,  8.31it/s]


 67%|██████▋   | 9304/13814 [17:44<07:53,  9.52it/s]


 67%|██████▋   | 9306/13814 [17:44<06:42, 11.20it/s]


 67%|██████▋   | 9308/13814 [17:44<06:19, 11.89it/s]


 67%|█████

 70%|███████   | 9708/13814 [18:35<08:01,  8.53it/s]


 70%|███████   | 9709/13814 [18:35<07:46,  8.80it/s]


 70%|███████   | 9710/13814 [18:35<08:13,  8.32it/s]


 70%|███████   | 9712/13814 [18:35<07:46,  8.79it/s]


 70%|███████   | 9713/13814 [18:35<07:31,  9.08it/s]


 70%|███████   | 9715/13814 [18:35<06:46, 10.09it/s]


 70%|███████   | 9717/13814 [18:35<05:49, 11.72it/s]


 70%|███████   | 9719/13814 [18:36<08:54,  7.67it/s]


 70%|███████   | 9721/13814 [18:36<08:17,  8.23it/s]


 70%|███████   | 9723/13814 [18:36<07:33,  9.02it/s]


 70%|███████   | 9725/13814 [18:36<07:51,  8.67it/s]


 70%|███████   | 9727/13814 [18:37<06:39, 10.23it/s]


 70%|███████   | 9730/13814 [18:37<06:18, 10.79it/s]


 70%|███████   | 9732/13814 [18:37<06:39, 10.21it/s]


 70%|███████   | 9734/13814 [18:37<06:37, 10.27it/s]


 70%|███████   | 9737/13814 [18:38<06:54,  9.84it/s]


 71%|███████   | 9739/13814 [18:38<08:44,  7.77it/s]


 71%|███████   | 9740/13814 [18:38<08:34,  7.92it/s]


 71%|█████

 74%|███████▎  | 10173/13814 [19:31<11:42,  5.18it/s]


 74%|███████▎  | 10174/13814 [19:31<12:15,  4.95it/s]


 74%|███████▎  | 10177/13814 [19:32<10:17,  5.89it/s]


 74%|███████▎  | 10178/13814 [19:32<11:17,  5.37it/s]


 74%|███████▎  | 10179/13814 [19:32<14:19,  4.23it/s]


 74%|███████▎  | 10180/13814 [19:33<15:24,  3.93it/s]


 74%|███████▎  | 10181/13814 [19:33<18:02,  3.35it/s]


 74%|███████▎  | 10182/13814 [19:33<18:02,  3.36it/s]


 74%|███████▎  | 10183/13814 [19:34<18:20,  3.30it/s]


 74%|███████▎  | 10184/13814 [19:34<16:02,  3.77it/s]


 74%|███████▎  | 10185/13814 [19:34<14:00,  4.32it/s]


 74%|███████▎  | 10186/13814 [19:34<12:15,  4.93it/s]


 74%|███████▎  | 10187/13814 [19:34<11:19,  5.34it/s]


 74%|███████▍  | 10188/13814 [19:34<11:31,  5.24it/s]


 74%|███████▍  | 10189/13814 [19:35<11:24,  5.30it/s]


 74%|███████▍  | 10190/13814 [19:35<11:10,  5.41it/s]


 74%|███████▍  | 10191/13814 [19:35<09:49,  6.14it/s]


 74%|███████▍  | 10193/13814 [19:35<08:43,  6.92

 77%|███████▋  | 10575/13814 [20:25<06:19,  8.53it/s]


 77%|███████▋  | 10577/13814 [20:25<05:46,  9.33it/s]


 77%|███████▋  | 10579/13814 [20:25<05:37,  9.59it/s]


 77%|███████▋  | 10582/13814 [20:25<04:30, 11.93it/s]


 77%|███████▋  | 10584/13814 [20:25<04:03, 13.24it/s]


 77%|███████▋  | 10586/13814 [20:26<04:21, 12.35it/s]


 77%|███████▋  | 10588/13814 [20:26<04:55, 10.92it/s]


 77%|███████▋  | 10590/13814 [20:26<06:47,  7.91it/s]


 77%|███████▋  | 10592/13814 [20:26<06:26,  8.34it/s]


 77%|███████▋  | 10594/13814 [20:27<06:31,  8.23it/s]


 77%|███████▋  | 10596/13814 [20:27<06:08,  8.72it/s]


 77%|███████▋  | 10597/13814 [20:27<05:55,  9.04it/s]


 77%|███████▋  | 10598/13814 [20:27<06:27,  8.29it/s]


 77%|███████▋  | 10600/13814 [20:27<06:31,  8.21it/s]


 77%|███████▋  | 10601/13814 [20:28<07:10,  7.46it/s]


 77%|███████▋  | 10603/13814 [20:28<07:28,  7.16it/s]


 77%|███████▋  | 10604/13814 [20:28<08:43,  6.14it/s]


 77%|███████▋  | 10606/13814 [20:28<07:22,  7.25

 80%|███████▉  | 10991/13814 [21:18<05:14,  8.98it/s]


 80%|███████▉  | 10993/13814 [21:18<05:31,  8.50it/s]


 80%|███████▉  | 10994/13814 [21:18<05:40,  8.28it/s]


 80%|███████▉  | 10995/13814 [21:19<05:33,  8.45it/s]


 80%|███████▉  | 10996/13814 [21:19<05:53,  7.97it/s]


 80%|███████▉  | 10997/13814 [21:19<06:40,  7.04it/s]


 80%|███████▉  | 10998/13814 [21:19<07:06,  6.61it/s]


 80%|███████▉  | 11001/13814 [21:19<05:44,  8.17it/s]


 80%|███████▉  | 11003/13814 [21:19<05:18,  8.81it/s]


 80%|███████▉  | 11005/13814 [21:20<06:20,  7.38it/s]


 80%|███████▉  | 11006/13814 [21:20<07:55,  5.91it/s]


 80%|███████▉  | 11007/13814 [21:20<10:23,  4.50it/s]


 80%|███████▉  | 11008/13814 [21:21<08:56,  5.23it/s]


 80%|███████▉  | 11010/13814 [21:21<07:38,  6.11it/s]


 80%|███████▉  | 11011/13814 [21:21<08:20,  5.60it/s]


 80%|███████▉  | 11012/13814 [21:21<07:29,  6.23it/s]


 80%|███████▉  | 11013/13814 [21:21<08:10,  5.71it/s]


 80%|███████▉  | 11014/13814 [21:21<07:14,  6.44

 83%|████████▎ | 11426/13814 [22:08<03:57, 10.05it/s]


 83%|████████▎ | 11428/13814 [22:09<04:46,  8.34it/s]


 83%|████████▎ | 11430/13814 [22:09<04:10,  9.53it/s]


 83%|████████▎ | 11432/13814 [22:09<05:13,  7.59it/s]


 83%|████████▎ | 11434/13814 [22:09<04:47,  8.28it/s]


 83%|████████▎ | 11436/13814 [22:10<05:23,  7.34it/s]


 83%|████████▎ | 11438/13814 [22:10<04:31,  8.76it/s]


 83%|████████▎ | 11440/13814 [22:10<03:53, 10.18it/s]


 83%|████████▎ | 11442/13814 [22:10<03:28, 11.36it/s]


 83%|████████▎ | 11444/13814 [22:10<03:59,  9.90it/s]


 83%|████████▎ | 11447/13814 [22:10<03:11, 12.38it/s]


 83%|████████▎ | 11450/13814 [22:11<02:51, 13.76it/s]


 83%|████████▎ | 11452/13814 [22:11<03:07, 12.60it/s]


 83%|████████▎ | 11454/13814 [22:11<04:23,  8.96it/s]


 83%|████████▎ | 11456/13814 [22:11<04:56,  7.96it/s]


 83%|████████▎ | 11458/13814 [22:12<05:58,  6.58it/s]


 83%|████████▎ | 11460/13814 [22:12<04:56,  7.95it/s]


 83%|████████▎ | 11462/13814 [22:12<05:17,  7.41

 86%|████████▌ | 11874/13814 [23:04<03:19,  9.71it/s]


 86%|████████▌ | 11876/13814 [23:04<03:08, 10.30it/s]


 86%|████████▌ | 11878/13814 [23:04<03:15,  9.91it/s]


 86%|████████▌ | 11880/13814 [23:04<03:33,  9.04it/s]


 86%|████████▌ | 11882/13814 [23:05<03:56,  8.18it/s]


 86%|████████▌ | 11884/13814 [23:05<04:26,  7.25it/s]


 86%|████████▌ | 11885/13814 [23:05<04:16,  7.53it/s]


 86%|████████▌ | 11886/13814 [23:05<06:05,  5.27it/s]


 86%|████████▌ | 11887/13814 [23:06<05:39,  5.67it/s]


 86%|████████▌ | 11888/13814 [23:06<06:13,  5.16it/s]


 86%|████████▌ | 11889/13814 [23:06<05:53,  5.45it/s]


 86%|████████▌ | 11890/13814 [23:06<05:14,  6.11it/s]


 86%|████████▌ | 11891/13814 [23:06<06:28,  4.95it/s]


 86%|████████▌ | 11892/13814 [23:07<06:59,  4.58it/s]


 86%|████████▌ | 11894/13814 [23:07<07:03,  4.53it/s]


 86%|████████▌ | 11895/13814 [23:07<08:31,  3.75it/s]


 86%|████████▌ | 11896/13814 [23:08<07:57,  4.02it/s]


 86%|████████▌ | 11897/13814 [23:08<07:38,  4.18

 89%|████████▊ | 12257/13814 [23:56<04:02,  6.42it/s]


 89%|████████▊ | 12258/13814 [23:56<04:14,  6.11it/s]


 89%|████████▊ | 12259/13814 [23:56<03:50,  6.76it/s]


 89%|████████▉ | 12260/13814 [23:57<04:11,  6.19it/s]


 89%|████████▉ | 12261/13814 [23:57<04:37,  5.59it/s]


 89%|████████▉ | 12263/13814 [23:57<03:53,  6.65it/s]


 89%|████████▉ | 12264/13814 [23:57<04:07,  6.27it/s]


 89%|████████▉ | 12266/13814 [23:57<03:21,  7.69it/s]


 89%|████████▉ | 12267/13814 [23:57<03:37,  7.11it/s]


 89%|████████▉ | 12268/13814 [23:58<03:39,  7.04it/s]


 89%|████████▉ | 12269/13814 [23:58<03:52,  6.65it/s]


 89%|████████▉ | 12270/13814 [23:58<04:31,  5.68it/s]


 89%|████████▉ | 12271/13814 [23:58<04:26,  5.79it/s]


 89%|████████▉ | 12274/13814 [23:58<03:29,  7.33it/s]


 89%|████████▉ | 12276/13814 [23:59<03:43,  6.88it/s]


 89%|████████▉ | 12277/13814 [23:59<06:10,  4.15it/s]


 89%|████████▉ | 12278/13814 [23:59<05:47,  4.42it/s]


 89%|████████▉ | 12279/13814 [23:59<04:58,  5.14

 92%|█████████▏| 12711/13814 [24:51<03:25,  5.38it/s]


 92%|█████████▏| 12713/13814 [24:51<02:56,  6.23it/s]


 92%|█████████▏| 12714/13814 [24:51<03:03,  5.99it/s]


 92%|█████████▏| 12715/13814 [24:52<02:49,  6.48it/s]


 92%|█████████▏| 12716/13814 [24:52<03:20,  5.49it/s]


 92%|█████████▏| 12718/13814 [24:52<02:59,  6.10it/s]


 92%|█████████▏| 12719/13814 [24:52<03:14,  5.63it/s]


 92%|█████████▏| 12720/13814 [24:52<03:09,  5.77it/s]


 92%|█████████▏| 12722/13814 [24:53<02:43,  6.70it/s]


 92%|█████████▏| 12723/13814 [24:53<03:11,  5.69it/s]


 92%|█████████▏| 12725/13814 [24:53<02:46,  6.54it/s]


 92%|█████████▏| 12726/13814 [24:53<03:04,  5.90it/s]


 92%|█████████▏| 12727/13814 [24:53<03:18,  5.48it/s]


 92%|█████████▏| 12728/13814 [24:54<03:16,  5.52it/s]


 92%|█████████▏| 12729/13814 [24:54<04:37,  3.91it/s]


 92%|█████████▏| 12730/13814 [24:54<04:12,  4.29it/s]


 92%|█████████▏| 12732/13814 [24:55<03:32,  5.09it/s]


 92%|█████████▏| 12733/13814 [24:55<04:45,  3.79

 95%|█████████▌| 13155/13814 [25:44<00:32, 20.58it/s]


 95%|█████████▌| 13158/13814 [25:44<00:40, 16.16it/s]


 95%|█████████▌| 13161/13814 [25:44<00:56, 11.49it/s]


 95%|█████████▌| 13163/13814 [25:44<00:49, 13.08it/s]


 95%|█████████▌| 13165/13814 [25:45<00:57, 11.23it/s]


 95%|█████████▌| 13167/13814 [25:45<01:14,  8.74it/s]


 95%|█████████▌| 13169/13814 [25:45<01:18,  8.27it/s]


 95%|█████████▌| 13171/13814 [25:46<01:17,  8.33it/s]


 95%|█████████▌| 13173/13814 [25:46<01:16,  8.40it/s]


 95%|█████████▌| 13175/13814 [25:46<01:30,  7.09it/s]


 95%|█████████▌| 13177/13814 [25:46<01:23,  7.61it/s]


 95%|█████████▌| 13178/13814 [25:47<01:29,  7.14it/s]


 95%|█████████▌| 13179/13814 [25:47<01:40,  6.32it/s]


 95%|█████████▌| 13180/13814 [25:47<01:43,  6.15it/s]


 95%|█████████▌| 13181/13814 [25:47<02:31,  4.19it/s]


 95%|█████████▌| 13182/13814 [25:47<02:09,  4.87it/s]


 95%|█████████▌| 13184/13814 [25:48<01:48,  5.83it/s]


 95%|█████████▌| 13185/13814 [25:48<01:41,  6.20

 98%|█████████▊| 13565/13814 [26:39<00:24, 10.21it/s]


 98%|█████████▊| 13567/13814 [26:39<00:29,  8.31it/s]


 98%|█████████▊| 13569/13814 [26:40<00:46,  5.26it/s]


 98%|█████████▊| 13570/13814 [26:40<00:57,  4.28it/s]


 98%|█████████▊| 13571/13814 [26:40<01:02,  3.91it/s]


 98%|█████████▊| 13572/13814 [26:41<01:12,  3.33it/s]


 98%|█████████▊| 13573/13814 [26:41<01:11,  3.36it/s]


 98%|█████████▊| 13574/13814 [26:41<01:20,  2.99it/s]


 98%|█████████▊| 13575/13814 [26:42<01:11,  3.32it/s]


 98%|█████████▊| 13576/13814 [26:42<01:04,  3.71it/s]


 98%|█████████▊| 13577/13814 [26:42<01:04,  3.66it/s]


 98%|█████████▊| 13578/13814 [26:42<01:04,  3.64it/s]


 98%|█████████▊| 13580/13814 [26:43<00:58,  4.03it/s]


 98%|█████████▊| 13581/13814 [26:43<00:54,  4.25it/s]


 98%|█████████▊| 13582/13814 [26:43<00:47,  4.92it/s]


 98%|█████████▊| 13583/13814 [26:43<00:42,  5.41it/s]


 98%|█████████▊| 13584/13814 [26:44<00:45,  5.08it/s]


 98%|█████████▊| 13585/13814 [26:44<00:42,  5.39

0.1284972052034892
---------- Started Epoch 3 -----------





  0%|          | 4/13814 [00:00<19:31, 11.78it/s]


  0%|          | 5/13814 [00:00<22:34, 10.20it/s]


  0%|          | 6/13814 [00:00<23:46,  9.68it/s]


  0%|          | 9/13814 [00:00<19:00, 12.10it/s]


  0%|          | 12/13814 [00:00<18:01, 12.77it/s]


  0%|          | 14/13814 [00:01<22:31, 10.21it/s]


  0%|          | 16/13814 [00:01<34:58,  6.58it/s]


  0%|          | 17/13814 [00:01<31:37,  7.27it/s]


  0%|          | 18/13814 [00:02<57:09,  4.02it/s]


  0%|          | 20/13814 [00:02<43:44,  5.25it/s]


  0%|          | 22/13814 [00:02<35:07,  6.54it/s]


  0%|          | 25/13814 [00:02<27:16,  8.42it/s]


  0%|          | 29/13814 [00:02<21:06, 10.88it/s]


  0%|          | 33/13814 [00:03<17:11, 13.36it/s]


  0%|          | 36/13814 [00:03<16:42, 13.74it/s]


  0%|          | 39/13814 [00:03<18:04, 12.70it/s]


  0%|          | 41/13814 [00:03<16:45, 13.70it/s]


  0%|          | 43/13814 [00:04<25:01,  9.17it/s]


  0%|          | 45/13814 [00:04<30:10,  7.61it

  5%|▍         | 639/13814 [00:50<41:43,  5.26it/s]


  5%|▍         | 641/13814 [00:51<37:54,  5.79it/s]


  5%|▍         | 643/13814 [00:51<31:05,  7.06it/s]


  5%|▍         | 647/13814 [00:51<24:30,  8.95it/s]


  5%|▍         | 649/13814 [00:51<22:47,  9.63it/s]


  5%|▍         | 652/13814 [00:51<19:38, 11.17it/s]


  5%|▍         | 654/13814 [00:51<18:22, 11.94it/s]


  5%|▍         | 657/13814 [00:52<16:21, 13.40it/s]


  5%|▍         | 661/13814 [00:52<13:31, 16.20it/s]


  5%|▍         | 664/13814 [00:52<14:18, 15.32it/s]


  5%|▍         | 666/13814 [00:52<17:58, 12.19it/s]


  5%|▍         | 668/13814 [00:52<16:58, 12.91it/s]


  5%|▍         | 670/13814 [00:53<19:39, 11.14it/s]


  5%|▍         | 673/13814 [00:53<18:29, 11.85it/s]


  5%|▍         | 675/13814 [00:53<18:44, 11.68it/s]


  5%|▍         | 677/13814 [00:53<17:15, 12.69it/s]


  5%|▍         | 679/13814 [00:53<22:25,  9.76it/s]


  5%|▍         | 681/13814 [00:54<25:00,  8.75it/s]


  5%|▍         | 683/13814 [

  9%|▉         | 1212/13814 [01:42<25:05,  8.37it/s]


  9%|▉         | 1214/13814 [01:43<26:05,  8.05it/s]


  9%|▉         | 1215/13814 [01:43<33:45,  6.22it/s]


  9%|▉         | 1217/13814 [01:43<31:20,  6.70it/s]


  9%|▉         | 1218/13814 [01:43<29:07,  7.21it/s]


  9%|▉         | 1220/13814 [01:43<24:12,  8.67it/s]


  9%|▉         | 1222/13814 [01:43<21:04,  9.96it/s]


  9%|▉         | 1224/13814 [01:44<28:36,  7.33it/s]


  9%|▉         | 1225/13814 [01:44<30:09,  6.96it/s]


  9%|▉         | 1226/13814 [01:44<28:22,  7.39it/s]


  9%|▉         | 1227/13814 [01:44<28:59,  7.23it/s]


  9%|▉         | 1230/13814 [01:44<23:08,  9.06it/s]


  9%|▉         | 1232/13814 [01:45<27:16,  7.69it/s]


  9%|▉         | 1234/13814 [01:45<26:37,  7.87it/s]


  9%|▉         | 1236/13814 [01:45<23:59,  8.74it/s]


  9%|▉         | 1239/13814 [01:45<19:08, 10.94it/s]


  9%|▉         | 1241/13814 [01:46<19:34, 10.70it/s]


  9%|▉         | 1243/13814 [01:46<22:32,  9.30it/s]


  9%|▉    

 13%|█▎        | 1747/13814 [02:34<17:35, 11.43it/s]


 13%|█▎        | 1749/13814 [02:34<21:26,  9.38it/s]


 13%|█▎        | 1751/13814 [02:34<22:47,  8.82it/s]


 13%|█▎        | 1752/13814 [02:34<23:15,  8.64it/s]


 13%|█▎        | 1753/13814 [02:34<25:39,  7.83it/s]


 13%|█▎        | 1755/13814 [02:34<21:02,  9.56it/s]


 13%|█▎        | 1758/13814 [02:35<18:38, 10.78it/s]


 13%|█▎        | 1760/13814 [02:35<19:19, 10.39it/s]


 13%|█▎        | 1762/13814 [02:35<17:26, 11.52it/s]


 13%|█▎        | 1764/13814 [02:35<21:40,  9.26it/s]


 13%|█▎        | 1766/13814 [02:36<25:06,  8.00it/s]


 13%|█▎        | 1767/13814 [02:36<24:24,  8.23it/s]


 13%|█▎        | 1769/13814 [02:36<21:13,  9.46it/s]


 13%|█▎        | 1771/13814 [02:36<19:42, 10.19it/s]


 13%|█▎        | 1775/13814 [02:36<16:47, 11.95it/s]


 13%|█▎        | 1777/13814 [02:36<15:10, 13.22it/s]


 13%|█▎        | 1779/13814 [02:37<19:05, 10.50it/s]


 13%|█▎        | 1781/13814 [02:37<17:57, 11.17it/s]


 13%|█▎   

 16%|█▌        | 2209/13814 [03:26<39:22,  4.91it/s]


 16%|█▌        | 2210/13814 [03:26<35:41,  5.42it/s]


 16%|█▌        | 2212/13814 [03:26<28:11,  6.86it/s]


 16%|█▌        | 2213/13814 [03:26<26:50,  7.20it/s]


 16%|█▌        | 2215/13814 [03:26<25:21,  7.62it/s]


 16%|█▌        | 2216/13814 [03:27<49:09,  3.93it/s]


 16%|█▌        | 2217/13814 [03:27<43:08,  4.48it/s]


 16%|█▌        | 2218/13814 [03:27<37:49,  5.11it/s]


 16%|█▌        | 2222/13814 [03:27<28:18,  6.82it/s]


 16%|█▌        | 2224/13814 [03:27<26:34,  7.27it/s]


 16%|█▌        | 2226/13814 [03:28<23:51,  8.10it/s]


 16%|█▌        | 2228/13814 [03:28<22:01,  8.77it/s]


 16%|█▌        | 2230/13814 [03:28<19:16, 10.02it/s]


 16%|█▌        | 2232/13814 [03:28<17:42, 10.90it/s]


 16%|█▌        | 2234/13814 [03:28<19:08, 10.08it/s]


 16%|█▌        | 2236/13814 [03:28<20:50,  9.26it/s]


 16%|█▌        | 2238/13814 [03:29<22:36,  8.53it/s]


 16%|█▌        | 2239/13814 [03:29<25:17,  7.63it/s]


 16%|█▌   

 19%|█▉        | 2639/13814 [04:18<24:21,  7.65it/s]


 19%|█▉        | 2641/13814 [04:18<21:20,  8.72it/s]


 19%|█▉        | 2642/13814 [04:18<22:29,  8.28it/s]


 19%|█▉        | 2643/13814 [04:18<25:35,  7.28it/s]


 19%|█▉        | 2644/13814 [04:19<35:24,  5.26it/s]


 19%|█▉        | 2645/13814 [04:19<52:23,  3.55it/s]


 19%|█▉        | 2646/13814 [04:19<46:22,  4.01it/s]


 19%|█▉        | 2647/13814 [04:20<40:59,  4.54it/s]


 19%|█▉        | 2649/13814 [04:20<34:57,  5.32it/s]


 19%|█▉        | 2650/13814 [04:20<30:52,  6.03it/s]


 19%|█▉        | 2652/13814 [04:20<25:08,  7.40it/s]


 19%|█▉        | 2653/13814 [04:20<23:51,  7.80it/s]


 19%|█▉        | 2655/13814 [04:20<22:04,  8.43it/s]


 19%|█▉        | 2658/13814 [04:21<22:41,  8.20it/s]


 19%|█▉        | 2659/13814 [04:21<23:39,  7.86it/s]


 19%|█▉        | 2660/13814 [04:21<37:10,  5.00it/s]


 19%|█▉        | 2661/13814 [04:21<32:47,  5.67it/s]


 19%|█▉        | 2663/13814 [04:22<31:05,  5.98it/s]


 19%|█▉   

 22%|██▏       | 3089/13814 [05:12<11:16, 15.86it/s]


 22%|██▏       | 3092/13814 [05:12<09:55, 18.00it/s]


 22%|██▏       | 3095/13814 [05:12<09:40, 18.48it/s]


 22%|██▏       | 3098/13814 [05:13<09:26, 18.93it/s]


 22%|██▏       | 3102/13814 [05:13<08:37, 20.69it/s]


 22%|██▏       | 3105/13814 [05:13<10:22, 17.21it/s]


 22%|██▏       | 3107/13814 [05:13<10:42, 16.68it/s]


 23%|██▎       | 3109/13814 [05:13<14:58, 11.91it/s]


 23%|██▎       | 3111/13814 [05:14<18:59,  9.39it/s]


 23%|██▎       | 3113/13814 [05:14<22:17,  8.00it/s]


 23%|██▎       | 3115/13814 [05:14<25:38,  6.95it/s]


 23%|██▎       | 3116/13814 [05:15<30:23,  5.87it/s]


 23%|██▎       | 3117/13814 [05:15<31:39,  5.63it/s]


 23%|██▎       | 3118/13814 [05:15<37:13,  4.79it/s]


 23%|██▎       | 3120/13814 [05:15<29:59,  5.94it/s]


 23%|██▎       | 3122/13814 [05:15<26:13,  6.80it/s]


 23%|██▎       | 3123/13814 [05:16<35:29,  5.02it/s]


 23%|██▎       | 3125/13814 [05:16<27:40,  6.44it/s]


 23%|██▎  

 25%|██▌       | 3508/13814 [06:05<15:57, 10.77it/s]


 25%|██▌       | 3510/13814 [06:05<17:16,  9.94it/s]


 25%|██▌       | 3512/13814 [06:05<21:06,  8.13it/s]


 25%|██▌       | 3513/13814 [06:05<20:37,  8.32it/s]


 25%|██▌       | 3514/13814 [06:05<22:31,  7.62it/s]


 25%|██▌       | 3517/13814 [06:06<18:19,  9.37it/s]


 25%|██▌       | 3519/13814 [06:06<23:29,  7.30it/s]


 25%|██▌       | 3520/13814 [06:06<37:31,  4.57it/s]


 25%|██▌       | 3521/13814 [06:06<32:25,  5.29it/s]


 25%|██▌       | 3522/13814 [06:07<28:33,  6.01it/s]


 26%|██▌       | 3524/13814 [06:07<23:35,  7.27it/s]


 26%|██▌       | 3525/13814 [06:07<25:53,  6.62it/s]


 26%|██▌       | 3526/13814 [06:07<29:26,  5.82it/s]


 26%|██▌       | 3527/13814 [06:07<30:49,  5.56it/s]


 26%|██▌       | 3528/13814 [06:07<29:07,  5.89it/s]


 26%|██▌       | 3529/13814 [06:08<26:03,  6.58it/s]


 26%|██▌       | 3530/13814 [06:08<30:07,  5.69it/s]


 26%|██▌       | 3532/13814 [06:08<25:18,  6.77it/s]


 26%|██▌  

 29%|██▊       | 3952/13814 [06:57<17:49,  9.22it/s]


 29%|██▊       | 3954/13814 [06:57<15:33, 10.56it/s]


 29%|██▊       | 3956/13814 [06:57<15:45, 10.42it/s]


 29%|██▊       | 3958/13814 [06:57<18:40,  8.80it/s]


 29%|██▊       | 3960/13814 [06:58<24:46,  6.63it/s]


 29%|██▊       | 3961/13814 [06:58<29:36,  5.55it/s]


 29%|██▊       | 3964/13814 [06:58<23:45,  6.91it/s]


 29%|██▊       | 3965/13814 [06:58<21:55,  7.49it/s]


 29%|██▊       | 3968/13814 [06:59<17:04,  9.61it/s]


 29%|██▊       | 3970/13814 [06:59<15:00, 10.93it/s]


 29%|██▉       | 3972/13814 [06:59<13:05, 12.53it/s]


 29%|██▉       | 3974/13814 [06:59<16:57,  9.67it/s]


 29%|██▉       | 3976/13814 [06:59<17:06,  9.59it/s]


 29%|██▉       | 3978/13814 [07:00<20:43,  7.91it/s]


 29%|██▉       | 3980/13814 [07:00<26:14,  6.25it/s]


 29%|██▉       | 3981/13814 [07:00<23:20,  7.02it/s]


 29%|██▉       | 3982/13814 [07:01<31:47,  5.15it/s]


 29%|██▉       | 3983/13814 [07:01<33:21,  4.91it/s]


 29%|██▉  

 32%|███▏      | 4433/13814 [07:51<13:08, 11.90it/s]


 32%|███▏      | 4435/13814 [07:51<12:36, 12.39it/s]


 32%|███▏      | 4437/13814 [07:51<16:06,  9.70it/s]


 32%|███▏      | 4439/13814 [07:51<15:34, 10.03it/s]


 32%|███▏      | 4441/13814 [07:51<14:16, 10.95it/s]


 32%|███▏      | 4443/13814 [07:52<14:58, 10.43it/s]


 32%|███▏      | 4445/13814 [07:52<14:10, 11.02it/s]


 32%|███▏      | 4447/13814 [07:52<18:04,  8.63it/s]


 32%|███▏      | 4449/13814 [07:53<30:08,  5.18it/s]


 32%|███▏      | 4450/13814 [07:53<30:29,  5.12it/s]


 32%|███▏      | 4451/13814 [07:53<30:20,  5.14it/s]


 32%|███▏      | 4452/13814 [07:53<34:28,  4.53it/s]


 32%|███▏      | 4453/13814 [07:54<37:37,  4.15it/s]


 32%|███▏      | 4454/13814 [07:54<32:41,  4.77it/s]


 32%|███▏      | 4456/13814 [07:54<27:17,  5.72it/s]


 32%|███▏      | 4459/13814 [07:54<21:52,  7.13it/s]


 32%|███▏      | 4461/13814 [07:54<19:47,  7.88it/s]


 32%|███▏      | 4463/13814 [07:55<16:41,  9.33it/s]


 32%|███▏ 

 35%|███▌      | 4881/13814 [08:45<19:22,  7.69it/s]


 35%|███▌      | 4883/13814 [08:46<16:21,  9.10it/s]


 35%|███▌      | 4885/13814 [08:46<13:43, 10.84it/s]


 35%|███▌      | 4887/13814 [08:46<14:27, 10.29it/s]


 35%|███▌      | 4889/13814 [08:46<18:17,  8.13it/s]


 35%|███▌      | 4891/13814 [08:46<17:57,  8.28it/s]


 35%|███▌      | 4894/13814 [08:47<15:24,  9.65it/s]


 35%|███▌      | 4896/13814 [08:47<14:48, 10.04it/s]


 35%|███▌      | 4898/13814 [08:47<13:11, 11.26it/s]


 35%|███▌      | 4902/13814 [08:47<10:24, 14.28it/s]


 36%|███▌      | 4905/13814 [08:47<10:23, 14.29it/s]


 36%|███▌      | 4908/13814 [08:47<09:39, 15.37it/s]


 36%|███▌      | 4910/13814 [08:48<16:13,  9.14it/s]


 36%|███▌      | 4912/13814 [08:48<15:56,  9.31it/s]


 36%|███▌      | 4914/13814 [08:48<16:51,  8.80it/s]


 36%|███▌      | 4916/13814 [08:49<19:03,  7.78it/s]


 36%|███▌      | 4917/13814 [08:49<17:47,  8.33it/s]


 36%|███▌      | 4918/13814 [08:49<21:01,  7.05it/s]


 36%|███▌ 

 39%|███▊      | 5347/13814 [09:37<29:17,  4.82it/s]


 39%|███▊      | 5349/13814 [09:37<23:23,  6.03it/s]


 39%|███▊      | 5352/13814 [09:38<20:52,  6.76it/s]


 39%|███▉      | 5353/13814 [09:38<19:09,  7.36it/s]


 39%|███▉      | 5356/13814 [09:38<15:57,  8.84it/s]


 39%|███▉      | 5358/13814 [09:38<14:23,  9.79it/s]


 39%|███▉      | 5360/13814 [09:38<14:30,  9.71it/s]


 39%|███▉      | 5362/13814 [09:39<13:02, 10.80it/s]


 39%|███▉      | 5365/13814 [09:39<10:45, 13.09it/s]


 39%|███▉      | 5367/13814 [09:39<10:41, 13.17it/s]


 39%|███▉      | 5369/13814 [09:39<09:54, 14.20it/s]


 39%|███▉      | 5371/13814 [09:39<10:40, 13.19it/s]


 39%|███▉      | 5373/13814 [09:39<13:34, 10.37it/s]


 39%|███▉      | 5375/13814 [09:40<14:37,  9.62it/s]


 39%|███▉      | 5377/13814 [09:40<14:48,  9.49it/s]


 39%|███▉      | 5379/13814 [09:40<15:44,  8.93it/s]


 39%|███▉      | 5381/13814 [09:40<15:57,  8.81it/s]


 39%|███▉      | 5382/13814 [09:41<18:26,  7.62it/s]


 39%|███▉ 

 42%|████▏     | 5815/13814 [10:32<18:40,  7.14it/s]


 42%|████▏     | 5817/13814 [10:32<15:56,  8.36it/s]


 42%|████▏     | 5819/13814 [10:32<14:10,  9.40it/s]


 42%|████▏     | 5821/13814 [10:33<14:14,  9.36it/s]


 42%|████▏     | 5823/13814 [10:33<13:42,  9.72it/s]


 42%|████▏     | 5825/13814 [10:33<12:13, 10.89it/s]


 42%|████▏     | 5827/13814 [10:33<15:27,  8.61it/s]


 42%|████▏     | 5829/13814 [10:33<14:26,  9.22it/s]


 42%|████▏     | 5831/13814 [10:34<14:59,  8.87it/s]


 42%|████▏     | 5832/13814 [10:34<17:01,  7.81it/s]


 42%|████▏     | 5833/13814 [10:34<19:28,  6.83it/s]


 42%|████▏     | 5834/13814 [10:34<20:02,  6.63it/s]


 42%|████▏     | 5836/13814 [10:35<21:08,  6.29it/s]


 42%|████▏     | 5838/13814 [10:35<18:33,  7.17it/s]


 42%|████▏     | 5840/13814 [10:35<18:59,  7.00it/s]


 42%|████▏     | 5842/13814 [10:35<20:30,  6.48it/s]


 42%|████▏     | 5846/13814 [10:36<15:50,  8.38it/s]


 42%|████▏     | 5849/13814 [10:36<13:12, 10.05it/s]


 42%|████▏

 45%|████▌     | 6275/13814 [11:26<21:14,  5.91it/s]


 45%|████▌     | 6277/13814 [11:26<17:03,  7.36it/s]


 45%|████▌     | 6280/13814 [11:26<16:18,  7.70it/s]


 45%|████▌     | 6281/13814 [11:26<15:17,  8.21it/s]


 45%|████▌     | 6282/13814 [11:26<15:26,  8.13it/s]


 45%|████▌     | 6284/13814 [11:27<16:59,  7.39it/s]


 46%|████▌     | 6286/13814 [11:27<14:31,  8.64it/s]


 46%|████▌     | 6289/13814 [11:27<11:54, 10.53it/s]


 46%|████▌     | 6293/13814 [11:27<09:40, 12.96it/s]


 46%|████▌     | 6295/13814 [11:27<11:10, 11.21it/s]


 46%|████▌     | 6297/13814 [11:28<16:49,  7.45it/s]


 46%|████▌     | 6299/13814 [11:28<17:30,  7.15it/s]


 46%|████▌     | 6301/13814 [11:28<15:49,  7.91it/s]


 46%|████▌     | 6303/13814 [11:29<16:17,  7.68it/s]


 46%|████▌     | 6305/13814 [11:29<13:45,  9.10it/s]


 46%|████▌     | 6307/13814 [11:29<14:52,  8.41it/s]


 46%|████▌     | 6309/13814 [11:29<14:56,  8.37it/s]


 46%|████▌     | 6310/13814 [11:29<20:39,  6.05it/s]


 46%|████▌

 49%|████▊     | 6729/13814 [12:22<15:47,  7.48it/s]


 49%|████▊     | 6731/13814 [12:22<13:56,  8.47it/s]


 49%|████▊     | 6734/13814 [12:22<12:02,  9.80it/s]


 49%|████▉     | 6736/13814 [12:23<12:14,  9.63it/s]


 49%|████▉     | 6738/13814 [12:23<13:56,  8.46it/s]


 49%|████▉     | 6740/13814 [12:23<12:14,  9.64it/s]


 49%|████▉     | 6742/13814 [12:23<13:25,  8.77it/s]


 49%|████▉     | 6744/13814 [12:24<12:39,  9.31it/s]


 49%|████▉     | 6746/13814 [12:24<14:17,  8.24it/s]


 49%|████▉     | 6747/13814 [12:24<14:27,  8.15it/s]


 49%|████▉     | 6748/13814 [12:24<20:07,  5.85it/s]


 49%|████▉     | 6749/13814 [12:25<23:50,  4.94it/s]


 49%|████▉     | 6750/13814 [12:25<30:05,  3.91it/s]


 49%|████▉     | 6751/13814 [12:25<27:40,  4.25it/s]


 49%|████▉     | 6753/13814 [12:25<23:25,  5.02it/s]


 49%|████▉     | 6754/13814 [12:26<22:00,  5.35it/s]


 49%|████▉     | 6756/13814 [12:26<17:26,  6.75it/s]


 49%|████▉     | 6758/13814 [12:26<15:41,  7.49it/s]


 49%|████▉

 52%|█████▏    | 7224/13814 [13:16<17:19,  6.34it/s]


 52%|█████▏    | 7226/13814 [13:16<14:45,  7.44it/s]


 52%|█████▏    | 7227/13814 [13:16<13:43,  8.00it/s]


 52%|█████▏    | 7228/13814 [13:16<13:10,  8.34it/s]


 52%|█████▏    | 7229/13814 [13:16<13:11,  8.32it/s]


 52%|█████▏    | 7230/13814 [13:16<14:46,  7.43it/s]


 52%|█████▏    | 7232/13814 [13:17<13:22,  8.20it/s]


 52%|█████▏    | 7233/13814 [13:17<14:08,  7.76it/s]


 52%|█████▏    | 7235/13814 [13:17<14:08,  7.75it/s]


 52%|█████▏    | 7237/13814 [13:17<11:57,  9.17it/s]


 52%|█████▏    | 7239/13814 [13:17<10:22, 10.56it/s]


 52%|█████▏    | 7243/13814 [13:18<09:01, 12.13it/s]


 52%|█████▏    | 7246/13814 [13:18<08:37, 12.69it/s]


 52%|█████▏    | 7248/13814 [13:18<10:45, 10.18it/s]


 52%|█████▏    | 7250/13814 [13:18<11:18,  9.68it/s]


 52%|█████▏    | 7252/13814 [13:19<13:51,  7.89it/s]


 53%|█████▎    | 7254/13814 [13:19<12:48,  8.54it/s]


 53%|█████▎    | 7256/13814 [13:19<11:23,  9.59it/s]


 53%|█████

 56%|█████▌    | 7686/13814 [14:08<18:48,  5.43it/s]


 56%|█████▌    | 7688/13814 [14:08<15:12,  6.71it/s]


 56%|█████▌    | 7689/13814 [14:09<15:09,  6.74it/s]


 56%|█████▌    | 7691/13814 [14:09<13:31,  7.54it/s]


 56%|█████▌    | 7692/13814 [14:09<17:30,  5.83it/s]


 56%|█████▌    | 7693/13814 [14:09<19:05,  5.34it/s]


 56%|█████▌    | 7694/13814 [14:09<17:16,  5.91it/s]


 56%|█████▌    | 7695/13814 [14:09<16:37,  6.14it/s]


 56%|█████▌    | 7697/13814 [14:10<13:47,  7.39it/s]


 56%|█████▌    | 7698/13814 [14:10<12:49,  7.95it/s]


 56%|█████▌    | 7700/13814 [14:10<14:25,  7.06it/s]


 56%|█████▌    | 7701/13814 [14:10<13:23,  7.60it/s]


 56%|█████▌    | 7703/13814 [14:10<11:27,  8.89it/s]


 56%|█████▌    | 7705/13814 [14:11<12:00,  8.48it/s]


 56%|█████▌    | 7707/13814 [14:11<11:20,  8.97it/s]


 56%|█████▌    | 7708/13814 [14:11<13:17,  7.65it/s]


 56%|█████▌    | 7709/13814 [14:11<15:56,  6.38it/s]


 56%|█████▌    | 7710/13814 [14:11<16:07,  6.31it/s]


 56%|█████

 59%|█████▉    | 8137/13814 [15:02<11:23,  8.31it/s]


 59%|█████▉    | 8139/13814 [15:02<13:47,  6.86it/s]


 59%|█████▉    | 8140/13814 [15:03<22:46,  4.15it/s]


 59%|█████▉    | 8141/13814 [15:03<21:58,  4.30it/s]


 59%|█████▉    | 8143/13814 [15:03<19:55,  4.74it/s]


 59%|█████▉    | 8145/13814 [15:04<18:29,  5.11it/s]


 59%|█████▉    | 8147/13814 [15:04<15:54,  5.94it/s]


 59%|█████▉    | 8148/13814 [15:04<14:39,  6.44it/s]


 59%|█████▉    | 8149/13814 [15:04<17:04,  5.53it/s]


 59%|█████▉    | 8151/13814 [15:05<14:40,  6.43it/s]


 59%|█████▉    | 8152/13814 [15:05<15:36,  6.05it/s]


 59%|█████▉    | 8154/13814 [15:05<13:11,  7.15it/s]


 59%|█████▉    | 8157/13814 [15:05<11:29,  8.20it/s]


 59%|█████▉    | 8159/13814 [15:05<09:56,  9.48it/s]


 59%|█████▉    | 8161/13814 [15:06<15:11,  6.20it/s]


 59%|█████▉    | 8163/13814 [15:06<12:18,  7.65it/s]


 59%|█████▉    | 8166/13814 [15:06<10:03,  9.35it/s]


 59%|█████▉    | 8168/13814 [15:06<11:42,  8.04it/s]


 59%|█████

 62%|██████▏   | 8572/13814 [16:00<09:06,  9.60it/s]


 62%|██████▏   | 8574/13814 [16:00<08:40, 10.06it/s]


 62%|██████▏   | 8576/13814 [16:01<10:25,  8.38it/s]


 62%|██████▏   | 8577/13814 [16:01<12:20,  7.07it/s]


 62%|██████▏   | 8579/13814 [16:01<10:18,  8.46it/s]


 62%|██████▏   | 8581/13814 [16:01<08:59,  9.70it/s]


 62%|██████▏   | 8583/13814 [16:01<08:29, 10.26it/s]


 62%|██████▏   | 8585/13814 [16:02<11:13,  7.76it/s]


 62%|██████▏   | 8586/13814 [16:02<12:27,  6.99it/s]


 62%|██████▏   | 8587/13814 [16:02<11:42,  7.44it/s]


 62%|██████▏   | 8588/13814 [16:02<13:41,  6.36it/s]


 62%|██████▏   | 8590/13814 [16:02<14:04,  6.19it/s]


 62%|██████▏   | 8591/13814 [16:03<12:47,  6.81it/s]


 62%|██████▏   | 8593/13814 [16:03<10:59,  7.92it/s]


 62%|██████▏   | 8595/13814 [16:03<10:34,  8.22it/s]


 62%|██████▏   | 8596/13814 [16:03<10:06,  8.60it/s]


 62%|██████▏   | 8597/13814 [16:03<12:06,  7.18it/s]


 62%|██████▏   | 8598/13814 [16:03<11:23,  7.63it/s]


 62%|█████

 65%|██████▌   | 9029/13814 [16:54<04:29, 17.74it/s]


 65%|██████▌   | 9032/13814 [16:55<06:22, 12.50it/s]


 65%|██████▌   | 9034/13814 [16:55<11:56,  6.67it/s]


 65%|██████▌   | 9036/13814 [16:56<13:44,  5.79it/s]


 65%|██████▌   | 9038/13814 [16:56<13:31,  5.89it/s]


 65%|██████▌   | 9039/13814 [16:56<16:01,  4.97it/s]


 65%|██████▌   | 9040/13814 [16:56<14:15,  5.58it/s]


 65%|██████▌   | 9041/13814 [16:57<13:27,  5.91it/s]


 65%|██████▌   | 9043/13814 [16:57<12:12,  6.51it/s]


 65%|██████▌   | 9045/13814 [16:57<09:56,  7.99it/s]


 65%|██████▌   | 9047/13814 [16:57<09:54,  8.02it/s]


 65%|██████▌   | 9048/13814 [16:57<09:49,  8.09it/s]


 66%|██████▌   | 9049/13814 [16:58<12:52,  6.17it/s]


 66%|██████▌   | 9050/13814 [16:58<15:04,  5.27it/s]


 66%|██████▌   | 9051/13814 [16:58<15:09,  5.24it/s]


 66%|██████▌   | 9053/13814 [16:58<12:07,  6.54it/s]


 66%|██████▌   | 9055/13814 [16:58<10:21,  7.66it/s]


 66%|██████▌   | 9057/13814 [16:59<09:56,  7.98it/s]


 66%|█████

 69%|██████▊   | 9486/13814 [17:48<05:58, 12.06it/s]


 69%|██████▊   | 9489/13814 [17:48<05:24, 13.32it/s]


 69%|██████▊   | 9494/13814 [17:48<04:21, 16.54it/s]


 69%|██████▊   | 9497/13814 [17:48<04:35, 15.68it/s]


 69%|██████▉   | 9499/13814 [17:48<05:09, 13.94it/s]


 69%|██████▉   | 9501/13814 [17:49<05:57, 12.06it/s]


 69%|██████▉   | 9503/13814 [17:49<08:09,  8.82it/s]


 69%|██████▉   | 9505/13814 [17:49<09:10,  7.83it/s]


 69%|██████▉   | 9507/13814 [17:50<10:04,  7.13it/s]


 69%|██████▉   | 9508/13814 [17:50<13:18,  5.39it/s]


 69%|██████▉   | 9509/13814 [17:50<12:50,  5.59it/s]


 69%|██████▉   | 9510/13814 [17:50<12:46,  5.62it/s]


 69%|██████▉   | 9512/13814 [17:50<11:32,  6.21it/s]


 69%|██████▉   | 9514/13814 [17:51<09:49,  7.29it/s]


 69%|██████▉   | 9515/13814 [17:51<13:22,  5.35it/s]


 69%|██████▉   | 9516/13814 [17:51<14:50,  4.83it/s]


 69%|██████▉   | 9517/13814 [17:52<17:09,  4.17it/s]


 69%|██████▉   | 9519/13814 [17:52<15:43,  4.55it/s]


 69%|█████

 72%|███████▏  | 9939/13814 [18:41<07:46,  8.31it/s]


 72%|███████▏  | 9941/13814 [18:41<07:04,  9.11it/s]


 72%|███████▏  | 9943/13814 [18:42<06:26, 10.02it/s]


 72%|███████▏  | 9945/13814 [18:42<06:59,  9.23it/s]


 72%|███████▏  | 9947/13814 [18:42<06:54,  9.32it/s]


 72%|███████▏  | 9949/13814 [18:42<06:17, 10.25it/s]


 72%|███████▏  | 9951/13814 [18:42<06:08, 10.48it/s]


 72%|███████▏  | 9954/13814 [18:43<05:50, 11.03it/s]


 72%|███████▏  | 9956/13814 [18:43<05:47, 11.10it/s]


 72%|███████▏  | 9958/13814 [18:43<05:29, 11.69it/s]


 72%|███████▏  | 9960/13814 [18:43<06:06, 10.52it/s]


 72%|███████▏  | 9962/13814 [18:44<07:14,  8.86it/s]


 72%|███████▏  | 9963/13814 [18:44<07:28,  8.59it/s]


 72%|███████▏  | 9964/13814 [18:44<07:15,  8.83it/s]


 72%|███████▏  | 9967/13814 [18:44<06:12, 10.33it/s]


 72%|███████▏  | 9970/13814 [18:44<06:11, 10.33it/s]


 72%|███████▏  | 9972/13814 [18:45<07:19,  8.75it/s]


 72%|███████▏  | 9973/13814 [18:45<07:23,  8.65it/s]


 72%|█████

 76%|███████▌  | 10449/13814 [19:33<04:26, 12.64it/s]


 76%|███████▌  | 10451/13814 [19:33<04:38, 12.10it/s]


 76%|███████▌  | 10454/13814 [19:33<04:46, 11.71it/s]


 76%|███████▌  | 10456/13814 [19:34<07:05,  7.88it/s]


 76%|███████▌  | 10458/13814 [19:34<10:46,  5.19it/s]


 76%|███████▌  | 10459/13814 [19:35<12:38,  4.42it/s]


 76%|███████▌  | 10460/13814 [19:35<11:54,  4.70it/s]


 76%|███████▌  | 10464/13814 [19:35<08:58,  6.22it/s]


 76%|███████▌  | 10469/13814 [19:35<06:45,  8.25it/s]


 76%|███████▌  | 10472/13814 [19:35<05:29, 10.15it/s]


 76%|███████▌  | 10475/13814 [19:36<04:58, 11.19it/s]


 76%|███████▌  | 10477/13814 [19:36<05:20, 10.40it/s]


 76%|███████▌  | 10479/13814 [19:36<05:04, 10.95it/s]


 76%|███████▌  | 10481/13814 [19:36<05:18, 10.47it/s]


 76%|███████▌  | 10484/13814 [19:36<04:18, 12.86it/s]


 76%|███████▌  | 10486/13814 [19:36<04:19, 12.84it/s]


 76%|███████▌  | 10489/13814 [19:37<04:09, 13.33it/s]


 76%|███████▌  | 10491/13814 [19:37<04:15, 12.98

 79%|███████▉  | 10896/13814 [20:25<04:36, 10.54it/s]


 79%|███████▉  | 10898/13814 [20:25<04:17, 11.32it/s]


 79%|███████▉  | 10900/13814 [20:26<05:46,  8.40it/s]


 79%|███████▉  | 10904/13814 [20:26<04:54,  9.87it/s]


 79%|███████▉  | 10906/13814 [20:26<05:03,  9.58it/s]


 79%|███████▉  | 10908/13814 [20:26<05:20,  9.07it/s]


 79%|███████▉  | 10910/13814 [20:27<05:46,  8.38it/s]


 79%|███████▉  | 10911/13814 [20:27<07:28,  6.47it/s]


 79%|███████▉  | 10912/13814 [20:27<07:48,  6.20it/s]


 79%|███████▉  | 10913/13814 [20:27<07:39,  6.31it/s]


 79%|███████▉  | 10914/13814 [20:27<09:55,  4.87it/s]


 79%|███████▉  | 10915/13814 [20:28<11:00,  4.39it/s]


 79%|███████▉  | 10916/13814 [20:28<09:24,  5.13it/s]


 79%|███████▉  | 10917/13814 [20:28<11:12,  4.31it/s]


 79%|███████▉  | 10918/13814 [20:29<13:51,  3.48it/s]


 79%|███████▉  | 10919/13814 [20:29<14:34,  3.31it/s]


 79%|███████▉  | 10920/13814 [20:29<12:59,  3.71it/s]


 79%|███████▉  | 10921/13814 [20:29<13:21,  3.61

 82%|████████▏ | 11341/13814 [21:17<05:23,  7.64it/s]


 82%|████████▏ | 11342/13814 [21:17<06:07,  6.73it/s]


 82%|████████▏ | 11344/13814 [21:18<05:59,  6.88it/s]


 82%|████████▏ | 11346/13814 [21:18<04:52,  8.45it/s]


 82%|████████▏ | 11349/13814 [21:18<03:55, 10.46it/s]


 82%|████████▏ | 11351/13814 [21:18<05:19,  7.71it/s]


 82%|████████▏ | 11353/13814 [21:19<06:53,  5.96it/s]


 82%|████████▏ | 11354/13814 [21:19<07:57,  5.15it/s]


 82%|████████▏ | 11355/13814 [21:19<07:13,  5.67it/s]


 82%|████████▏ | 11356/13814 [21:19<06:22,  6.42it/s]


 82%|████████▏ | 11357/13814 [21:19<06:41,  6.12it/s]


 82%|████████▏ | 11358/13814 [21:20<06:08,  6.66it/s]


 82%|████████▏ | 11359/13814 [21:20<06:32,  6.25it/s]


 82%|████████▏ | 11360/13814 [21:20<06:03,  6.76it/s]


 82%|████████▏ | 11361/13814 [21:20<06:01,  6.78it/s]


 82%|████████▏ | 11363/13814 [21:20<05:31,  7.39it/s]


 82%|████████▏ | 11364/13814 [21:20<05:30,  7.42it/s]


 82%|████████▏ | 11367/13814 [21:21<05:03,  8.06

 85%|████████▌ | 11749/13814 [22:10<04:51,  7.08it/s]


 85%|████████▌ | 11751/13814 [22:11<04:17,  8.00it/s]


 85%|████████▌ | 11753/13814 [22:11<04:16,  8.03it/s]


 85%|████████▌ | 11754/13814 [22:11<05:15,  6.52it/s]


 85%|████████▌ | 11756/13814 [22:11<04:16,  8.04it/s]


 85%|████████▌ | 11758/13814 [22:12<04:56,  6.93it/s]


 85%|████████▌ | 11759/13814 [22:12<04:47,  7.14it/s]


 85%|████████▌ | 11760/13814 [22:12<05:01,  6.80it/s]


 85%|████████▌ | 11762/13814 [22:12<04:18,  7.94it/s]


 85%|████████▌ | 11763/13814 [22:12<04:29,  7.62it/s]


 85%|████████▌ | 11764/13814 [22:12<04:25,  7.73it/s]


 85%|████████▌ | 11766/13814 [22:12<03:58,  8.58it/s]


 85%|████████▌ | 11768/13814 [22:13<03:44,  9.12it/s]


 85%|████████▌ | 11769/13814 [22:13<04:19,  7.89it/s]


 85%|████████▌ | 11770/13814 [22:13<04:15,  8.00it/s]


 85%|████████▌ | 11775/13814 [22:13<03:18, 10.25it/s]


 85%|████████▌ | 11777/13814 [22:13<02:54, 11.65it/s]


 85%|████████▌ | 11779/13814 [22:14<03:48,  8.92

 88%|████████▊ | 12183/13814 [23:02<03:57,  6.88it/s]


 88%|████████▊ | 12184/13814 [23:02<03:48,  7.13it/s]


 88%|████████▊ | 12185/13814 [23:02<03:34,  7.60it/s]


 88%|████████▊ | 12187/13814 [23:02<03:18,  8.20it/s]


 88%|████████▊ | 12188/13814 [23:02<03:16,  8.29it/s]


 88%|████████▊ | 12189/13814 [23:02<03:20,  8.12it/s]


 88%|████████▊ | 12191/13814 [23:03<02:44,  9.85it/s]


 88%|████████▊ | 12193/13814 [23:03<02:37, 10.26it/s]


 88%|████████▊ | 12195/13814 [23:03<02:43,  9.91it/s]


 88%|████████▊ | 12197/13814 [23:03<03:08,  8.57it/s]


 88%|████████▊ | 12200/13814 [23:03<02:36, 10.31it/s]


 88%|████████▊ | 12202/13814 [23:04<04:08,  6.48it/s]


 88%|████████▊ | 12204/13814 [23:04<03:39,  7.34it/s]


 88%|████████▊ | 12206/13814 [23:04<03:23,  7.90it/s]


 88%|████████▊ | 12207/13814 [23:04<03:34,  7.50it/s]


 88%|████████▊ | 12209/13814 [23:05<02:58,  8.98it/s]


 88%|████████▊ | 12211/13814 [23:05<03:02,  8.77it/s]


 88%|████████▊ | 12214/13814 [23:05<02:33, 10.40

 92%|█████████▏| 12640/13814 [23:54<02:00,  9.76it/s]


 92%|█████████▏| 12642/13814 [23:54<01:47, 10.90it/s]


 92%|█████████▏| 12644/13814 [23:55<02:02,  9.54it/s]


 92%|█████████▏| 12646/13814 [23:55<02:21,  8.25it/s]


 92%|█████████▏| 12647/13814 [23:55<03:29,  5.57it/s]


 92%|█████████▏| 12648/13814 [23:56<03:28,  5.59it/s]


 92%|█████████▏| 12650/13814 [23:56<02:49,  6.87it/s]


 92%|█████████▏| 12652/13814 [23:56<02:32,  7.63it/s]


 92%|█████████▏| 12655/13814 [23:56<01:58,  9.75it/s]


 92%|█████████▏| 12657/13814 [23:56<01:56,  9.96it/s]


 92%|█████████▏| 12659/13814 [23:56<02:15,  8.54it/s]


 92%|█████████▏| 12661/13814 [23:57<02:12,  8.71it/s]


 92%|█████████▏| 12663/13814 [23:57<02:08,  8.99it/s]


 92%|█████████▏| 12665/13814 [23:57<02:06,  9.08it/s]


 92%|█████████▏| 12667/13814 [23:58<03:08,  6.08it/s]


 92%|█████████▏| 12668/13814 [23:58<02:49,  6.75it/s]


 92%|█████████▏| 12670/13814 [23:58<02:26,  7.81it/s]


 92%|█████████▏| 12671/13814 [23:58<03:34,  5.34

 95%|█████████▍| 13094/13814 [24:47<01:57,  6.14it/s]


 95%|█████████▍| 13095/13814 [24:48<01:57,  6.11it/s]


 95%|█████████▍| 13096/13814 [24:48<01:56,  6.19it/s]


 95%|█████████▍| 13097/13814 [24:48<02:20,  5.10it/s]


 95%|█████████▍| 13098/13814 [24:48<02:17,  5.22it/s]


 95%|█████████▍| 13099/13814 [24:48<02:22,  5.03it/s]


 95%|█████████▍| 13100/13814 [24:49<02:19,  5.11it/s]


 95%|█████████▍| 13103/13814 [24:49<01:48,  6.58it/s]


 95%|█████████▍| 13105/13814 [24:49<01:30,  7.81it/s]


 95%|█████████▍| 13107/13814 [24:49<01:31,  7.75it/s]


 95%|█████████▍| 13108/13814 [24:49<01:33,  7.53it/s]


 95%|█████████▍| 13110/13814 [24:50<01:38,  7.14it/s]


 95%|█████████▍| 13113/13814 [24:50<01:20,  8.67it/s]


 95%|█████████▍| 13115/13814 [24:50<01:11,  9.80it/s]


 95%|█████████▍| 13117/13814 [24:50<01:05, 10.69it/s]


 95%|█████████▍| 13119/13814 [24:50<00:56, 12.33it/s]


 95%|█████████▍| 13123/13814 [24:50<00:45, 15.12it/s]


 95%|█████████▌| 13125/13814 [24:51<00:47, 14.66

 98%|█████████▊| 13564/13814 [25:40<00:33,  7.42it/s]


 98%|█████████▊| 13565/13814 [25:40<00:42,  5.80it/s]


 98%|█████████▊| 13567/13814 [25:41<00:38,  6.34it/s]


 98%|█████████▊| 13568/13814 [25:41<00:42,  5.81it/s]


 98%|█████████▊| 13569/13814 [25:41<00:44,  5.53it/s]


 98%|█████████▊| 13570/13814 [25:41<00:38,  6.32it/s]


 98%|█████████▊| 13572/13814 [25:41<00:33,  7.14it/s]


 98%|█████████▊| 13573/13814 [25:42<00:35,  6.87it/s]


 98%|█████████▊| 13574/13814 [25:42<00:32,  7.32it/s]


 98%|█████████▊| 13576/13814 [25:42<00:26,  8.89it/s]


 98%|█████████▊| 13578/13814 [25:42<00:25,  9.26it/s]


 98%|█████████▊| 13580/13814 [25:42<00:30,  7.61it/s]


 98%|█████████▊| 13581/13814 [25:43<00:35,  6.54it/s]


 98%|█████████▊| 13582/13814 [25:43<00:32,  7.09it/s]


 98%|█████████▊| 13583/13814 [25:43<00:32,  7.16it/s]


 98%|█████████▊| 13584/13814 [25:43<00:33,  6.94it/s]


 98%|█████████▊| 13586/13814 [25:43<00:30,  7.55it/s]


 98%|█████████▊| 13588/13814 [25:43<00:24,  9.28

0.09829167705830284
---------- Started Epoch 4 -----------





  0%|          | 3/13814 [00:00<21:59, 10.46it/s]


  0%|          | 4/13814 [00:00<30:32,  7.53it/s]


  0%|          | 7/13814 [00:00<24:10,  9.52it/s]


  0%|          | 11/13814 [00:00<19:04, 12.06it/s]


  0%|          | 14/13814 [00:00<17:15, 13.33it/s]


  0%|          | 16/13814 [00:01<25:00,  9.19it/s]


  0%|          | 18/13814 [00:01<26:30,  8.67it/s]


  0%|          | 20/13814 [00:01<26:30,  8.67it/s]


  0%|          | 22/13814 [00:01<23:02,  9.98it/s]


  0%|          | 25/13814 [00:02<18:57, 12.12it/s]


  0%|          | 27/13814 [00:02<17:24, 13.20it/s]


  0%|          | 29/13814 [00:02<26:29,  8.67it/s]


  0%|          | 32/13814 [00:02<22:20, 10.28it/s]


  0%|          | 34/13814 [00:02<21:20, 10.76it/s]


  0%|          | 36/13814 [00:02<18:35, 12.35it/s]


  0%|          | 38/13814 [00:03<20:56, 10.96it/s]


  0%|          | 40/13814 [00:03<20:07, 11.41it/s]


  0%|          | 42/13814 [00:03<23:00,  9.98it/s]


  0%|          | 44/13814 [00:03<28:09,  8.15i

  4%|▍         | 615/13814 [00:47<12:40, 17.35it/s]


  4%|▍         | 618/13814 [00:47<20:25, 10.76it/s]


  4%|▍         | 620/13814 [00:47<18:05, 12.16it/s]


  5%|▍         | 623/13814 [00:48<16:43, 13.15it/s]


  5%|▍         | 625/13814 [00:48<17:27, 12.60it/s]


  5%|▍         | 627/13814 [00:48<17:51, 12.30it/s]


  5%|▍         | 629/13814 [00:48<21:11, 10.37it/s]


  5%|▍         | 631/13814 [00:48<21:08, 10.40it/s]


  5%|▍         | 633/13814 [00:49<24:07,  9.10it/s]


  5%|▍         | 635/13814 [00:49<21:45, 10.09it/s]


  5%|▍         | 637/13814 [00:49<19:02, 11.54it/s]


  5%|▍         | 640/13814 [00:49<18:08, 12.10it/s]


  5%|▍         | 642/13814 [00:49<17:24, 12.62it/s]


  5%|▍         | 646/13814 [00:49<14:38, 14.99it/s]


  5%|▍         | 649/13814 [00:50<13:48, 15.89it/s]


  5%|▍         | 653/13814 [00:50<12:34, 17.45it/s]


  5%|▍         | 656/13814 [00:50<11:53, 18.45it/s]


  5%|▍         | 658/13814 [00:50<11:52, 18.45it/s]


  5%|▍         | 660/13814 [

  9%|▊         | 1185/13814 [01:38<15:50, 13.28it/s]


  9%|▊         | 1187/13814 [01:39<14:53, 14.14it/s]


  9%|▊         | 1189/13814 [01:39<15:21, 13.70it/s]


  9%|▊         | 1191/13814 [01:39<15:22, 13.68it/s]


  9%|▊         | 1194/13814 [01:39<12:58, 16.21it/s]


  9%|▊         | 1197/13814 [01:39<14:28, 14.52it/s]


  9%|▊         | 1199/13814 [01:39<14:17, 14.72it/s]


  9%|▊         | 1201/13814 [01:40<14:57, 14.06it/s]


  9%|▊         | 1203/13814 [01:40<20:55, 10.05it/s]


  9%|▊         | 1205/13814 [01:40<26:44,  7.86it/s]


  9%|▊         | 1207/13814 [01:40<23:47,  8.83it/s]


  9%|▉         | 1209/13814 [01:41<23:34,  8.91it/s]


  9%|▉         | 1211/13814 [01:41<24:43,  8.49it/s]


  9%|▉         | 1212/13814 [01:41<30:57,  6.78it/s]


  9%|▉         | 1215/13814 [01:41<25:33,  8.22it/s]


  9%|▉         | 1217/13814 [01:42<31:57,  6.57it/s]


  9%|▉         | 1218/13814 [01:42<29:19,  7.16it/s]


  9%|▉         | 1220/13814 [01:42<26:10,  8.02it/s]


  9%|▉    

 12%|█▏        | 1695/13814 [02:29<24:54,  8.11it/s]


 12%|█▏        | 1697/13814 [02:29<23:37,  8.55it/s]


 12%|█▏        | 1701/13814 [02:29<18:44, 10.77it/s]


 12%|█▏        | 1703/13814 [02:30<20:54,  9.66it/s]


 12%|█▏        | 1705/13814 [02:30<20:41,  9.75it/s]


 12%|█▏        | 1707/13814 [02:30<19:33, 10.32it/s]


 12%|█▏        | 1709/13814 [02:30<24:22,  8.27it/s]


 12%|█▏        | 1711/13814 [02:31<24:36,  8.19it/s]


 12%|█▏        | 1713/13814 [02:31<20:55,  9.64it/s]


 12%|█▏        | 1715/13814 [02:31<18:12, 11.07it/s]


 12%|█▏        | 1717/13814 [02:31<18:18, 11.01it/s]


 12%|█▏        | 1719/13814 [02:31<17:13, 11.70it/s]


 12%|█▏        | 1721/13814 [02:31<22:01,  9.15it/s]


 12%|█▏        | 1723/13814 [02:32<22:19,  9.03it/s]


 12%|█▏        | 1725/13814 [02:32<24:22,  8.26it/s]


 13%|█▎        | 1729/13814 [02:32<19:23, 10.39it/s]


 13%|█▎        | 1733/13814 [02:32<15:41, 12.82it/s]


 13%|█▎        | 1736/13814 [02:32<13:52, 14.51it/s]


 13%|█▎   

 16%|█▌        | 2227/13814 [03:20<20:25,  9.45it/s]


 16%|█▌        | 2229/13814 [03:20<29:56,  6.45it/s]


 16%|█▌        | 2230/13814 [03:21<36:14,  5.33it/s]


 16%|█▌        | 2231/13814 [03:21<31:55,  6.05it/s]


 16%|█▌        | 2232/13814 [03:21<34:18,  5.63it/s]


 16%|█▌        | 2233/13814 [03:21<44:26,  4.34it/s]


 16%|█▌        | 2234/13814 [03:22<45:23,  4.25it/s]


 16%|█▌        | 2235/13814 [03:22<44:28,  4.34it/s]


 16%|█▌        | 2236/13814 [03:22<40:34,  4.76it/s]


 16%|█▌        | 2238/13814 [03:22<32:10,  6.00it/s]


 16%|█▌        | 2239/13814 [03:22<32:55,  5.86it/s]


 16%|█▌        | 2240/13814 [03:23<44:36,  4.32it/s]


 16%|█▌        | 2241/13814 [03:23<40:11,  4.80it/s]


 16%|█▌        | 2243/13814 [03:23<35:33,  5.42it/s]


 16%|█▌        | 2244/13814 [03:23<36:19,  5.31it/s]


 16%|█▋        | 2245/13814 [03:23<36:32,  5.28it/s]


 16%|█▋        | 2246/13814 [03:24<35:00,  5.51it/s]


 16%|█▋        | 2248/13814 [03:24<29:19,  6.57it/s]


 16%|█▋   

 19%|█▉        | 2643/13814 [04:15<24:21,  7.64it/s]


 19%|█▉        | 2645/13814 [04:16<21:00,  8.86it/s]


 19%|█▉        | 2647/13814 [04:16<20:49,  8.94it/s]


 19%|█▉        | 2650/13814 [04:16<17:02, 10.92it/s]


 19%|█▉        | 2652/13814 [04:16<15:51, 11.73it/s]


 19%|█▉        | 2654/13814 [04:16<17:55, 10.38it/s]


 19%|█▉        | 2656/13814 [04:16<16:45, 11.10it/s]


 19%|█▉        | 2658/13814 [04:17<17:02, 10.91it/s]


 19%|█▉        | 2660/13814 [04:17<20:51,  8.91it/s]


 19%|█▉        | 2662/13814 [04:17<24:33,  7.57it/s]


 19%|█▉        | 2664/13814 [04:18<25:13,  7.36it/s]


 19%|█▉        | 2665/13814 [04:18<25:55,  7.17it/s]


 19%|█▉        | 2666/13814 [04:18<26:55,  6.90it/s]


 19%|█▉        | 2667/13814 [04:18<31:28,  5.90it/s]


 19%|█▉        | 2669/13814 [04:18<28:16,  6.57it/s]


 19%|█▉        | 2670/13814 [04:19<26:59,  6.88it/s]


 19%|█▉        | 2671/13814 [04:19<28:39,  6.48it/s]


 19%|█▉        | 2673/13814 [04:19<29:29,  6.30it/s]


 19%|█▉   

 22%|██▏       | 3097/13814 [05:11<22:07,  8.07it/s]


 22%|██▏       | 3099/13814 [05:11<21:29,  8.31it/s]


 22%|██▏       | 3101/13814 [05:11<22:53,  7.80it/s]


 22%|██▏       | 3103/13814 [05:12<21:29,  8.30it/s]


 22%|██▏       | 3105/13814 [05:12<18:50,  9.47it/s]


 22%|██▏       | 3107/13814 [05:12<16:18, 10.94it/s]


 23%|██▎       | 3110/13814 [05:12<14:46, 12.07it/s]


 23%|██▎       | 3112/13814 [05:12<13:48, 12.92it/s]


 23%|██▎       | 3114/13814 [05:12<19:16,  9.25it/s]


 23%|██▎       | 3116/13814 [05:13<26:51,  6.64it/s]


 23%|██▎       | 3118/13814 [05:13<23:20,  7.64it/s]


 23%|██▎       | 3120/13814 [05:13<21:09,  8.43it/s]


 23%|██▎       | 3122/13814 [05:14<21:11,  8.41it/s]


 23%|██▎       | 3123/13814 [05:14<26:32,  6.71it/s]


 23%|██▎       | 3127/13814 [05:14<20:48,  8.56it/s]


 23%|██▎       | 3129/13814 [05:14<21:22,  8.33it/s]


 23%|██▎       | 3132/13814 [05:14<18:16,  9.74it/s]


 23%|██▎       | 3136/13814 [05:15<15:04, 11.80it/s]


 23%|██▎  

 25%|██▌       | 3495/13814 [06:04<22:29,  7.65it/s]


 25%|██▌       | 3496/13814 [06:04<31:18,  5.49it/s]


 25%|██▌       | 3498/13814 [06:04<26:54,  6.39it/s]


 25%|██▌       | 3499/13814 [06:05<27:43,  6.20it/s]


 25%|██▌       | 3500/13814 [06:05<31:09,  5.52it/s]


 25%|██▌       | 3501/13814 [06:05<33:42,  5.10it/s]


 25%|██▌       | 3502/13814 [06:05<31:15,  5.50it/s]


 25%|██▌       | 3503/13814 [06:05<31:52,  5.39it/s]


 25%|██▌       | 3504/13814 [06:06<34:26,  4.99it/s]


 25%|██▌       | 3505/13814 [06:06<36:55,  4.65it/s]


 25%|██▌       | 3506/13814 [06:06<34:12,  5.02it/s]


 25%|██▌       | 3508/13814 [06:06<27:17,  6.29it/s]


 25%|██▌       | 3511/13814 [06:06<22:47,  7.54it/s]


 25%|██▌       | 3513/13814 [06:07<25:47,  6.66it/s]


 25%|██▌       | 3516/13814 [06:07<20:09,  8.51it/s]


 25%|██▌       | 3518/13814 [06:07<25:25,  6.75it/s]


 25%|██▌       | 3520/13814 [06:08<27:19,  6.28it/s]


 25%|██▌       | 3521/13814 [06:08<29:58,  5.72it/s]


 25%|██▌  

 28%|██▊       | 3914/13814 [06:58<16:42,  9.88it/s]


 28%|██▊       | 3916/13814 [06:58<18:29,  8.92it/s]


 28%|██▊       | 3918/13814 [06:59<18:03,  9.14it/s]


 28%|██▊       | 3920/13814 [06:59<15:19, 10.76it/s]


 28%|██▊       | 3922/13814 [06:59<17:22,  9.49it/s]


 28%|██▊       | 3924/13814 [07:00<27:44,  5.94it/s]


 28%|██▊       | 3926/13814 [07:00<23:49,  6.91it/s]


 28%|██▊       | 3927/13814 [07:00<27:49,  5.92it/s]


 28%|██▊       | 3928/13814 [07:00<27:07,  6.08it/s]


 28%|██▊       | 3930/13814 [07:01<27:18,  6.03it/s]


 28%|██▊       | 3932/13814 [07:01<21:44,  7.58it/s]


 28%|██▊       | 3934/13814 [07:01<21:40,  7.59it/s]


 28%|██▊       | 3935/13814 [07:01<21:18,  7.73it/s]


 28%|██▊       | 3936/13814 [07:01<26:01,  6.33it/s]


 29%|██▊       | 3938/13814 [07:02<25:00,  6.58it/s]


 29%|██▊       | 3939/13814 [07:02<28:13,  5.83it/s]


 29%|██▊       | 3940/13814 [07:02<26:29,  6.21it/s]


 29%|██▊       | 3942/13814 [07:02<25:35,  6.43it/s]


 29%|██▊  

 32%|███▏      | 4354/13814 [07:53<22:21,  7.05it/s]


 32%|███▏      | 4355/13814 [07:54<30:13,  5.22it/s]


 32%|███▏      | 4356/13814 [07:54<38:15,  4.12it/s]


 32%|███▏      | 4357/13814 [07:54<33:12,  4.75it/s]


 32%|███▏      | 4358/13814 [07:54<29:13,  5.39it/s]


 32%|███▏      | 4360/13814 [07:54<25:57,  6.07it/s]


 32%|███▏      | 4362/13814 [07:55<25:16,  6.23it/s]


 32%|███▏      | 4363/13814 [07:55<27:19,  5.76it/s]


 32%|███▏      | 4365/13814 [07:55<23:05,  6.82it/s]


 32%|███▏      | 4368/13814 [07:55<21:02,  7.48it/s]


 32%|███▏      | 4369/13814 [07:56<22:25,  7.02it/s]


 32%|███▏      | 4370/13814 [07:56<22:51,  6.89it/s]


 32%|███▏      | 4373/13814 [07:56<18:21,  8.57it/s]


 32%|███▏      | 4375/13814 [07:56<19:22,  8.12it/s]


 32%|███▏      | 4377/13814 [07:56<18:23,  8.55it/s]


 32%|███▏      | 4378/13814 [07:57<18:35,  8.46it/s]


 32%|███▏      | 4380/13814 [07:57<15:24, 10.21it/s]


 32%|███▏      | 4382/13814 [07:57<14:13, 11.05it/s]


 32%|███▏ 

 35%|███▍      | 4800/13814 [08:47<13:15, 11.33it/s]


 35%|███▍      | 4803/13814 [08:47<11:27, 13.10it/s]


 35%|███▍      | 4805/13814 [08:47<11:14, 13.35it/s]


 35%|███▍      | 4807/13814 [08:47<10:48, 13.90it/s]


 35%|███▍      | 4810/13814 [08:47<10:20, 14.51it/s]


 35%|███▍      | 4812/13814 [08:47<10:42, 14.02it/s]


 35%|███▍      | 4814/13814 [08:48<17:19,  8.66it/s]


 35%|███▍      | 4816/13814 [08:48<21:12,  7.07it/s]


 35%|███▍      | 4818/13814 [08:48<17:10,  8.73it/s]


 35%|███▍      | 4820/13814 [08:49<19:01,  7.88it/s]


 35%|███▍      | 4822/13814 [08:49<18:42,  8.01it/s]


 35%|███▍      | 4824/13814 [08:49<20:07,  7.44it/s]


 35%|███▍      | 4828/13814 [08:49<15:30,  9.66it/s]


 35%|███▍      | 4831/13814 [08:49<13:10, 11.36it/s]


 35%|███▍      | 4833/13814 [08:50<15:58,  9.37it/s]


 35%|███▌      | 4835/13814 [08:50<16:41,  8.97it/s]


 35%|███▌      | 4837/13814 [08:50<14:31, 10.30it/s]


 35%|███▌      | 4839/13814 [08:50<18:25,  8.12it/s]


 35%|███▌ 

# Evaluating Model on the Test Data

The training data for this model can be accessed through the following [link](https://www.comet.ml/lflage/lstm-postagger-training-data/view/new/panels)

| Hyperparameters  || TrainData 1|
|:----------------:||-----------|
| Learning Rate    ||   0,001   |
| Hidden Size      ||   150     |
| Number of Epochs ||   20      |

<img src='./images/Mean Accuracy per Epoch - TrainData.svg' width="1000" height="800">

<img src='./images/Mean Loss per Epoch - TrainData.svg' width="1000" height="800">

In [24]:
path = './models/LSTM_PosTagger_Train - TrainData1.pt'
lstm = LSTMPosTagger(pretrained_embeddings,150,len(tagset))
lstm.load_state_dict(torch.load(path))
lstm.eval()


if os.path.exists(path):
    eval_model(test_dataloader,lstm)

model accuracy: 0.9036


# Conclusions

Evaluating the models created with **Development Data** on the **Test Data** might not be the standard procedure, but it provided a consistent baseline and comparable parameters to train the model on the **Training Data**.

The final accuracy obtained on the **Test Data** was of 90.36% which is comparable with the best scores obtained for the most efficient representative models and the baseline neural models. 